### ISSUE TITLE
Can't launch realsense_navigation / gmapping.launch 

### ISSUE THREAD

**Issue by omershalev** [realsenseai/realsense-ros#100]
### System Configuration

| Version | Your Configuration |
| :-- | :-- |
| Operating System | Ubuntu 16.04.1 LTS |
| Kernel | 4.4.0-34-generic |
| Backend | video4linux |
| ROS | kinetic |
| ROS RealSense | 1.4.0 |
| librealsense | 0.9.1 |
| Camera Type-Firmware | 1.0.72.06 |
### Expected Behavior

roslaunch realsense_navigation gmapping.launch should launch gmapping with TurtleBot&RealSense specific configuration
### Actual Behavior

The following message:

> multiple files named [gmapping.launch] in package [realsense_navigation]:
> - /opt/ros/kinetic/share/realsense_navigation/turtlebot/launch/gmapping.launch
> - /opt/ros/kinetic/share/realsense_navigation/launch/gmapping.launch
>   Please specify full path instead
>   The traceback for the exception was written to the log file
### Steps to Reproduce

> roslaunch realsense_navigation gmapping.launch

**Comment by anelliot** [comment]
I'm guessing you have both of these launch files because you ran the install script twice from different directories (you shouldn't have run it from the turtlebot directory). In the short term, you'll want to delete the /opt/ros/kinetic/share/realsense_navigation/turtlebot/ directory and it's contents. In the long run, realsense_navigation will be removed (this is currently in progress), and you will run all navigation functions directly from the turtlebot package.
