### ISSUE TITLE
[D435] Spurious pointcloud behind object

### ISSUE THREAD

**Issue by SwiftGust** [realsenseai/realsense-ros#1148]
I'm using Realsense D435

I found the pointcloud output is very spurious behind the cylindrical object in front (see below picture)
But I don't want any shadows behind actual obstacle distances
How can I get more accurate, not spurious results?

Resolution tested 
- 480 x 270 / 60 fps 
- 640 x 480 / 30 fps 
with using HighResMediumDensity preset parameters

5 cylindrical object in front and the wall behind, there is nothing else in the scene, pointcloud starts from the cylindrical object and very spurious behind the object. 
![image](https://user-images.githubusercontent.com/13569579/77981357-aae00580-7344-11ea-9667-9d51f8949b7c.png)

**Comment by MartyG-RealSense** [comment]
The pattern of the black areas makes me think that it probably is not a problem  related to light reflecting off the surfaces of the cylinders, as the black areas would likely be more confined to the shape of the cylinders instead of spreading out across the image.

It may be worth observing the same scene with the RealSense Viewer program if you are able to and comparing the results to your own "Camera" program to see whether the code in your application has an influence on the results.  

Also, considering that you are using very low resolution settings, I wonder if "LowResMedDensityPreset.json" may be a more appropriate json to use, since the 'Medium Density' type of jsons are resolution-based.

**Comment by SwiftGust** [comment]
Hi, 
I did additional test with all available parameter set provided.
I chose HighResMedDensity preset since it showed good quality regardless resolution while I was testing across some time ago.

As far as I tested, HighResHighAccuracy preset shows good results regardless of the resolution again, prevents this spurious depth & pointcloud issue.

Shortcoming is that cylinder object becomes too thin and black areas are quite large. 

Realsense Viewer
![HighResHighAcc](https://user-images.githubusercontent.com/13569579/78024283-0fc24c80-7393-11ea-90a2-0fd21982dc82.png)

ROS Demo Pointcloud 
![HighHigh-640x480](https://user-images.githubusercontent.com/13569579/78026845-41d5ad80-7397-11ea-8abe-b12f53be7638.png)

**Comment by MartyG-RealSense** [comment]
I tried to recreate the results that you got with my D435i camera but couldn't.

Would it be possible please to perform a Dynamic Calibration of your camera to eliminate the possibility that the problems with the image result from camera mis-calibration?   The Dynamic Calibrator Tool can be found at the link below.

https://downloadcenter.intel.com/download/28517/Intel-RealSense-D400-Series-Calibration-Tools-and-API

If you are using Linux, the installation instructions for Linux are on page 14 of the Calbrator's user guide:

https://www.intel.co.uk/content/www/uk/en/support/articles/000026723/emerging-technologies/intel-realsense-technology.html

**Comment by SwiftGust** [comment]
In my test environment, I tested both used D435 camera & new D435i camera and both exhibit similar problem.

During trying to work with dynamic calibration tool however, the tool gives me following error while other rs-* example & realsense-viewer programs does work fine in this environment.

None other realsense programs are not running at the same time, plug-out & back-in doesn't help on this matter.

Should I use librealsense built with libusb?

```bash
$ Intel.Realsense.DynamicCalibrator -v
2.6.8.0

$ Intel.Realsense.DynamicCalibrator -list
terminate called after throwing an instance of 'rs2::backend_error'
  what():  get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: Device or resource busy
Aborted (core dumped)

$ Intel.Realsense.DynamicCalibrator 
terminate called after throwing an instance of 'rs2::backend_error'
  what():  get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: Device or resource busy
Aborted (core dumped)

```

- OS : Linux Ubuntu 18.04
- Kernel : 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Realsense : SDK v2.33.1
- D435 Firmware : 0.5.12.03.00
`librealsense2-dkms is already the newest version (1.3.13-0ubuntu1).`

P.S. In the realsense-viewer program I can see "On-chip Calibration" & "Tare Calibration" and these are working, are these do exact same as dynamic calibration tool?

**Comment by MartyG-RealSense** [comment]
The calibration options in the RealSense Viewer are quick and easy "lightweight" functions for depth data improvement that do not provide the full camera calibration that the Dynamic Calibrator tool does.

Do you get the same busy error please if you provide the full path:

/usr/bin/Intel.Realsense.DynamicCalibrator -list

If you are getting similar results with a new D435i though then it may not be a calibration related problem, as the cameras are calibrated in the factory and usually work well when new out of the box.

**Comment by SwiftGust** [comment]
Result is the same with full path execution
```bash
$ /usr/bin/Intel.Realsense.DynamicCalibrator -list
terminate called after throwing an instance of 'rs2::backend_error'
  what():  get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: Device or resource busy
Aborted (core dumped)
```

**Comment by MartyG-RealSense** [comment]
As you got similar results from a new D435i, let's put the calibration aside for a moment and look at other possibilities.  Do the cylinders have a reflective surface such as shiny metal, please?  Such a surface might throw off the camera's ability to analyse their depth, especially if light-sources were shining on them.

**Comment by SwiftGust** [comment]
Nope cylindrical objects are all same PVC or similar plastic pipes and quite a lot of dirts on it but light source would be at behind & up from camera view-point.

Here is picture of the test environment.

**Comment by MartyG-RealSense** [comment]
I don't think that the large black areas at the sides are shadows, because the shadows cast by the cylinders seem to already be accounted for in the image (the blue triangular shapes at the base of the cylinders on your point cloud image roughly correspond to the shadows on the RGB image).

During tests with the RealSense Viewer, I noticed that I seemed to get better alignment of the black areas around objects if I used Color as the texture source instead of Depth.  The process to do this is:

1.  Enable the RGB stream
2.  Enable stereo streaming in 3D point cloud mode.  
3.  At the top of the screen, use the drop-down menu to set the Texture Source to Color instead of Depth.

![image](https://user-images.githubusercontent.com/41145062/78117001-04a40680-73fd-11ea-81c8-b381be038360.png)

**Comment by SwiftGust** [comment]
Thank you for the tip.
Matching depth with color stream seems helps pointcloud quality even for transparent as described in
https://github.com/IntelRealSense/librealsense/blob/jupyter/notebooks/depth_under_water.ipynb

But it doesn't look to me it does improves quality of depth over solid object
the downside seems much reduced FOV of pointclouds and 
possible additional processing on host side(?, not sure) 
Lots of side portion of image is thrown away to matching with RGB FOV from depth image
![RGB Matched Pointcloud](https://user-images.githubusercontent.com/13569579/78137507-69447d00-7460-11ea-8dbf-e800f9a09ccb.png)

**Comment by MartyG-RealSense** [comment]
If you enable the Infrared 1 stream instead of RGB, that should give you the option to use IR as the texture source instead of RGB.  Does that give the same restricted point cloud view, please?

**Comment by SwiftGust** [comment]
Yes, setting "pointcloud_texture_stream" to "RS_STREAM_INFRARED" for realsense-ros does give the same FOV excluding black regions
and to see beyond using without color stream matched parameter "allow_no_texture_points" to "true"
as in README

Then the question is using pointcloud matched with texture does really gives improves quality of depth/pointcloud? 
In static tests, this doesn't seem improves pointcloud better and requires additional processing, seems just post-processing on host-side to me.

**Comment by MartyG-RealSense** [comment]
Intel's camera tuning guide has the following information on use of IR:

*******************

The “LEFT IR” camera has the benefit of always:
1. Being pixel-perfect aligned, calibrated, and overlapped with the depth map, 
2. Perfectly time-synchronized, 
3. Requires no additional computational overhead to align color-to-depth, and
4. Gives no additional occlusion artifacts, because it is exactly co-aligned. 

The main draw-back is that it will normally show the projector pattern if the projector is turned on.

**Comment by SwiftGust** [comment]
I don't think stream matching doesn't take additional processing based on what I tested.
I'm using D435 on embedded device and as I tested using left IR matching with 

- Depth stream : 640 x 480 / 30fps
- IR Stream 1(Left) : 640 x 480 / 30 fps

CPU usage on both cases with only changing pointcloud_texture_stream parameter

-  RS2_STREAM_INFRARED : CPU usage 120% ~ 160%
-  RS2_STREAM_ANY : CPU usage 30% ~ 70 %

CPU clockspeed is set to fixed in this case. 
Stream matching does apparently easier to distinguish from human eyes.
However I'm not sure using IR stream matching does give better quality pointcloud too.

**Comment by MartyG-RealSense** [comment]
If you are using an embedded device with a limited hardware specification then there may be a limit on how much you can improve results, as you may have to use low resolution and not be able to use speed boosting methods such as offloading CPU processing work onto a GPU.

One way to improve the point cloud may be to use two cameras and place them so that their fields of view overlap.  In the areas where the views overlap, you may get better depth detail because there is redundancy in the data (both cameras are observing the same coordinates).  Having two cameras attached to the same device may not be practical though if the embedded device has a low hardware specification or a lack of additional USB ports.

May I ask please what your project goal is in scanning the five cylinders?

**Comment by SwiftGust** [comment]
I did compiled realsense SDK with CUDA but GPU usage is quite minimal, only running D435 to output pointcloud is just using GPU up to 5%, is there more way to utilize GPU further?

I'm using D435 to generate obstacle map around my mobile robot, obstacle may appear in different shape, types including cylindrical object and so on.
However, false pointcloud behind cylindrical objects fused with the wall few meters behind, creates very unusable maps.

**Comment by MartyG-RealSense** [comment]
The RealSense SDK can offload work to GPU with the GLSL Processing Block.  Its effectiveness is limited on low-power devices though.

https://github.com/IntelRealSense/librealsense/pull/3654

I wonder if it would help to set a Depth Clamp so that the camera excludes depth data more than 1 meter from the lens.  This would give it enough time to do obstacle avoidance but prevent the wall behind the cylinders from being rendered.

A quick way to test with the RealSense Viewer whether this would work is to go to the 'Post Processing' section of the Viewer's side options panel, enable the 'Threshold Filter' and set its maximum to '1' meter.

![image](https://user-images.githubusercontent.com/41145062/78640318-72da4480-78a7-11ea-9571-d4cef0924348.png)

**Comment by SwiftGust** [comment]
I just look through rs-gl example and it seems most of realsense-gl functions for windows & rendering and realsense-ros code is quite different from rs-gl examples, couldn't find where the pointcloud is processed, calling process function to pointcloud filter does the job internally 
https://github.com/IntelRealSense/realsense-ros/blob/3ab5077763e980ae72c0c29aec4a697067d43744/realsense2_camera/src/base_realsense_node.cpp#L1480

can you point me how to utilize GLSL in realsense-ros?
just replacing rs::pointcloud to in the following line would offload cpu processing or does need more to utilize it?
https://github.com/IntelRealSense/realsense-ros/blob/3ab5077763e980ae72c0c29aec4a697067d43744/realsense2_camera/src/base_realsense_node.cpp#L1068

changing to ->

```cpp
_filters.push_back(NamedFilter("pointcloud", std::make_shared<rs2::gl::pointcloud>(_pointcloud_texture.first, _pointcloud_texture.second)));
```
I applied this and doesn't seems realsense-ros utilize GPU.

Plus, will realsense-ros support realsense-gl library build option later?

In realsense-ros, applying clip_distance parameter does this job.
Is this the same called threshold filter in realsense-viewer?

**Comment by MartyG-RealSense** [comment]
I was not able to find an equivalent program to rs-gl for ROS to offload CPU work to GPU, unfortunately.  I will link the ROS wrapper developer @doronhi to this discussion for advice on this question of whether the ROS wrapper has GL support or has any plans to add it.

clip_distance is probably different from the threshold filter (there is more than one way to create depth clamps), but may be worth using if it achieves the same end result in ROS as a threshold filter.

**Comment by forestbeach** [comment]
I get a weird image when I set up the camera.  Unusable right now

![image](https://user-images.githubusercontent.com/63427523/78942113-fbfba200-7a86-11ea-844a-a7249dbde023.png)
![realsense camera problems](https://user-images.githubusercontent.com/63427523/78942229-38c79900-7a87-11ea-8ed3-8272644c4a7e.JPG)

**Comment by MartyG-RealSense** [comment]
Could you repeat the On-Chip Calibration in the RealSense Viewer please, pointing it at a flat wall, and see if that corrects your image?

**Comment by forestbeach** [comment]
It was on 3D; 2D worked.  I have to check on 3D downloads.

**Comment by MartyG-RealSense** [comment]
This case will be closed after 7 days from the time of writing this message if there are no further comments.  Thank you.

**Comment by MartyG-RealSense** [comment]
Closed due to no further comments.
