### ISSUE TITLE
Rviz doesn't display map

### ISSUE THREAD

**Issue by Tien-203** [realsenseai/realsense-ros#1153]
Hi every one, I'm trying SLAM with D435i camera following this tutorial [_https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i_] and I get this error.
when I run this command,
"**roslaunch realsense2_camera opensource_tracking.launch**"
rgbd.rviz appear but it doesn't display map and **Global Status: Error , Fixed Frame: Fixed frame [map] does not exist** , **No Image**
Terminal display this Warn
> [ WARN] [1586250842.291481430]: /rtabmap/rtabmap: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
> /rtabmap/rtabmap subscribed to (approx sync):
>    /rtabmap/odom,
>    /camera/color/image_raw,
>    /camera/aligned_depth_to_color/image_raw,
>    /camera/color/camera_info,
>    /rtabmap/odom_info

Sometime terminal display like this
> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
>  07/04 05:15:19,459 WARNING [140036175546112] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
>  07/04 05:15:19,464 WARNING [140036200724224] (uvc-device.cpp:664) interrupt event received: 129, 186, 248, 203, 142, 193, 86, 30, 60, 97, 1, 0, 64, 97, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

Can you help me fix that?
Thanks for your help.
![Screenshot from 2020-03-27 10-11-31](https://user-images.githubusercontent.com/63286216/78652907-5bdc2800-7890-11ea-9391-74e44ae6c3c8.png)

**Comment by MartyG-RealSense** [comment]
In the image that you have kindly supplied, you have a warning exclamation mark next to the 'Image' section.  Could you expand it open please so that we can see the settings inside the Image section please, like in the image from the tutorial shown below?  Thanks!

![image](https://user-images.githubusercontent.com/41145062/78662033-a2994480-78c7-11ea-8b9e-15ecd721fdaa.png)

**Comment by Tien-203** [comment]
Hi @MartyG-RealSense , thanks for your reply
this's my capture, it doesn't have item **map**

![error1](https://user-images.githubusercontent.com/63286216/78736082-4ad7f900-791a-11ea-9c56-b8175f38696d.jpg)

by the way, I using ROS on Ubuntu16.04 on VirtualBox

**Comment by MartyG-RealSense** [comment]
The troubleshooting documentation of the RealSense SDK recommends against using Oracle VirtualBox for a VM installation.  VMWare is recommend instead.

https://github.com/IntelRealSense/librealsense/wiki/Troubleshooting-Q%26A#q-im-using-a-virtual-machine-and-the-camera-is-not-working

https://github.com/IntelRealSense/librealsense/issues/2017

**Comment by Tien-203** [comment]
Hi @MartyG-RealSense , thanks for your reply :))
I tried install VMware and but it still not work.
Sometime I see this error like below image
![error1](https://user-images.githubusercontent.com/63286216/79032231-b5c34300-7b59-11ea-93dd-8fc5c14208ac.jpg)

Sometime it work at a few moment when start then it stuck
![92952966_162636068305613_2188779762846007296_n](https://user-images.githubusercontent.com/63286216/79032354-9973d600-7b5a-11ea-9c4b-f3d9a399a93b.png)
![work1](https://user-images.githubusercontent.com/63286216/79032419-1a32d200-7b5b-11ea-93db-26bbb6369977.jpg)

**Comment by MartyG-RealSense** [comment]
The developer of the ROS wrapper has said "The warning message "interrupt event received" can be ignored and indeed will be removed in future versions".

I would place more significance on the "USB cam overflow" and "USB Rec Overflow" warnings.  This brings to mind a couple of points to check with you:

1.  Are you using the official short USB cable that was supplied with the camera or are you using your own, longer choice of USB cable?  A high quality cable is important for use with RealSense, especially with cable lengths longer than 2 m.  With an own-choice cable that has quality issues, if it is 2 meters or more long then the camera may experience degraded performance or disconnections.

2.  If you are using the official short cable and plugging it directly into the computer or into an unpowered USB hub (one that draws its power from the computer) then errors may occur if the stability of the supplied power to the USB ports is unstable.  A mains-powered USB hub can help to reduce the possibility of these errors occurring, since its power comes from the mains electricity socket and so it is independent of the computer's power supply.

Some users have also found that errors that appeared on low-specification or older computers disappeared when the camera was used on more powerful computers.

**Comment by Tien-203** [comment]
Hi @MartyG-RealSense , thanks for your instruction.
I used the official short cable and plugging into  a mains-powered USB hub, but this error still occur
![error3](https://user-images.githubusercontent.com/63286216/79528297-d3c9ff80-8093-11ea-87a8-889f4970d10d.png)
![error5](https://user-images.githubusercontent.com/63286216/79528298-d593c300-8093-11ea-81ca-d2a56535cf36.png)
Are there something else u can advice for me? thank you

**Comment by MartyG-RealSense** [comment]
Apologies for the delay in responding, as I was researching this issue with the 'Fixed frame [map] does not exist' error.  

Apparently, RViz needs to be able to find a robot's "transformation tree" (TF) and may give this error if it cannot find it.  An answer in the link below suggests that "map" is changed to "base_link" on the **Fixed Frame** setting.

https://stackoverflow.com/questions/52420672/ros-rviz-how-to-visualize-a-point-cloud-that-doesnt-have-a-fixed-frame-transfo

![image](https://user-images.githubusercontent.com/41145062/79566610-c0765e80-80aa-11ea-83e0-6d591ff70af9.png)

**Comment by Tien-203** [comment]
thanks for your instruction @MartyG-RealSense 
I use mains-powered USB hub and run `rs-fw-update -l` to check firmware and type of usb, it's usb2.1 and I change to another computer it's usb3.2. It's work fine
Thank you!

**Comment by MartyG-RealSense** [comment]
I'm glad you found a solution - thanks for the update.   Good luck with your SLAM tests!   :)
