### ISSUE TITLE
Create 2D map 

### ISSUE THREAD

**Issue by Tien-203** [realsenseai/realsense-ros#1196]
Hi every one, I'm trying SLAM with D435i camera following this tutorial [https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i]. I used this command: 
**`rosrun map_server map_saver map:=/rtabmap/proj_map –f my_map_1`**
to create 2D map like tutorial, terminal display something like this 
![image](https://user-images.githubusercontent.com/63286216/81767688-3c759200-9503-11ea-999e-b93bf2217f1d.png) then nothing happened. 
I also wanna run rtabmap_ros with intel d435i like this
![image](https://user-images.githubusercontent.com/63286216/81767897-bdcd2480-9503-11ea-9eb4-06caaef36f97.png)
Can you give me the instruction for these?
Thank you!!!

**Comment by MartyG-RealSense** [comment]
Hi @intel-user   I only see the **rosrun** statement on your terminal.  The step before that would be to launch realsense2_camera with the **roslaunch** statement, otherwise nothing can happen.  Did you do this please after having installed the list of 4 components?

**roslaunch realsense2_camera opensource_tracking.launch**

**Comment by Tien-203** [comment]
Hi @MartyG-RealSense, I already install 4 components and launch realsense2_camera but it still nothing happen.
![image](https://user-images.githubusercontent.com/63286216/81773065-b4e34f80-9511-11ea-917e-d7b30417092c.png)

**Comment by MartyG-RealSense** [comment]
Thanks for the image above.  Your on screen log is full of error warning messages.  It looks as though you are experiencing the same **synthetic stream** related errors that were reported in other cases in April.

https://github.com/IntelRealSense/realsense-ros/issues/1161
https://github.com/IntelRealSense/realsense-ros/issues/1181

To check whether the errors are occurring because your computer is having difficulty coping with the amount of data that is being processed, you could try reducing the FPS speed by modifying the frame rate in the launch file to be '15'.   For example:

https://stackoverflow.com/a/59726945

**Comment by Tien-203** [comment]
hi @MartyG-RealSense, thanks for your reply.
I already reduce FPS to be 15 but is seem nothing change, I can't create 2D map
![image](https://user-images.githubusercontent.com/63286216/81888552-ca1cb480-95cb-11ea-8c52-b274e5a443c4.png)

By the way, can you instruct for me how to use rtabmap display robot's path like this?
![image](https://user-images.githubusercontent.com/63286216/81888768-43b4a280-95cc-11ea-8444-a9e6c9ad1094.png)
Thanks for your help!

**Comment by MartyG-RealSense** [comment]
The fact that you are receiving a 3D point cloud image would seem to indicate that the topics are being successfully published despite the errors in the log (which I would expect to be able to happen so long as the process has not "died").  I can see that you are successfully receiving a color image in RViz too.

The way that the terminal keeps offering advice about -h (help guidance) and suggestions for instruction structuring suggests to me that RViz is having trouble understanding the **rosrun map_server** instruction that you inputted, even though it is the same instruction as the one in Intel's D435i SLAM guide.

Looking at other examples on this map_saver command on the internet, everyone else seems to put the **rtabmap/proj** command on the end of the statement instead of the middle like the D435i SLAM guide does.  Try this please:

**rosrun map_server map_saver -f my_map_1 map:=/rtabmap/proj_map**

In regard to configuring RTABMAP to generate a robot path like the one on the image that you provided: the guidance in the links below seem to be very good:

http://official-rtab-map-forum.67519.x6.nabble.com/Trajectory-Generation-tp192p195.html

http://wiki.ros.org/rtabmap_ros/Tutorials/MappingAndNavigationOnTurtlebot

The first guide makes reference to opening a database.  According to the second guide, a database is saved after mapping at **/.ros/rtabmap.db**

http://wiki.ros.org/rtabmap_ros/Tutorials/MappingAndNavigationOnTurtlebot#Localization_mode

**Comment by MartyG-RealSense** [comment]
Do you require further assistance please or can this case be closed?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
