### ISSUE TITLE
System requirements for Multiple D435 cameras

### ISSUE THREAD

**Issue by cpuwanan** [realsenseai/realsense-ros#1198]
As suggested in [the white paper](https://www.intelrealsense.com/wp-content/uploads/2018/12/Multiple_Camera_WhitePaper_rev1.1.pdf?_ga=2.108153282.1529716005.1589303489-1672391292.1588186491), the Intel i7 with 2.6~3.5GHz could run multiple D415 cameras (connected via USB3.0 ports) successfully. 

However I want like to know more from the community about your experience running the multiple D435 cameras on Ubuntu 16.04 or 18.04, and what computer specifications you are using?

Additionally, I am also looking for the minimum system requirements that can run 2 units of [D435e](https://www.framos.com/en/framos-depth-camera-d435e-camera-only-22806) (connected via Ethernet M12 GigEVision port) on the same host.

Thank you

**Comment by MartyG-RealSense** [comment]
hi @cpuwanan    A computer with an i7 processor would be a good idea for handling 4 RealSense cameras.  For just 2 cameras though, an Up Squared single-board computer should be a reliable choice.

The more cameras that are attached to the same computer / computing device and streaming simultaneously, the higher the burden that will be placed on the USB system and on the computing hardware.  I would consider 4 RealSense 400 Series cameras to be a practical limit for multi-camera simultaneous streaming on the same computer (though Intel have tested 5 cameras of varying model types simultaneously with their **rs-multicam** example program.

https://github.com/IntelRealSense/librealsense/tree/master/examples/multicam

If you would like to be streaming 4 or more cameras simultaneously, I would recommend considering a multi-computer setup (for example, one camera per computer) and then combining all the individual streams together and doing post-processing on the data if necessary.  An example of this is a D435 four-camera volumetric capture demo with a 180 degree field of view that Intel did in January 2018 at the Sundance festival:

https://www.intelrealsense.com/volumetric-capture-using-intel-realsense-d435-cameras/

On a larger scale, the CONIX Research Center at Carnegie Mellon created a point cloud stitching system that could use up to 20 RealSense 400 Series cameras.

https://github.com/conix-center/pointcloud_stitching

If you are going to be using multiple cameras with a single-board computer instead of a full size PC, I would recommend attaching the multiple cameras to a mains electricity powered USB 3 hub that draws its power from a wall power socket.  This will help to ensure that the cameras are provided with stable power (more stable than a direct port connection on the computer may be able to provide) and are provided with enough power (budget for 2W of power for each camera, with the expectation that a single mains powered hub can provide 12W in total).

The USB standard allows for the linking together of up to 5 hubs, in a '5 levels deep' arrangement.

In regard to technical support for the D435e: this is handled by FRAMOS, as it is not an Intel product.  Their support email address is support@framos.com

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
