### ISSUE TITLE
fatal:you need to specify a tag name

### ISSUE THREAD

**Issue by Jenny0420** [realsenseai/realsense-ros#1220]
raspberry 4 4G
ubuntu 18.04 LTS
kernel: 5.3.0-1026-raspi2
I need run my relasense d435 on ros melodic
I have download the librealsense v2.33.1
when I run " ./scripts/patch-realsense-ubuntu-lts.sh"
as this picture
![4f355f3fbdca8b21af4b35de5958fb2](https://user-images.githubusercontent.com/43374977/83392553-ddcb7600-a427-11ea-9f15-1b48a358f8ae.jpg)

Can anyone please give me some suggestion on how to solve the problem ?

Thank you in advance.

**Comment by MartyG-RealSense** [comment]
In case Librealsense is having a conflict with your kernel, I would recommend instead installing librealsense through the RSUSB "backend" method, which requires an internet connection.  It is not dependent on Linux versions, kernel versions or patches, so you do not need to apply the patch script.

1.  Obtain the Librealsense source code.  If you have tried already to install SDK 2.33, you probably already have the unzipped Librealsense folder.

If you do not have it, you can visit the link below, go to the 'Assets' list at the bottom of its page and download the source-code zip file.  Then un-zip it.

https://github.com/IntelRealSense/librealsense/releases/tag/v2.33.1

![image](https://user-images.githubusercontent.com/41145062/83406499-aef0d800-a406-11ea-9775-2c1c4b53b552.png)

2.  In the unzipped Librealsense folder, go to the **Build** directory (Librealsense > Build).

If you do not have a Build folder, use the command below whilst in the Librealsense root folder to create one and navigate to it:

**mkdir build && cd build**

3.  Run the CMake command below whilst in the Build directory to install Librealsense:

**cmake ../ -DFORCE_RSUSB_BACKEND=true -DCMAKE_BUILD_TYPE=release -DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true**

**Comment by Jenny0420** [comment]
@MartyG-RealSense
thanks very much,but I have meat a new error
I have already ran "realsense-viewer" successfully
but I need use  realsense with ros
[https://github.com/IntelRealSense/realsense-ros](url)
when I run "roslaunch realsense2_camera rs_camera.launch"
I have got a new error
[error_launch.txt](https://github.com/IntelRealSense/realsense-ros/files/4721862/error_launch.txt)
In this txt,you can see 
" 03/06 06:36:24,315 WARNING [281472082633088] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 12, 
[ WARN] [1591166184.355585657]: Hardware Notification:USB REC overflow,1.59117e+12,Error,Hardware Error"

how can I do.And thanks for adviance

**Comment by MartyG-RealSense** [comment]
The **USB REC overflow** error suggests that more data is being generated than the USB can handle.  

You could try adding **enable_infra2:=false** to your roslaunch statement to disable infrared2 and free up USB bandwidth.  For example:

**roslaunch realsense2_camera rs_camera.launch enable_infra2:=false**

Doronhi the RealSense ROS wrapper developer has said "It will have no effect on the depth quality.  It only disable the infra2 images' transmission via the USB port.  They are still taken and the depth is calculated using them inside the device".

**Comment by Jenny0420** [comment]
I have already tried your suggesstion ,but it didn't work
![Screenshot from 2020-06-03 09-14-26](https://user-images.githubusercontent.com/43374977/83619657-c4a8fd80-a5be-11ea-8dc7-d5fa8e3f0d3b.png)

 I can't get the picture in RViz,but I can get the picture when I run "realsense-viewer"

**Comment by MartyG-RealSense** [comment]
How often do the **control_transfer returned** messages appear?   Once a minute, or more often?

**Comment by Jenny0420** [comment]
@MartyG-RealSense 
thanks for your suggesstion.
I've tried your method, but it doesn't work
![Screenshot from 2020-06-03 09-14-26](https://user-images.githubusercontent.com/43374977/83630073-c7f7b580-a5cd-11ea-88e8-8a68e8229232.png)
I can't get the picture in RViz,but i can get the picture when i run 'realsense-viewer'

**Comment by doronhi** [comment]
@Jenny0420 , Are you familiar with RViz? To see the picture you need to do the following on RViz:
Add->"By Topic" tab -> /camera/color/image_raw/Image

**Comment by Jenny0420** [comment]
@doronhi 
sorry
I have chosed Add->By display ->pointcloud(and pointcloud2)
but nothing happend
I should choose "By Topic"
And i find that in depth->image_rect_raw->(camera or depthcloud) the refreash time of camera is very long almost 1.5s
by raspberrypi 4 4G

**Comment by Jenny0420** [comment]
with rapberrypi4 4gMem
when i only turn on the RGB camera
4CPU used almost 90%
4GMem used 1.48G
![1 4](https://user-images.githubusercontent.com/43374977/83639177-e0230100-a5dc-11ea-83ee-2a04a04af418.jpg)
but when i turn on the depthcloud 
4CPU used almost 95%
4GMem used 3.6G
![3 6](https://user-images.githubusercontent.com/43374977/83639430-4576f200-a5dd-11ea-854f-325c121d1b1e.jpg)
and the RViz will be broken

**Comment by MartyG-RealSense** [comment]
@Jenny0420  Do you still require assistance with this case please or can it now be closed?  Thanks!

**Comment by MartyG-RealSense** [comment]
Thanks so much for the update!

**Comment by JHPHELAN** [comment]
@doronhi @MartyG-RealSense 
Has the "tag" issue been resolved for ARM devices e.g. Raspberry Pi and Jetson Nano?
Having to "backend" with RSUSB instead of V4L causes severe performance degradation as referenced here:
[https://github.com/IntelRealSense/realsense-ros/issues/2068#issuecomment-924590313](url)
With ROS2 being the future and the ARM platforms so popular, it seems a straightforward "sudo apt install ..." should be a priority project.  Am I wrong?  I last tried on LibRealSense v2.50.
Appreciate, as always, your prompt and thoughtful responses!
JHP

**Comment by MartyG-RealSense** [comment]
My understanding is that if libralsense is built from packages on Jetson instead of source code - as referenced by Doronhi in https://github.com/IntelRealSense/realsense-ros/issues/1110#issuecomment-596517559 - then the build will also be based on the RSUSB backend.  So building from the dedicated Jetson packages instead of source code may not be a solution if RSUSB gives you performance degradation.

The Jetson installation instructions do though offer the option of a non-RSUSB build from source code with the **V4L Native Backend**, which has a dedicated patch script **patch-realsense-ubuntu-L4T.sh** instead of the 'patch-realsense-ubuntu-lts.sh' one used on x86 / x64 non-RSUSB source code builds. 

https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md#building-from-source-using-native-backend

In regard to the Doronhi comment that you linked to at https://github.com/IntelRealSense/realsense-ros/issues/2068#issuecomment-924590313 - Intel made updates to the RSUSB backend in librealsense 2.50.0 that are described in https://github.com/IntelRealSense/librealsense/pull/9821  

There was a recent report though from a RealSense user that said that they had RSUSB problems with 2.50.0 that disappeared if they used the previous SDK version 2.49.0.  As there is not a matching ROS wrapper version for 2.49.0 though, then I would recommend using **2.48.0**.
