### ISSUE TITLE
A few depth image problems of D430  camera module

### ISSUE THREAD

**Issue by dingbaiyin** [realsenseai/realsense-ros#1221]
My company uses the D430 camera module. The camera is fixed on the aluminum metal frame by manual installation. As shown in picture 1, we encountered several image problems during the use of D430
1. In automatic exposure mode, when the light is weak at night, there will be small black spots on the edge of the target object, as shown in Figure 2
2. The depth image is ok, but the 3D point cloud image will have pits, as shown in Figures 3 and 4
3. After using the calibrated depth camera for a period of time, the acquired depth image has a lot of overall deviation in the Z-axis direction, and can be restored after re-calibration
What are the causes of these 3 problems and how to avoid them?
4. What are the areas of D430 installation that need improvement and attention, I hope you can give some suggestions

<img width="1065" alt="D430安装方式" src="https://user-images.githubusercontent.com/40271689/83415084-20ee0f00-a451-11ea-9f04-bbf1acd444af.png">
<img width="484" alt="small black spots on the edge of the pig" src="https://user-images.githubusercontent.com/40271689/83415607-e6d13d00-a451-11ea-8c28-9c58f895637e.png">
![b827eb0e41d5_100000001_2020-05-11-14-49-16_test_0 00_0 00_0 00_0_1](https://user-images.githubusercontent.com/40271689/83415724-2435ca80-a452-11ea-9f91-9e1675acae01.png)

<img width="732" alt="3D point cloud image of a pig" src="https://user-images.githubusercontent.com/40271689/83416266-0026b900-a453-11ea-86bd-8ef8436c0410.png">

**Comment by dingbaiyin** [comment]
this is figure 3，that is the depth map with the most 3D point cloud image above
![b827eb0e41d5_100000001_2020-05-11-14-49-16_test_0 00_0 00_0 00_0_1](https://user-images.githubusercontent.com/40271689/83417025-1b45f880-a454-11ea-93dc-c8786a8b9de9.png)

**Comment by dingbaiyin** [comment]
this is figure 3，that is the depth map with the most 3D point cloud image above
![b827eb0e41d5_100000001_2020-05-11-14-49-16_test_0 00_0 00_0 00_0_1](https://user-images.githubusercontent.com/40271689/83417475-b9d25980-a454-11ea-8d50-8e08a4f4562c.png)

**Comment by MartyG-RealSense** [comment]
1.  You could try using the "High Density" visual preset, as it prioritises a high 'fill rate' and so can fill more holes.  Using "High Accuracy" preset will increase the risk of holes occurring.  "Medium Density" provides a balance between accuracy and fill-rate.

You could also try increasing the "Laser Power" value.  This may result in increased camera operating temperature but can reduce sparseness in the depth image

Another option would be to apply a Hole Filling post-processing filter to the depth image.

2.  The black areas in Figure 3 look like the kind of holes that a Hole Filling filter would help to close up.

3.  Assuming that there is not severe vibration passing through the mounting point, and the camera is unable to be physically knocked by a human due to its mount position, a mis-calibration of the camera after a period of time might occur if the D430 module is exposed to high temperature.

Whilst the camera is streaming, you can check the ASIC Temperature (camera board temperature) and the Projector Temperature in the RealSense Viewer, under the "Controls" section of the options side-panel.

If the ASIC Temperature is over 42 degrees C, temperatures above that are when problems may start occurring in the output image.

If the Projector Temperature exceeds 60 degrees C for several seconds, the Laser Power will first be halved and then the laser will shut off if the temperature continues to be excessive.

Conceivably, if the Protector Temperature exceeds 60 degrees but the Laser Power is at its default setting, a halving of the laser power could cause the depth data to become sparse and result in holes.

4.  If there is excessive temperature and it is generated by the camera board and not by an external temperature source, adding an improved 'heat sink' component to the design to draw heat away from the board more effectively may reduce the likelihood of a temperature-caused mis-calibration.

Page 83 of the current edition of the data sheet document for the 400 Series cameras provides design guidance about a heat sink.

https://dev.intelrealsense.com/docs/intel-realsense-d400-series-product-family-datasheet

Also, it is worth mentioning that care should be taken when handling the depth module during installation, as mis-calibration can occur if the module is physically flexed when being handled, requiring a re-calibration to correct it.

Regarding the flex cable that connects the Vision Processor D4 board and the depth module: there is also a rigid inter-connector board that is available.  As far as I know it does not offer a performance advantage over cable, but I mention it in case you want to incorporate it into your product design.

https://www.framos.com/en/d400-rigid-50-pin-interposer-20737

**Comment by dingbaiyin** [comment]
Thank you ，I read the  intel-realsense-d400-series-product-family-datasheet .This is very useful for us.
I find that ASIC Temperature is higher than 42 degrees most of the time and it is difficult to drop below 42 degrees Celsius
I still have a few questions:
1. When we use a Hole Filling post-processing filter to the depth image, the speckle of the depth image is obviously reduced, so will the image effect of the corresponding 3D point cloud be improved or not?
2. From the depth image, the image of the pig is quite complete, but from the 3D point cloud image, the back of the pig is not flat and smooth, and even a large depression appears as shown in the picture. What causes this and how to avoid it. I'm sorry this question I mentioned earlier but still don't understand
depth image:
![b827eb0e41d5_100000001_2020-05-11-14-49-16_test_0 00_0 00_0 00_0_1](https://user-images.githubusercontent.com/40271689/83474717-3ac63b00-a4bf-11ea-9fb3-e4fe31252b1c.png)
point cloud image :
<img width="1034" alt="pointCloud poor" src="https://user-images.githubusercontent.com/40271689/83475197-6e559500-a4c0-11ea-81d8-a75a52f704c5.png">
this is two imgae 
The point cloud image does not look very clear. This is the Baidu cloud link address of two pictures, which can be downloaded and viewed

**Comment by MartyG-RealSense** [comment]
1.  Yes, the Hole-Filling Filter works in 3D point cloud mode as well as 2D mode.

2.  It looks as though there is a lot of waviness in the point cloud image.The links below on reducing waviness and "ghost noise" may be a useful reference.

https://github.com/IntelRealSense/librealsense/issues/4553

https://github.com/IntelRealSense/librealsense/issues/1375

**Comment by dingbaiyin** [comment]
Great, I will try.Thank you !

**Comment by MartyG-RealSense** [comment]
Hi @dingbaiyin  do you still require assistance with this case please, or can it be closed?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by bestaps** [comment]
@dingbaiyin where did you get the cable from? we are looking for suppliers for the same.

**Comment by MartyG-RealSense** [comment]
Hi @bestaps   If you are looking for a pre-made **interposer cable** to connect the Vision Processor D4 to the Depth Module board, or the rigid board connector version, the Intel authorized company FRAMOS can supply them:

**FRAMOS**

**Cable**
Different lengths can be selected using the **Cable length (m)** drop-down menu.

https://www.framos.com/en/hsf50-22273

**Board**
https://www.framos.com/en/d400-rigid-50-pin-interposer-20737

Other suppliers for the rigid board can be found by googling for **intel interposer 956827**
