### ISSUE TITLE
It support Realsense D455 now?

### ISSUE THREAD

**Issue by Zhan-Jia-Rong** [realsenseai/realsense-ros#1320]
I used "Method 1" to install the device,then i modify "device_type" to d455.
But it doesn't work.
![realsense](https://user-images.githubusercontent.com/54267059/89501282-a85f5200-d7f5-11ea-862a-ee4d0f6ad683.png)
![realsense2](https://user-images.githubusercontent.com/54267059/89501287-aac1ac00-d7f5-11ea-910d-7fdf4062aca4.png)

thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Zhan-Jia-Rong   Version 2.2.15 of the RealSense ROS wrapper for matching with SDK 2.36.0 does not contain official support for D455.

![image](https://user-images.githubusercontent.com/41145062/89510102-0f661200-d7c8-11ea-8318-ada5b528d5f9.png)

I am not involved in ROS wrapper development.  It is likely though that official D455 support will be added in an upcoming version of the wrapper.

In the meantime, you could try setting the default device to D435i to see if it works as a temporary workaround, since the D455 is similar to the D435 and has an IMU too.

**Comment by MrMixit** [comment]
Hey @Zhan-Jia-Rong! I just asked the same question in #1318 yesterday, and very recently they made a new commit that added support for this device!

**Comment by MartyG-RealSense** [comment]
@MrMixit  Thanks so much for highlighting this, I hadn't seen it.

**Comment by Zhan-Jia-Rong** [comment]
After I installed it using "Method 2", I will try your proposal. 
Thanks for your reply！
