### ISSUE TITLE
Can't change the framerate of the camera even with a lower resolution

### ISSUE THREAD

**Issue by ChunYe173** [realsenseai/realsense-ros#1338]
Hi,

I am working with Intel Realsense D435 camera on ubuntu 16.04. I am trying to make the camera to publish image of 60fps with resolution of 424x240 based on the realsense-viewer. I changed the resolution and the frame rate of the color module image in the launch file and it shows in the terminal that the camera is publishing image of 424x240 with 60fps when I run the command _roslaunch realsense2_camera rs_camera.launch_ . But the command _rostopic hz /camera/color/image_raw_ shows that the camera is only publishing image of an average rate of 30fps but not 60fps. Attach is the pictures that I took to further explain the situation above. Please assists. Thanks

![Realsense-viewer screenshot](https://user-images.githubusercontent.com/66294422/90609733-0dc03380-e237-11ea-9557-ec1ed616dd73.png)

![WhatsApp Image 2020-08-19 at 3 41 56 PM (2)](https://user-images.githubusercontent.com/66294422/90609848-38aa8780-e237-11ea-93ee-c67c0a2a4b4e.jpeg)

![WhatsApp Image 2020-08-19 at 3 41 56 PM](https://user-images.githubusercontent.com/66294422/90610100-8b843f00-e237-11ea-9ffa-dd5f1891861d.jpeg)

![WhatsApp Image 2020-08-19 at 3 41 56 PM (1)](https://user-images.githubusercontent.com/66294422/90610124-92ab4d00-e237-11ea-9835-57fd7495661d.jpeg)

![WhatsApp Image 2020-08-19 at 4 11 38 PM](https://user-images.githubusercontent.com/66294422/90610062-81624080-e237-11ea-9991-7cd7654c9841.jpeg)

**Comment by MartyG-RealSense** [comment]
Hi @ChunYe173    I replicated your setup in the RealSense Viewer with a D435i.  I set RGB to 60 FPS and RGB8 on a USB2 connection.  Looking at the FPS information during streaming, I observed that when auto-exposure was enabled, FPS was around 33 instead of 60.  When auto-exposure was disabled, the FPS leapt to 59.5.

Under the **Controls** section of the RGB options, if the option **Auto-Exposure Priority** is disabled whilst auto-exposure is enabled then FPS becomes around 59.5.  This is because having Auto-Exposure enabled and Auto-Exposure Priority on the RGB controls disabled forces the camera to try to keep to a constant FPS.

I repeated the tests on a USB 3 connection and the results were identical.

You should be able to test whether these principles affect the color FPS in the RealSense ROS wrapper in the same way by accessing the **enable_auto_exposure** and the **auto_exposure_priority** controls through the RGB section of the controls in the **dynamic_reconfigure** interface (which allows you to change camera settings after roslaunch during runtime).

https://github.com/IntelRealSense/realsense-ros#set-camera-controls-using-dynamic-reconfigure-params

**Comment by ChunYe173** [comment]
Hi @MartyG-RealSense ,

I have tried the solution that you provide. Its really helpful and the Intel Realsense D435 camera can now publish image of 60fps. Thanks a lot!

**Comment by MartyG-RealSense** [comment]
Great news that the method worked for you - thanks for the update!
