### ISSUE TITLE
Mainstream project to use RealSense device on ROS2

### ISSUE THREAD

**Issue by atinfinity** [realsenseai/realsense-ros#1456]
I hope to use RealSense device on ROS2. And, there is the following project.

- https://github.com/IntelRealSense/realsense-ros
- https://github.com/intel/ros2_intel_realsense

Which is the mainstream project as Intel?
Please tell me your recommended project.

**Comment by MartyG-RealSense** [comment]
Hi @atinfinity   The ROS1 wrapper is the most well-developed because it has had multiple releases over a number of years.  The ROS2 wrapper, which currently targets ROS2 Eloquent, is relatively new at the time of writing this.   RealSense support of ROS2 is considered as important as ROS1, so whilst its wrapper is recent, it should not be thought of as being less mainstream than ROS1.  The ROS2 wrapper code also has the advantage of being strongly based on the ROS1 wrapper code.

The discussion in the link below gives a good general overview of plans for the ROS2 wrapper by the RealSense ROS wrapper developer @doronhi 

https://github.com/IntelRealSense/librealsense/issues/5825

**Comment by atinfinity** [comment]
@MartyG-RealSense Thank you for your reply. I'll read this issue.

**Comment by JaehyunShim** [comment]
@MartyG-RealSense @atinfinity
It looks like the question is why there are two separate repositories for ROS2 packages (or which one is the mainstream). As far as what I can see from the contributor list, the second repository was developed by the intel team in China but it is not maintained at all.

**Comment by JaehyunShim** [comment]
@MartyG-RealSense I mentioned it already in another issue thread, but if you guys are not going to maintain it, archive it and guide users to the mainstream repository (the first link) so they send PRs there, not to the deprecated one.

**Comment by MartyG-RealSense** [comment]
Hi @JaehyunShim   The currently developed ROS2 wrapper is the one in the link below, which supports **ROS2 Eloquent**:

https://github.com/IntelRealSense/realsense-ros/tree/eloquent

I believe that the wrapper with dormant development that you refer to is this one:

https://github.com/intel/ros2_intel_realsense

It is hosted on the general **Intel** GitHub site, not the dedicated **RealSense ROS** GitHub.  RealSense projects on the main Intel GitHub do occasionally occur, an example of this being a project to display RealSense depth streams in a web-browser.

https://github.com/intel/depth-camera-web-demo

The RealSense ROS team would not have control over the content hosted on the main Intel GitHub by other developers outside of its team.
