### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by limitedboom** [realsenseai/realsense-ros#1464]
I tried installing this on my Raspberry Pi 4 with ROS and tried running the line of sudo apt-get install ros-$ROS_VER-realsense2-camera. I tried this with both the export kinetic and export melodic steps, but get the error of "Unable to lcoate package ros--realsense2-camera. would anyone know why this would be happening because I tried different githubs for intel realsense installation but get this same error one way or another when installing.

**Comment by MartyG-RealSense** [comment]
Hi @limitedboom   Can you confirm please whether you are using the Raspbian or the Ubuntu OS on your Pi 4?  The official installation instructions are suited for use with Ubuntu.  

If you are using Raspbian then I would recommend a librealsense + ROS installation guide designed for Raspbian and Pi 4.

A good example of such a guide is the **eleccelerator** one, which explains errors that might occur at each step and fixes for them.

https://eleccelerator.com/wiki/index.php?title=Raspbian_Buster_ROS_RealSense

**Comment by limitedboom** [comment]
I am using Ubuntu.

**Comment by MartyG-RealSense** [comment]
Thank you very much for the confirmation of the OS that you are using.

I believe that the best source of information for your situation (Pi 4 with Ubuntu trying to install ROS and the RealSense ROS wrapper) will be the instruction guide contributed by a RealSense user in the link below.

https://support.intelrealsense.com/hc/en-us/community/posts/360049881094/comments/360014049813

In that guide, the RealSense user installs the RealSense ROS wrapper on their Pi by building the ROS wrapper from source with **Method 2** instead of the package-based installation in the **Method 1** that you used.

https://github.com/IntelRealSense/realsense-ros#step-2-install-intel-realsense-ros-from-sources

**Comment by MartyG-RealSense** [comment]
Hi @limitedboom   Do you require further assistance with this case, please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
