### ISSUE TITLE
Is there any difference between the depth information of realsense-viewer and realsense-ros?

### ISSUE THREAD

**Issue by Hiroaki-K4** [realsenseai/realsense-ros#1579]
Hi.
I am using realsense for 3D object detection. The data taken with the real sense-viewer is used as the training data. At the time of inference, we use the depth information from realsense-ros.
So I have a queation about depth information by realsense. Is there any difference between the depth information of realsense-viewer and realsense-ros(/camera/depth/image_rect_raw)? For example, Maximum depth distance, etc.
Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Hiroaki-K4   Aside from technical differences in how RealSense ROS handles data compared to librealsense (since the ROS wrapper aims for data to be compliant with ROS standards), RealSense Viewer also applies a range of post-processing filters to the data by default.  

These can be turned off manually.  You can do so individually for each filter or entirely by left-clicking on the blue icons - signifying an On state - to turn them off) in the **Post Processing** section of the options side-panel under the **Stereo Module** section.  

The Viewer's post-processing filter set has a **Threshold Filter** that sets the minimum and maximum observable depth distance, excluding data from the image that is beyond this distance.  When enabled, this filter imposes a maximum depth distance of 4 meters by default (though it is manually editable).  

In RealSense ROS, filters have to be configured manually - for example, by defining them in the roslaunch instruction.  Also, not all filters supported in librealsense are present in the RealSense ROS wrapper.  Instead of a Threshold Filter, the wrapper has a **clip_distance** parameter to set maximum distance.

![image](https://user-images.githubusercontent.com/41145062/102600365-9fbd4780-4116-11eb-926d-a2df35a4cb18.png)

**Comment by Hiroaki-K4** [comment]
@MartyG-RealSense 
Thank you for reply. I understood!

**Comment by MartyG-RealSense** [comment]
Thanks very much @Hiroaki-K4 for the update!
