### ISSUE TITLE
Rtabmap..cpp:1148::process() RGB-D SLAM mode is enabled, memory is incremental but no odometry is provided. Image 76684 is ignored!

### ISSUE THREAD

**Issue by punchnami** [realsenseai/realsense-ros#1635]
| Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       | { D435i } | 
| Firmware Version                   | (05.12.09) | 
| Operating System & Version |   Linux (Ubuntu 18.04.5)   | 
| Kernel Version (Linux Only)    |  (4.9.14)                                         | 
| Platform                                 | NVIDIA Jetson NANO  |
| SDK Version                            |  2.0                          | 

After I followed all the instruction and  used the command
`roslaunch realsense2_camera opensource_tracking.launch `

Everything works just fine for a while with the **odo quality** values appear on the log then it gave the value of 0  with warning and error as seen in the picture below

![odo](https://user-images.githubusercontent.com/48686073/105334024-faabf800-5c08-11eb-8a71-812a3150401f.png)

I tried executing the following command but the problem still occurs.

`roslaunch realsense2_camera opensource_tracking.launch enable_gyro:=true enable_accel:=true enable_infra:=true`

**Secondly**, to save the rosbag file, the rviz program should be opened while saving? (I was trying save the rosbag file while the rviz program was executing, it didn't stop and the file size was up to 89Gb so I Ctrl+c the terminal respectively)

Thank you in advance!
Any help is appreciated :)

**Comment by MartyG-RealSense** [comment]
Hi @punchnami   Are you following the instructions in Intel's D435i SLAM guide that uses **roslaunch realsense2_camera opensource_tracking.launch**, please?  

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

If you are using this guide and are having problems with loss of tracking (a possibility that the guide warns about), then use of **RTABMAP** has been discussed in regard to resetting odometry with **relocalization**.

https://github.com/IntelRealSense/realsense-ros/issues/1529

In regard to the question about rosbag recording: since **rosbag record** records the contents of published topics, I would not think that it would be necessary to have RViz active during the recording, as RViz is "vizualizing" the contents of the published topics.  

http://wiki.ros.org/rosbag/Commandline#rosbag_record

Bag files recorded in the librealsense SDK are often multi-gigabyte in size though, so I would expect a similar file size from a bag created with rosbag record if it is a lengthy recordng session.  It is probably unrelated to RViz being open, and instead related to the fact that bag files are commonly large in size due to the file format.

**Comment by punchnami** [comment]
Thank you for your response as always! @MartyG-RealSense , I tried to slow down the movement of my camera and it's in fact affected the odometry values and didn't break the sequences! 

And yes, I did the installation as instructed in Intel's D435i SLAM guide but there're another problem when I tried to play my recorded rosbag file with the following command 

`roscore >/dev/null 2>&1 &
rosparam set use_sim_time true
rosbag play my_bagfile_1.bag --clock
roslaunch realsense2_camera opensource_tracking.launch offline:=true`

The Global status showed an error: Fixed Frame [map] does not exist and the TF status showed warning, is it normal ?

![rvizerror](https://user-images.githubusercontent.com/48686073/105663224-49f17180-5f04-11eb-97ec-b40cf1de9a2d.png)

**Comment by MartyG-RealSense** [comment]
Given that the roslaunch for this D435i SLAM tutorial now requires additional instructions to enable the IMU after ROS wrapper version **2.2.15**, it may be that you need to add the same terms to the offline roslaunch instruction to enable those topics in order to play back the bag.

roscore >/dev/null 2>&1 &
rosparam set use_sim_time true
rosbag play my_bagfile_1.bag --clock
roslaunch realsense2_camera opensource_tracking.launch offline:=true **enable_gyro:=true enable_accel:=true enable_infra:=true**

**Comment by punchnami** [comment]
Oh I see, thank you so much @MartyG-RealSense !
