### ISSUE TITLE
How to use realsense D435 to get the topic:/camera/color/Image_raw/compressed?

### ISSUE THREAD

**Issue by GitZzw** [realsenseai/realsense-ros#1641]
I only got these topics:
/camera/color/camera_info
/camera/color/image_raw
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/extrinsics/depth_to_color
/camera/motion_module/parameter_descriptions
/camera/motion_module/parameter_updates
/camera/realsense2_camera_manager/bond
/camera/rgb_camera/auto_exposure_roi/parameter_descriptions
/camera/rgb_camera/auto_exposure_roi/parameter_updates
/camera/rgb_camera/parameter_descriptions
/camera/rgb_camera/parameter_updates
/camera/stereo_module/auto_exposure_roi/parameter_descriptions
/camera/stereo_module/auto_exposure_roi/parameter_updates
/camera/stereo_module/parameter_descriptions
/camera/stereo_module/parameter_updates
/diagnostics
/rosout
/rosout_agg
/tf
/tf_static

**Comment by MartyG-RealSense** [comment]
Hi @GitZzw  Are you using the **rs_camera** roslaunch instruction please?

**roslaunch realsense2_camera rs_camera.launch**

With the above instruction, some topics may be missing from the rostopic list because the IMU and infrared topics are disabled by default from ROS wrapper **2.2.15** onwards.  You can enable those by adding the commands below to the end of the roslaunch instruction:

**enable_gyro:=true enable_accel:=true enable_infra1:=true enable_infra2:=true**

**Comment by GitZzw** [comment]
I tryed:
roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true enable_infra1:=true enable_infra2:=true
and I got 
"IMU Calibration is not available, default intrinsic and extrinsic will be used."
"control_transfer returned error, index: 768, error: No data available, number: 61"
The log:
[screen.log](https://github.com/IntelRealSense/realsense-ros/files/5861740/screen.log)

**Comment by MartyG-RealSense** [comment]
If you have a D435 (not a D435i with an IMU) then leave out the enable_gyro and enable_accel commands from the roslaunch statement, as there is no IMU component in the camera to access.  I do apologize.

In your log you have multiple **control_transfer returned error, index: 768, error: No data available, number: 61** warnings after launch.  If this error is continuously generating then it can indicate a serious communication problem with the device.

The next test step that I would recommend is to add an instruction to the end of your roslaunch statement to reset the camera at launch and see whether that improves performance:

**initial_reset:=true**

**Comment by GitZzw** [comment]
Thank you for your patience, so D435 camera do not contain an IMU component?
And I have tried all the advised command in https://github.com/IntelRealSense/realsense-ros/issues/1271, but still have multiple control_transfer returned error.

**Comment by MartyG-RealSense** [comment]
That is correct, the D435 model does not have an IMU component inside it.  The D435i model does.

Please add the commands below to your roslaunch instruction to set the depth and color FPS speed to '15' to test whether using 15 FPS instead of 30 reduces the control_transfer returned warnings:

**depth_fps:=15 color_fps:=15**
