### ISSUE TITLE
I want to get the distance from the depth image

### ISSUE THREAD

**Issue by Hiroaki-K4** [realsenseai/realsense-ros#1654]
Hi.
I was able to get a depth image (16UC1) using realsense-ros. I want to get the distance (meter) of a pixel in this image. For example, if I want to get the distance (meter) at a location (x, y) = (320, 320) in a depth image, can I find it by multiplying the pixel value at that location by the realsense depth_scale (0.0010000000474974513)?
Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Hiroaki-K4    Yes, multiplying the 16-bit depth value by the **depth unit scale** provides the distance in meters.   As indicated by your depth_scale value, the default depth unit scale of the 400 Series cameras is **0.001** (meters).  

If your program is not going to be changing the depth scale then you can simplify the program by just multiplying by 0.001 instead of using an instruction to retrieve the depth scale value in real-time, since the depth scale does not change unless deliberately modified.

**Comment by Hiroaki-K4** [comment]
ok. I understood. Thank you!
