### ISSUE TITLE
Non-linearity in depth measurements

### ISSUE THREAD

**Issue by Omega-Phone** [realsenseai/realsense-ros#1733]
Hello, 
I'm working with D435 camera for an AGV. In order to navigate in the environnement, i'm trying to perform a ground removal based on RANSAC algorithm. 
However, I am not able to fit a plane to the true ground since there is a non-linearity in the depth measurements.  
To illustrate the problem, here are some screenshots: 
![realSenseViewer1](https://user-images.githubusercontent.com/58468629/109674644-602fc480-7b77-11eb-9cd2-219c748d6762.PNG)
![octave1](https://user-images.githubusercontent.com/58468629/109674541-4b533100-7b77-11eb-85db-6d6e132584be.PNG)

The 2 pictures above are displaying the same thing: it is just a room with a clear ground and a desk at the complete right. The first one is taken from real sense viewer, while the second is a plot of a numpy array in octave. From here, everything seems ok.

But the 2 same pictures from left profile are different: 
![realSenseViewer2](https://user-images.githubusercontent.com/58468629/109675209-ddf3d000-7b77-11eb-8abf-a88f2f1b79be.PNG)
![octave2](https://user-images.githubusercontent.com/58468629/109676093-a9ccdf00-7b78-11eb-86f5-cf78ca8136ad.PNG)

Since the ground in realsense viewer appears to be completely plane, the ground plotted in octave is more following a quadratic function, which make hard to determine ground plane.
Maybe this is a normal behavior since the error depends on z², but I would like to know if there is a way to correct the measurements with calibration or something else. 

I hope I've been clear enough, thanks in advance.

**Comment by MartyG-RealSense** [comment]
Hi @Omega-Phone  Although this case is posted on the RealSense ROS forum, it looks as though it is a **librealsense SDK** case.  Is that correct, please?

I could find very few references about using octave with RealSense, so it is difficult for me to advise about that approach to ground segmentation with RANSAC.  

If you are using librealsense, the SDK makes use of the plane-fit algorithm in the link below, which it has integrated into the SDK's **Depth Quality Tool** as a validated approach to implementing plane-fit.  

http://www.ilikebigbits.com/2015_03_04_plane_from_points.html

More information about this can be found in the links below:

https://github.com/IntelRealSense/librealsense/issues/4440 

https://github.com/IntelRealSense/librealsense/issues/3866 

Though the algorithm is implemented as C++ in the Depth Quality Tool, a RealSense team member has stated that the algorithm can be re-written for Python.

https://github.com/IntelRealSense/librealsense/issues/3866#issuecomment-487520955

A different, simpler approach that could be considered is to set up a **depth clamp** that defines a minimum and maximum depth distance, so that depth data with values outside of that range is excluded from the image.  If, for example, a minimum depth distance of 0.5 meters was set then the camera would exclude depth data under 0.5 meters, such as the ground directly in front of the AGV.  This could help to avoid mis-triggering of obstacle detection due to detection of the ground at short range.

You could test this approach in the RealSense Viewer by going to the **Post Processing** section of the Stereo Module options and expanding open the **Threshold Filter**, which enables the setting of a minimum / maximum depth clamp.  You can then change the default minimum value of this option 

![image](https://user-images.githubusercontent.com/41145062/109800404-0a115e80-7c15-11eb-9b3a-0fc9cda1845d.png)

If this approach is satisfactory for you, a threshold filter can be set up with Python scripting.

**Comment by Omega-Phone** [comment]
Hi @MartyG-RealSense, and first of all, thank for your time ! 

Indeed, it's more an issue for **librealrense SDK** than **ROS** forum, could I change it somehow ? 

Actually, Octave is not really the point, and RANSAC algorithm neither. I wrote a RANSAC algorithm in python and it is working as expected in itself.

My issue is that I cannot obtain from python librealsense a ground plane that is effectively a plane. Instead, I have a ground plane that follow a quadratic curve as the one plotted in Octave on the above pictures.

What is actually curious is that the point cloud from Real Sense Viewer give me a nice ground plane as I expect (The 2 other pictures above). However it is strictly the same room.

So I'm asking if you have an idea to explain the different results from librealsense and Real Sense Viewer, and if it exists a configuration or calibration to correct the ground curve in order to obtain a flat ground plane such in Real Sense Viewer or https://github.com/IntelRealSense/librealsense/issues/4440. 

Thanks in advance.

**Comment by MartyG-RealSense** [comment]
It is no problem to continue the current librealsense-related case here.  For future librealsense cases, please post them at the forum linked to below.

https://github.com/IntelRealSense/librealsense/issues

The RealSense Viewer applies a range of configuration presets (such as depth colorization color-scheme) and post-processing filters by default when it is launched.  However, an application that you have created yourself lacks these pre-configured settings, meanng that they have to be deliberately programmed into your scripting in order to be recreated.  The output from a self-created program may therefore have differences to the output of the Viewer.

There are a number of different approaches to ground segmentation with Python, such as using PCL and its SACSegmentation class.

https://github.com/IntelRealSense/librealsense/issues/6338#issuecomment-623278392

A Python point cloud processing library called **pyntcloud** that is compatible with RealSense 400 Series cameras may meet your needs and be relatively straightforward to implement though.

https://github.com/IntelRealSense/librealsense/issues/6989#issuecomment-667570521

**Comment by Omega-Phone** [comment]
In order to add those settings and post-processing filters (I have already add some), is there a way to access the whole configuration of RealSense Viewer ? This way I could be able to reproduce the same configuration in my program. 

Thank you for the link about ground segmentation, I will take a look !

**Comment by MartyG-RealSense** [comment]
You can define settings in the options categories of the **Stereo Module** settings of the RealSense Viewer and then export them from the Viewer as a custom Visual Preset (json) file.  This json can then be loaded into your own program when it launches to apply the configuration settings in the json.  The json export option is near the top of the Viewer's side-panel.

![image](https://user-images.githubusercontent.com/41145062/109973938-ecb1c280-7cf0-11eb-9859-be4468fc70e9.png)

Post-processing filters have to be manually programmed into an application.

The link below has an example of Python code for loading a custom json file.

https://github.com/IntelRealSense/librealsense/issues/6075

![image](https://user-images.githubusercontent.com/41145062/109975465-8f1e7580-7cf2-11eb-9223-b2d6df7dff0f.png)

**Comment by Omega-Phone** [comment]
Update: I found the problem, I was simply missing the fact that there are 2 coordinate systems. I didn't project from pixel to point with rs2_project_point_to_pixel function. 
Thanks again for your time.

**Comment by MartyG-RealSense** [comment]
Excellent news that you found the solution @Omega-Phone  - thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
