### ISSUE TITLE
Plane intersection with a pixel ray

### ISSUE THREAD

**Issue by alex-stonebridge** [realsenseai/realsense-ros#1742]
Hello, I am using this package with D435 and everything is working perfectly. However, I am a bit confused with my task according to the picture below. I have my camera (1) and robot (2), both with their own coordinate frames and I have all TFs between these frames. I have an object (3) with known height (10 cm) which is located on the ground plane (4) with known height (0 cm). From my RGB image I know the central pixel of the objects contour (Pink circle). I need to find the coordinate of the objects center (Orange circle) in robot frame on the ground.
My idea is to assume one more plane (5) which is 1/2 of object height (5 cm) and find the point of intersection between that plane and pixel ray (purple ray). Then, by using TFs and by substracting 5 cm from Z coordinate I could get the desired orange circle coordinates in robot frame.
My question is: how could I find the point of intersection between the pixel ray and the fictional plane (5) with its known height in robot frame? Are there any tools from realsense or ROS? I guess I cannot use rs2_deproject_pixel_to_point function here, because I will get a distance to pink circle instead of the distance to the real center of my object.
![ASDA](https://user-images.githubusercontent.com/75436493/110399917-f895df80-8076-11eb-9e7b-702037d65f80.png)

**Comment by MartyG-RealSense** [comment]
Hi @alex-stonebridge   A simpler way to visualize this problem may be to obtain the **volumetric** measurement values of the box (length, width, height) and then divide all three of those values by 2, and that should provide the center of the box.

![image](https://user-images.githubusercontent.com/41145062/110456445-7b438c80-80c1-11eb-943d-ad6e8a0845b5.png)

The SDK has a Python example program for librealsense called **box_dimensioner_multicam** that can create a volumetric measurement of a box with a single camera, despite its multicam-referencing name.  The box has to be placed upon a 'chessboard' image surface beneath it though.  If you have a large box, you can define a custom chessboard size by editing values in the script.

https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python/examples/box_dimensioner_multicam

**********************

If the problem is more a case of getting the box's real-time position and angle **(pose**) in relation to a camera mounted to a moving robot so that the robot can align to the box, then a ROS-based pose solution for D435 such as the **DOPE** one in the link below may be more appropriate.

https://github.com/avinashsen707/AUBOi5-D435-ROS-DOPE

**Comment by MartyG-RealSense** [comment]
Hi @alex-stonebridge  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
