### ISSUE TITLE
Question: dependencies inside docker

### ISSUE THREAD

**Issue by p0rys** [realsenseai/realsense-ros#1779]
Hey guys,

i have a few short questions. I'm working on a ros docker container that is running multiple realsense nodes. 

**First:**
Right now i'm installing the suggested packages (librealsense2-udev-rules librealsense2-dkms librealsense2 librealsense2-utils librealsense2-dev) via apt from realsense package repo (http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo) AND also "ros-foxy-librealsense2" via rosdep before compiling this repo (branch foxy).

Is this really necessary to install both or is it maybe enough to just install the "ros-foxy-librealsense2" package?  

**Second:**
Do i need the lib and udev rules on the docker host when running the container in privileged mode? Right now, i have none of them installed on the host and most of the time i get only some cameras / nodes working (not always the same ones) but the other ones complaining about not find the device (mapped via serialnumber).

Thanks!

Greetings,
p0rys

**Comment by MartyG-RealSense** [comment]
Hi @p0rys  My knowledge of Docker is limited, but the advice below will hopefully be helpful to you.

1.  To answer this question, may I please first confirm which RealSense ROS2 Foxy wrapper you are using.   Your use of **"ros-foxy-librealsense2** makes me think that you would be installing a now-obsolete Foxy wrapper on the Intel GitHub that is no longer maintained.

https://github.com/intel/ros2_intel_realsense

https://index.ros.org/r/ros2_intel_realsense/#foxy

The current and actively maintained RealSense ROS2 wrapper, which is unrelated to that old wrapper and has support for Dashing, Eloquent and Foxy, is on the **realsense-ros** GitHub.

https://github.com/IntelRealSense/realsense-ros/tree/ros2

If it is your deliberate intention to use that old unsupported wrapper instead of the current one, please let me know.  Thanks!

2.  Comments from RealSense ROS users in the Docker discussion at the link below confirmed that Docker worked for them when Privileged Mode was set to **true** .

https://github.com/IntelRealSense/realsense-ros/issues/1104#issuecomment-594974217

Another Docker-related RealSense ROS case also had success when elevating privileges.

https://github.com/IntelRealSense/realsense-ros/issues/388#issuecomment-410672421

I do not have the knowledge of Docker to confidently offer an answer to your question about whether the lib and udev rules are needed when running in Privileged Mode though unfortunately.

**Comment by p0rys** [comment]
Hi @MartyG-RealSense , really appreciate your help!

1)
I think i just missed "**sudo apt purge ros-$ROS_DISTRO-librealsense2 -y**" from install method 2 which led to the confussion... Is it right that i can't use install method 1 on Ubuntu 20.04 and ROS foxy? Apt does not find the package "**ros-foxy-realsense2-camera**" even with ROS and Intel Realsense sources.

Currently i'm using the "foxy"-branch of this repository. If i understand it correctly, i could also use the "ros2"-branch as it is compatible with dashing, eloquent and foxy, right? 

2)
It seems that all cameras are working out of the box (with docker privileges) without installing something on the host maschine but the connection is not consistent (sometimes it find more cameras, sometimes less [out of four]) . I will read through the mentioned comments and try a few things if it is not getting better. Maybe it is only something with our current setup (host is Ubuntu 18.04 and docker Ubuntu 20.04). I will write a comment if i find a solution (or if it magically works ;D )

**Comment by MartyG-RealSense** [comment]
Hi @p0rys  You are very welcome!

1. The first step of the ROS2 instructions, which comes before choosing Method 1 or 2, recommends using Ubuntu 18.04 with Dashing and Ubuntu 20.04 with Foxy.

https://github.com/IntelRealSense/realsense-ros/tree/ros2#step-1-install-the-ros2-distribution

Since Method 1 in the ROS2 wrapper's installation instructions simply asks for the instruction **sudo apt-get install ros-$ROS_DISTRO-realsense2-camera** to be input without having to define the value of the $ variable first as required in the ROS1 wrapper, I would assume (not certain) that the choice of 18.04 or 20.04 in the preceding step pre-determines the ROS version that is substituted in for $ROS-DISTRO

If you chose to use the older unsupported ROS2 wrapper then you would not be able to use it with more recent RealSense camera models such as D455 and L515, as it would not have the support for these that the current ROS2 wrapper does.

2.  I have a recollection of a RealSense Docker user recommending that the same kernel version be used for both the host and Docker, though that was a personal opinion rather than firm documentation.

**Comment by p0rys** [comment]
Thanks @MartyG-RealSense !

Yes, right now i'm on Ubuntu 20.04 with Foxy. I tried the mentioned command and even **sudo apt-get install ros-foxy-realsense2-camera** directly. It still does not find the package in my apt sources (ubuntu, ROS and Intel-Realsense). 
I do **not** want to use the old wrapper and right now i'm totally fine with cloning this repository (branch ros2) and compile it if there is no deb-package available. I was just not sure if i'm doing something wrong because the install guide recommends installing the deb-package...

For the different kernel versions on host and docker -> i will try a few different combinations when i have a little bit more time and post the results here.

**Comment by eholmes13** [comment]
@p0rys I'm in a similar boat to you, I'm attempting to create a docker container on Ubuntu 18.04 with Dashing. I'm running into the same issue of not finding a ros-dashing-realsense2-camera package in my apt sources, have you made any progress with figuring out the issue?

**Comment by MartyG-RealSense** [comment]
Hi @p0rys  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by p0rys** [comment]
Hey @MartyG-RealSense 

Sorry for the late response. Indeed i tried a few different configurations. It seems that it is enough to install the [librealsense2](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages), this repository (branch ros2) and remove _ros-foxy-librealsense2_ manually to get it to work constantly. It is NOT needed to install anything on the host maschine (maybe it is better, but i did not notice any problems. Even with the different kernel versions on host and guest). 

I think the main problem was that rosdep is automatically installing ros-foxy-librealsense2. After removeing it and installing the version from [here](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages) everything seems fine.

@eholmes13 
Right now i did not find a deb package for this wrapper. It seems that it is not available in ros deb sources. There is nothing I (or we) can do about that. Someone with the needed access rights need to add it. 

For now i just download these repository inside my dockerfile, install all dependencies and compile it manually. If it helps, i can provide you a few code snippts.

**Comment by MartyG-RealSense** [comment]
Thanks very much @p0rys for the confirmation that your Docker setup is working for you if you make manual adjustments to the setup.

**Comment by MartyG-RealSense** [comment]
Hi @p0rys  Do you require further assistance with this case, please?  Thanks!

**Comment by p0rys** [comment]
Hey @MartyG-RealSense As everything seems to run fine now, the issue can be closed.  

@eholmes13 Got the confirmation that the deb packages are missing. They should be available in a few weeks. See: #1814

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update @p0rys - great to hear that your system is successful!
