### ISSUE TITLE
Best and cheapest extended USB 3.0 cable 

### ISSUE THREAD

**Issue by ranjitkathiriya** [realsenseai/realsense-ros#1799]
Hello there,

I need a 3.0 USB to type C cable for my intel real sense D435i. Can you please! suggest some links where I can buy It? I want cable around 10m long.

I am living in Ireland.

**Comment by MartyG-RealSense** [comment]
Hi @ranjitkathiriya   Based on known support for RealSense and past feedback from RealSense users, **Newnex** and **OCP** are worth researching.

Because a high quality cable is important when using a long cable with RealSense cameras, purchasing a cheap cable can be a false economy as it may have performance degradation or no connection at all when transmitting over cable length of 2 meters or more.

For a length of 10 meters, you will likely need an **active repeater** type USB cable with signal-boosting components.

**Newnex**
https://www.newnex.com/realsense-3d-camera-connectivity.php

https://youtube.com/watch?v=GLQgR1jT04M

**OCP**
https://www.ocp.com/news/intel-realsense-d435-and-d415-camera-cables/

**Comment by ranjitkathiriya** [comment]
Thanks for reply @MartyG-RealSense
