### ISSUE TITLE
Realsense D435i  + iRobot Create Gmapping

### ISSUE THREAD

**Issue by cnburke** [realsenseai/realsense-ros#1873]
Hello,

I am attempting to integrate my D435i camera into my project. In short, I have an iRobot Create 2 platform using the AutonomyLabs/create_robot ROS package, and this works swimmingly. 

I then moved on to getting the realsense-ros package up and running on my Jetson nano, and I've got RViz successfully displaying the pointcloud. 

My current issue is in creating a rosbag for use in mapping. I obviously need both odometry data and a laserscan input.

My issue is that the camera_link base frame obviously doesn't have a transform to my create_robot odometry frame, and I've been trying to create one. Thus far, I've tried following the tf2 examples from the ROS wiki, but I'm still pretty new to ROS and haven't had too much to with getting custom transforms working. 

I've also read that odom frames need a direct transform, no "skips", so perhaps that has something to do with it. 

I guess what I'm looking for is if there's a way that I can just take the URDF for the rs_camera.launch file and add a transform that says "hey, I'm a d435i camera, and I'm mounted at (0,3,3) in relation to your create_robot's odom frame" (btw, the odom frame is the root of the tree in the create_robot ROS package).

And just for kicks, if anybody has a good link for combining the robot_description provided with the rs_camera.launch with other robot_descriptions, bonus points. 

Thanks in advanced.

**Comment by MartyG-RealSense** [comment]
Hi @cnburke  Intel's D435i SLAM guide for ROS may be able to provide you with what you are looking for.  It describes how to configure a SLAM system based on **rtabmap_ros** and then record the data to a rosbag with **rosbag record** and play it back.

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

 A RealSense user expanded upon that guide to describe how to retrieve the camera's relative position from the generated map by performing **localization**.  The guide describes that the pose can then be published to ROS.

https://github.com/IntelRealSense/librealsense/issues/8094#issuecomment-753979162

If you need to record to a bag ROS topic data generated by devices other than the D435i then adding the **-all** term to the rosbag record command in order to record all topics that are currently publishing may help you to achieve that.

http://wiki.ros.org/rosbag/Commandline#rosbag_record

**Comment by MartyG-RealSense** [comment]
Hi @cnburke  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
