### ISSUE TITLE
How to get the camera head temperature

### ISSUE THREAD

**Issue by ranjitkathiriya** [realsenseai/realsense-ros#1923]
Hello there,

Can you please! help me with what is this camera head temperature, where it can be used, and How I can get this value in ROS noetic. I am using an realsense D435i.

Thanks in advance for the help!

**Comment by MartyG-RealSense** [comment]
Hi @ranjitkathiriya   I am not familiar with the term 'camera head temperature'.  The librealsense SDK supports 8 temperature options - 7 of which are detailed in the link below, and an 8th relating to D415 humidity that was added in SDK 2.40.0.

https://support.intelrealsense.com/hc/en-us/community/posts/360043579994-D415-Temperature

If you are seeking to access the general internal temperature of the camera in the ROS wrapper instead of through librealsense, the **ASIC** temperature would likely be the most appropriate option.  The ASIC, projector and motion module temperature readings should be published in the ROS wrapper under the **/diagnostics** topic.
