### ISSUE TITLE
pointcloud filter

### ISSUE THREAD

**Issue by THLL245** [realsenseai/realsense-ros#1954]
D435I - Jetson Nano - ROS Melodic

When running 

roslaunch realsense2_camera rs_camera.launch

Immediately get control_transfer returned error, index 768, error: No data available, number: 61

When using RVIZ  topic /camera/depth/image_rect_raw has data and great frame rate

When I try and add the Color Image Topic /camera/color/image_raw  I get the following error

Error updating depth cloud: Depth image resolution (840x480) does not match color image resolution (1280 x 720)

new error now  control_transfer returned error, index 768, error: No data available, number: 11

Now really I would like to use this camera for its pointcloud but when doing

roslaunch reaslsense2_camera rs_camera.launch filter:=pointcloud 

The topic /camera/depth/color/points doesn't even publish anything

I am not sure if these problems are related to each other but pointcloud doesnt work

**Comment by MartyG-RealSense** [comment]
Hi @THLL245   If the **control_transfer returned** warning only generates a small number of times at launch and then stops, or appears once or twice a minute after launch, then it can be safely ignored.  If it is generating continuously though then it can indicate that there is a serious communication problem with the device.  I note though that the topics are being published successfully in your particular case.

Regarding your problem with rendering the pointcloud in RViz: do you have 'Fixed Frame' set to **camera_link** like in the ROS wrapper's pointcloud example, please?

https://github.com/IntelRealSense/realsense-ros#point-cloud

![image](https://user-images.githubusercontent.com/41145062/123624340-59a01980-d806-11eb-9061-b67144f07990.png)

Also, can you confirm please that you are using **filters:=** instead of filter:=

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud**

**Comment by THLL245** [comment]
Yes fixed frame is camera_link and control_transfer error:61 is constant about once every 3 secs but this is only when subscribed to topic /camera/depth/image_rect_raw when subscribed to /camera/color/image_raw it changes to transfer error: 11 and that is about once a sec and unable to show because of different resolutions.

**Comment by MartyG-RealSense** [comment]
Regarding the error that you received:

**Error updating depth cloud: Depth image resolution (840x480) does not match color image resolution (1280 x 720)**

I have not seen that particular ROS error before.  I will tag @doronhi the RealSense ROS wrapper developer to seek their input.

Hi @doronhi  Do you know what might cause the above error and prevent the pointcloud from being published in RViz please?

**Comment by MartyG-RealSense** [comment]
H @THLL245  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
