### ISSUE TITLE
How to convert 2D coordinates to 3D coordinates ? 

### ISSUE THREAD

**Issue by gusrbgks** [realsenseai/realsense-ros#1973]
Hi, I got images with ros-realsense camera and did object detection using ros-yolo.

The camera is using the L515 model.

I want to convert the center point (2D coordinate) of the bbox detected by yolo to a 3D coordinate that also contains the z value.

I'm trying to convert 2D coordinates to 3D by subscribing to ros-yolo's message from ros-realsense.

How can I get the 3D coordinate values?

**Comment by MartyG-RealSense** [comment]
Hi @gusrbgks  Are you using **darknet_ros** please?

https://github.com/leggedrobotics/darknet_ros

If you are, then darknet_ros has a RealSense-compatible 3D module called **darknet_ros_3d**, though it requires ROS2.

It can be launched after darknet_ros to obtain 3D bounding boxes.  darknet_ros_3d then calculates and outputs the z-distance to the nearest and furthest pixel of the 3D bounding box (zmin and zmax).

https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d

**Comment by gusrbgks** [comment]
Hi MartyG-RealSense.

I tried darknet_ros_3d but I am using ros1. 

So it doesn't build.

**Comment by MartyG-RealSense** [comment]
Can you provide me with a link to the ROS YOLO system that you are using please?

**Comment by gusrbgks** [comment]
Here is a link to the Yolo system I'm using.

https://github.com/leggedrobotics/darknet_ros

**Comment by gusrbgks** [comment]
I found the ROS1 melodic version!
I am building darknet_ros_3d using melodic brunch.
Can I use this darknet_ros_3d package to get the 3D point(x,y,z) value of the pixel(2D x,y)?

**Comment by MartyG-RealSense** [comment]
Yes, darknet_ros_3d has a Melodic branch (link provided below for future readers of this case).

https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d/tree/melodic

darknet_ros_3d seems to return values based on particular regions of the 3D bounding box rather than for a specific xy pixel coordinate.

There was a RealSense ROS user who created a Python script that subscribed to **darknet_ros** and who was trying to find the Z distance for an XY that they already knew.

https://github.com/IntelRealSense/realsense-ros/issues/1574#issuecomment-747442213

![image](https://user-images.githubusercontent.com/41145062/125443375-7d59c137-4114-4cda-a94c-942b205c1398.png)

**Comment by MartyG-RealSense** [comment]
Hi @gusrbgks  Do you require further assistance with this case, please?  Thanks!

**Comment by gusrbgks** [comment]
Hi.
I seem to have found a way to get 3D points from the Darknet_3D package.
Thank you.

**Comment by MartyG-RealSense** [comment]
That's excellent news @gusrbgks that you achieved a solution.  Is it okay to close this case now or do you require assistance with something else, please?  Thanks!
