### ISSUE TITLE
How to convert the 2D coordinates of Mask-rcnn to the 3D coordinates of the mask  

### ISSUE THREAD

**Issue by Lai-dongdong** [realsenseai/realsense-ros#1974]
My device is L515, and I have got a 2D mask. How do I map the 2D mask to the point cloud?

**Comment by MartyG-RealSense** [comment]
Hi @Lai-dongdong  If you are aiming to produce a lidar point cloud and then filter it with Mask-RCNN then the **LDLS ROS** package may fit your needs if your point-cloud input data is from a bag file rather than live camera data.  It was designed with a Velodyne lidar camera in mind rather than the RealSense L515 though.

https://github.com/brian-h-wang/ldls_ros

**Comment by MartyG-RealSense** [comment]
Hi @Lai-dongdong  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
