### ISSUE TITLE
rqt reconfigure crashes on filter configuration tab

### ISSUE THREAD

**Issue by daniele-gusmini** [realsenseai/realsense-ros#1998]
With decimation filter active, on selection of decimation tab in dynamic reconfigure rqt crashes, reporting:

Floating point exception (core dumped)

**Comment by MartyG-RealSense** [comment]
Hi @daniele-gusmini   Are you able to set the decimation filter's magnitude with a **rosrun dynamic_reconfigure** command after the roslaunch instruction instead of using the decimation option on the dynamic_reconfigure GUI, please?

**rosrun dynamic_reconfigure dynparam set camera/decimation 'filter_magnitude' 8**

![image](https://user-images.githubusercontent.com/41145062/127033194-55ca081f-984a-4a15-a6a4-3e604c909db0.png)

If you would prefer to solve the issue with the GUI crash, there was a similar problem in 2019 in the case linked to below that was diagnosed to be caused if the kernel was unpatched.

https://github.com/IntelRealSense/realsense-ros/issues/607

**Comment by MartyG-RealSense** [comment]
Hi @daniele-gusmini  Do you require further assistance with this case, please?  Thanks!

**Comment by daniele-gusmini** [comment]
Hi @MartyG-RealSense, thanks for the help! Your method works, I found also an alternative setting up the parameter in the launch file as:

`<rosparam>
      /camera/decimation/filter_magnitude: 2
</rosparam>`

The GUI crash probably is due to the unpatched kernel as you said

Thank you for the help!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @daniele-gusmini - it's excellent news that you were successful.  Thanks for the update and for sharing your method with the RealSense ROS community!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
