### ISSUE TITLE
Uptime for l515 and d435i

### ISSUE THREAD

**Issue by aditdoshi333** [realsenseai/realsense-ros#2024]
Hello,

I wanted to know for much time I can run l515 and d435i with ros? For example, can I run 2 hrs without any break?

**Comment by MartyG-RealSense** [comment]
Hi @aditdoshi333  Though I do not have long-run test times for L515, the 400 Series cameras can run indefinitely so long as they remain within the recommended temperature range.  If a problem does occur during a long run, it is more likely to be due to non-camera reasons such as a glitch in the USB cable, the computer hardware (such as the USB port) or the computer's operating system.

In situations where a problem does arise, the outer maximum of a long-run session with the 400 Series cameras is typically around three days.

**Comment by MartyG-RealSense** [comment]
Hi @aditdoshi333  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
