### ISSUE TITLE
Auto exposure goes too low and freezes

### ISSUE THREAD

**Issue by fiorano10** [realsenseai/realsense-ros#2026]
We have 4 cameras connected to the motherboard, each has its own USB 3.1 Gen 1 port. Running the following config
Ubuntu 18.04
ROS Melodic
Librealsense v2.42
realsense-ros v2.2.22
Camera fw: 5.12.11
Auto exposure ROI: bottom 2/3 of the image
Camera : D435i

After launching the camera, it suddenly drops the exposure after a few minutes but never recovers, until the node is restarted.

dropped exposure in Orange
![Screenshot from 2021-08-07 14-44-22](https://user-images.githubusercontent.com/10829017/128613519-50dcdd8c-0b06-4bbc-ae9d-fc230608d314.png)

Before the exposure drop
![Screenshot from 2021-08-07 16-50-43](https://user-images.githubusercontent.com/10829017/128613579-c1ef2e70-2c31-49bd-9638-fca29b84d724.png)

After the exposure drop
![Screenshot from 2021-08-07 14-44-45](https://user-images.githubusercontent.com/10829017/128613560-0a0c48c3-56c9-40d3-a63b-f490a15057b3.png)

**Comment by MartyG-RealSense** [comment]
Hi @fiorano10  Which model of RealSense camera are you using, please?

There have been past cases of this effect of an exposure drop to minimum level that may require a camera reset or a covering over of the camera lenses with the hand to correct the image.  

https://github.com/IntelRealSense/librealsense/issues/4928
https://support.intelrealsense.com/hc/en-us/community/posts/360033445713-D435-Sunlight-saturation-problem

As a starting point in this investigation: if the effect occurs predictably and repeatedly after a few minutes, would it be possible to touch the outer casings of the cameras a few minutes after they have been enabled and see whether they are hot to the touch?  This could indicate that the problem is related to the camera being overheated due to bad USB cables or a glitch on the USB ports of the computer.  The computer is more likely as a cause, as all 4 cameras are unlikely to have bad USB cables.  There has also been a past case with a single-board computer where a power component on the board was causing camera overheating.

If you subscribe to the **/diagnostics** topic of the RealSense ROS wrapper then you can obtain the camera's internal ASIC and Projector temperature readings.

**Comment by fiorano10** [comment]
Wer're using D435i x 4, `/diagnostics_agg` says OK for all cameras. It is just one camera, and is fixed after blocking the view for a short period. Any way to do it without resetting the camera?

**Comment by MartyG-RealSense** [comment]
You could try disabling and then re-enabling auto-exposure during runtime with a rosrun instruction.

https://github.com/IntelRealSense/realsense-ros/issues/1472#issuecomment-785887174

**Comment by MartyG-RealSense** [comment]
Hi @fiorano10  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
