### ISSUE TITLE
Process died after nodelet bond is broken when playing back from the rosbag file

### ISSUE THREAD

**Issue by victorll998** [realsenseai/realsense-ros#2034]
Hi there, 

I have some troubles to playback from d455 rosbag files. I have two rosbag files that are recorded via SDK-pipeline. When I use ```rs_from_file.launch``` to playback these two rosbag files, it runs for a while and then one of them immediately dies. The error messages are like below. I have checked the rosbag files and they can be loaded by viewer to playback without any issue. I have spent a lot of time on it but have no progress so far.  If you have any idea about it, please let me know. Thank you.

I am using SDK 2.42.0 with ros_realsense 2.2.22 because of the issue that pointclouds cannot be reproduced from rosbag files.

```
[0m[ INFO] [1628666870.750791556]: Loading nodelet /d455_right/realsense2_camera of type realsense2_camera/RealSenseNodeFactory to manager realsense2_camera_manager with the following remappings:[0m
[0m[ INFO] [1628666870.758373198]: waitForService: Service [/d455_right/realsense2_camera_manager/load_nodelet] has not been advertised, waiting...[0m
[0m[ INFO] [1628666870.817947786]: waitForService: Service [/d455_right/realsense2_camera_manager/load_nodelet] is now available.[0m
[0m[ INFO] [1628666884.916157735]: Bond broken, exiting[0m
```

```
[ INFO] [1628666871.087854749]: RealSense Node Is Up!
[ WARN] [1628666871.092438705]: 
 11/08 17:27:51,092 WARNING [140254862771968] (playback_device.cpp:198) Playback device does not provide a matcher
 11/08 17:27:51,104 WARNING [140628998465280] (playback_device.cpp:198) Playback device does not provide a matcher
 11/08 17:27:51,249 WARNING [140254871164672] (playback_device.cpp:198) Playback device does not provide a matcher
[ INFO] [1628666871.362419444]: publishing unordered pointcloud.
[ INFO] [1628666871.385708674]: publishing unordered pointcloud.
[ WARN] [1628666875.870695329]: This node/nodelet subscribes topics only when subscribed.
[ WARN] [1628666875.889029219]: This node/nodelet subscribes topics only when subscribed.
[d455_right/realsense2_camera_manager-7] process has died [pid 18170, exit code -11, cmd /opt/ros/noetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/victor/.ros/log/a203a610-fa75-11eb-b5de-29e72f2bfe71/d455_right-realsense2_camera_manager-7.log].
log file: /home/victor/.ros/log/a203a610-fa75-11eb-b5de-29e72f2bfe71/d455_right-realsense2_camera_manager-7*.log

```

**Comment by MartyG-RealSense** [comment]
Hi @victorll998   In a past case (in librealsense rather than the ROS wrapper), a RealSense team member advises that the warning **(playback_device.cpp:198) Playback device does not provide a matcher** may occur if frame drops occur in the bag file because several stream types have been recorded into the bag and a high resolution was used for the streams.

https://github.com/IntelRealSense/librealsense/issues/3121#issuecomment-470527146
https://github.com/IntelRealSense/librealsense/issues/3121#issuecomment-487333025

This is similar to the advice about frame drops provided by **Doronhi** in your previous case https://github.com/IntelRealSense/realsense-ros/issues/1826 that featured this warning,

The latest librealsense SDK **2.49.0** that is now available includes a 3D rendering fix for rosbags, though I do not know if this will help with your particular problem once a ROS wrapper version that can be matched with librealsense 2.49.0 is available.

https://github.com/IntelRealSense/librealsense/pull/9300

**Comment by MartyG-RealSense** [comment]
Hi @victorll998  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
