### ISSUE TITLE
Can d455 and d435i work together?

### ISSUE THREAD

**Issue by rahulsharma11** [realsenseai/realsense-ros#2049]
Hi, I have 2 d435i cameras working together for mapping.
Currently due to color FOV limitations, i wanted to use 1 d455 camera with 1 d435i camera.

I just wanted to know can i use d435i + d455 camera together for point cloud generation and mapping?
And external HW sync process is same for this pair ? as in 2 d435i.

Can there be any other challenges i may experience?

Thanks.

**Comment by MartyG-RealSense** [comment]
Hi @rahulsharma11  It is recommendable that the same type of camera is used in a multiple camera setup due to hardware differences between models, such as different FOV sizes and sensor shutter types.  Those hardware variations would be the main challenge that you may face, as there may be differences in the images that are output from the D435i and D455 models.

For example, the D455 has a fast global shutter on both its depth and RGB sensors, whilst the D435i has a slower rolling shutter on its RGB sensor and global shutter on depth sensors.

You can mix camera types together if you wish to do so though.  For what you have in mind, Intel's ROS tutorial for stitching together point clouds from more than one camera into a single combined point cloud may suit your requirements.  There are two versions of this guide.

**Two cameras attached to the same computer**
https://github.com/IntelRealSense/realsense-ros/wiki/Showcase-of-using-2-cameras

**Three cameras on two computers**
https://github.com/IntelRealSense/realsense-ros/wiki/showcase-of-using-3-cameras-in-2-machines

The hardware sync process should be the same for D435i and D455, yes, though again it would not be recommendable to mix camera models in a hardware sync setup.  Hardware sync would not be required for the multiple camera guides in the links above though.

**Comment by rahulsharma11** [comment]
Thanks for the pointers.
