### ISSUE TITLE
SLAM with D435i tutorial: Pointcloud not dense

### ISSUE THREAD

**Issue by naoya-kumagai** [realsenseai/realsense-ros#2070]
I am following the SLAM tutorial. 
The pointcloud map generated by 

    rosrun pcl_ros pointcloud_to_pcd input:=/rtabmap/cloud_map
is not dense. What could be a fix for this? 

![image](https://user-images.githubusercontent.com/75962438/132582832-a5a08e10-b1ab-4abd-860c-b8f8bbb219ad.png)

**Comment by MartyG-RealSense** [comment]
Hi @naoya-kumagai   I can see color shading in the points, which suggests to me that the color image is being mapped to the point cloud like it should be in the D435i SLAM guide.

As a starting point, you could confirm that the pointcloud is set as unordered (is_dense = true) by including the command **ordered_pc:=false** in your roslaunch instruction.  The point cloud should be unordered by default anyway but it is worth checking to confirm that an ordered point cloud is not being caused by something in the project.

**Comment by naoya-kumagai** [comment]
This doesn't seem to make a difference...

**Comment by MartyG-RealSense** [comment]
Let's check through the guide steps again.  Can you confirm please that you have realsense2_camera, imu_filter_madgwick, rtabmap_ros and robot_localization installed, as described in https://github.com/IntelRealSense/realsense-ros/issues/2067#issuecomment-915452219 

Does your **Frames** list match the one in the guide, with only 'camera_link' and 'map' ticked?

![image](https://user-images.githubusercontent.com/41145062/132640625-5f4c39b0-cdd1-48f0-80ab-0ff1f9ce36b1.png)

And is **Image Topic** set to /camera/color/image/raw ?

**Comment by MartyG-RealSense** [comment]
Hi @naoya-kumagai  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
