### ISSUE TITLE
D455 pointcloud with direct light

### ISSUE THREAD

**Issue by abylikhsanov** [realsenseai/realsense-ros#2083]
Hi,

I am using D455 and standard launch file that enables the pointcloud (in particular, I use `rs_aligned_depth.launch` with `enable_pointcloud `set to `true`). The camera is tilted at 40 degrees to the ceiling and sometimes, it catches a direct light from the ceiling above and it causes a lot of ghost obstacles from it.

Is there a way to handle such scenario?

**Comment by MartyG-RealSense** [comment]
Hi @abylikhsanov  I would recommend a maximum tilt of 30 degrees if possible.  You can exceed this angle but there may be unpredictable effects in the image.  

In this case though, if the ghost obstacles occur when exposed to a strong light source then it is more likely to be due to the infrared sensor of the camera becoming saturated with light when directly observing the light source.  

If auto-exposure is enabled then removal of the presence of the disruptive light source, facing the camera away from the light-source or covering the camera lenses for a few seconds can enable the auto-exposure to automatically correct the image.

If tilting the camera 40 degrees towards where the light source is located is unavoidable then the negative effects of light glare on the camera image can be significantly reduced by applying a physical optical filter product called a **linear polarization filter** over the lenses on the outside of the camera.   Section **4.4  When to use polarizers and waveplates** of Intel's white-paper document about optical filters provides more information about this subject.

https://dev.intelrealsense.com/docs/optical-filters-for-intel-realsense-depth-cameras-d400#section-4-the-use-of-optical-filters

The image below, taken from Section 4.4, demonstrates the before and after difference that a linear polarization filter can make.

![image](https://user-images.githubusercontent.com/41145062/134125190-f529c66e-d908-4997-805f-c15ca479e200.png)

Another approach to dealing with facing a strong light source can be to set a **Region of Interest (ROI)** in the lower half of the image, as described in the guidelines in Intel's camera tuning paper for using a 400 Series camera in strong light.

https://dev.intelrealsense.com/docs/tuning-depth-cameras-for-best-performance#section-use-sunlight-but-avoid-glare

**Comment by MartyG-RealSense** [comment]
Hi @abylikhsanov  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
