### ISSUE TITLE
How do I time synchronize multiple L515s?

### ISSUE THREAD

**Issue by jieunko** [realsenseai/realsense-ros#2105]
I have been following multi L515 setup whitepaper 
https://dev.intelrealsense.com/docs/lidar-camera-l515-multi-camera-setup
It removed interference of the depth images between two l515 cam.
However there is time difference between the images which should not expected.
Any suggestion would be helpful. Thank you

**Comment by MartyG-RealSense** [comment]
Hi @jieunko  First, may I confirm which depth resolution you are using for the two cameras, which are presumably simultaneously active.  The white paper recommends 2 simultaneous cameras if using 1024x720 (XGA resolution) or up to 3 simultaneous cameras if using 640x480 (VGA resolution).  

![image](https://user-images.githubusercontent.com/41145062/136416690-b2c28585-0389-4165-bacd-3502fca698aa.png)

The paper describes that capture of a pair of cameras follows the process below when Python is used to control the cameras.

1.  Disable all cameras by setting the GPIO status to **Out** for each camera.  In this case, we only have 2 cameras to disable, '0' and '1'.

![image](https://user-images.githubusercontent.com/41145062/136417842-8706f842-4d79-4e9f-91f0-779aadd8ba50.png)

2.  Set the two cameras '0' and '1' to be active **(high**), followed by a sleep period and then set the two cameras to be inactive **low)**.

![image](https://user-images.githubusercontent.com/41145062/136418965-7a4c20f6-153b-4447-8b66-d1633033f3a4.png)

Example Python code, which could be trimmed down for 2 cameras instead of the paper's 8 (cameras 0-7), is provided in the appendix of the white paper.

https://dev.intelrealsense.com/docs/lidar-camera-l515-multi-camera-setup#section-appendix

Are you controlling the on-off status of 2 cameras simultaneously with Python scripting using the method above, please?  Or are you using a different method such as ROS to define L515 multi-camera capture (as this question is posted on the RealSense ROS forum rather than the main librealsense forum at https://github.com/IntelRealSense/librealsense/issues/ ).

**Comment by jieunko** [comment]
Hello! @MartyG-RealSense
My depth resolution is both 640x480 I was testing with realsense-viewer with inter cam sync mode enabled.
Oh then should  post this question to librealsense forum. Thank you again.
For 1. 2 with those the interference has not removed
So my code goes like  
GPIO.output(Camera0, GPIO.HIGH)
GPIO.output(Camera0, GPIO.LOW)
time.sleep(0.16)
GPIO.output(Camera0, GPIO.LOW)
GPIO.output(Camera1, GPIO.HIGH)
I think this is the main reason I am getting the time difference then interference issue still remains..  
By the way does realsense-ros wrapper work with L515 inter_cam_sync mode?

**Comment by MartyG-RealSense** [comment]
It's fine to continue the case on this forum.  :)

You can set Inter Cam Sync Mode in ROS, though just to the extent of setting the mode value rather than setting the GPIO to Out, High or Low as the Python script does.  An L515 user in https://github.com/IntelRealSense/realsense-ros/issues/1540#issuecomment-738027312 took the approach of setting the Inter Cam Sync Mode value in ROS by loading a **json** camera configuration file as part of their launch process.

The mode is also settable in ROS1 (Kinetic, Melodic or Noetic) as a **dynamic_reconfigure** parameter during runtime after launch, as described in https://github.com/IntelRealSense/realsense-ros/issues/984#issuecomment-707729244

**Comment by jieunko** [comment]
So it seems like time sync two camera and removing interference is quite impossible..
 Thank you for your help!!

**Comment by jieunko** [comment]
Hi @MartyG-RealSense
Does /camera/stereo_module type nodes available for L515s? or is it justed opened for streo cameras?

**Comment by MartyG-RealSense** [comment]
A list for the L515 is provided in the link below.

https://dev.intelrealsense.com/docs/ros-wrapper#section-l-500-lidar-depth-cameras

**Comment by MartyG-RealSense** [comment]
Hi @jieunko  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
