### ISSUE TITLE
How to publish depth frame

### ISSUE THREAD

**Issue by hyebin-rdv** [realsenseai/realsense-ros#2116]
My subscription side code is as follows.

> front_depth_image_topic = "Front_camera/depth/image_rect_raw"
> rospy.Subscriber(front_depth_image_topic, Image, front_depth_image_callback)
> 
> def front_depth_image_callback(msg):
>         depth_img = np.frombuffer(msg.data, dtype = np.uint16).reshape(msg.height, msg.width, -1)
> ...

I'm going to publish the depth frame according to that form.
`frames = pipeline.wait_for_frames()
 depth_frame = frames.get_depth_frame()
depth_image = np.asanyarray(depth_frame.get_data())`

Can I publish 'depth_frame' or depth_image right away? Which one should I publish?

**Comment by MartyG-RealSense** [comment]
Hi @hyebin-rdv  If you are asking whether you need to 'wait for frames' then you can receive frames immediately by using **poll_for_frames()** instead.  With wait_for_frames, it blocks until a complete frame is received.  Using poll_for_frames can have greater complexity though, as when using this instruction you should control when the CPU is put to sleep and for how long, otherwise you could end up maxing out the CPU at 100% usage.

In regard to what to publish: if this were a pure librealsense script (as I am not as familiar with accessing librealsense scripting from ROS) then I would say depth_image, as it is the end-result of the frame setup.  Typically in librealsense scripts, storing the frame in a numpy array is the step that comes shortly before displaying it using a method such as an OpenCV draw call such as **cv2.imshow**.  A simple example of this structure is provided by the SDK's **read_bag_example.py** example script in the link below.

https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/read_bag_example.py#L69-L72
