### ISSUE TITLE
Improve USB 2.1 functionality to enable stereo

### ISSUE THREAD

**Issue by matthewoots** [realsenseai/realsense-ros#2125]
Using a Raspberry Pi clone without USB3 is quite a pain, since all is working well until you reach the point where no /camera/infra2 is found, apparently the sensor stream is not available

Is there any way to enable the stream of **infrared 2** on USB2

Or is there a way to bypass the USB3 check? I do think you can change it only inside the main repo and not in this wrapper.

Thanks in advance!

**Comment by MartyG-RealSense** [comment]
Hi @matthewoots  You are correct.  The Infrared 2 stream is not supported on USB2, and is only available on USB3.  RealSense cameras have more limited capabilities on USB2, as described in the Intel article linked to below.

https://www.intelrealsense.com/usb2-support-for-intel-realsense-technology/

I have not previously seen any example of modifying the profiles supported under USB2, though I would speculate that if it were possible to do so then the librealsense SDK file **unit-tests-live.cpp** would be a good place to start looking as it contains numerous USB2-specific stream profile definitions.  You can highlight these in the file script (linked to below) by doing a page find operation in the browser window for the term **usb2** so that you can quickly browse through all USB2 references in the script.

https://github.com/IntelRealSense/librealsense/blob/master/unit-tests/unit-tests-live.cpp

I note in the title of this issue that you mention wanting to enable stereo.  If you are referring to stereo **depth**, the **Infrared2** stream is not related to stereo depth frame generation.  The camera hardware produces depth frames at the point of capture from the raw left and right infrared frames and then sends those frames along the USB cable to the computer / computing device.  Having the Infrared2 **stream profile** unavailable in the RealSense SDK software has no effect on the ability of the camera hardware to generate depth frames. 

Where it would be a problem is if you were aiming to stream both left and right **infrared** frames.

**Comment by matthewoots** [comment]
Hi @MartyG-RealSense thank you for the detailed explanation, and really taking the time to help to run through the deeds. And yeah this is a question or if possible a feature request of sorts.

My focus is to enable 435i infrared 1 and 2 stream on USB2 that's the objective since smaller SoC boards would only have USB2 and not USB3. Funny how depth can be processed and published and yet `infrared2` stream cannot be a form of output. 

Sorry for asking this, but I'm not too sure how changing the `unit-tests-live.cpp` will affect the 435i when I'm going to use the wrapper, or does it flash the parameters and settings onto the device. Am I suppose to use `Realsense Viewer` to observe and invoke the change? I've managed to build the `librealsense` repo on another system but I'm thinking of how to change the device settings on the hardware so that the RS ROS wrapper on the other machine would be able to use it, since I saw that the `rs2::device _dev` receives the parameters from the device, or is this how the device works?

**Comment by MartyG-RealSense** [comment]
The Infrared2 stream is disabled when the camera is being detected as being on a USB2 connection in order to reduce USB bandwidth, since a USB2 connection is slower than USB3.  

The left and right infrared frames that a depth frame is generated from are **raw** frames that are not usually accessible to the end-user.   The Infrared and Infrared 2 streams that are accessible from programs such as the Viewer are different from the raw infrared frames, as they have undergone a process called **rectification** in the camera hardware to apply a distortion model to them.  More information about distortion models can be found in the documentation link below.

https://dev.intelrealsense.com/docs/projection-in-intel-realsense-sdk-20#section-distortion-models

In the majority of cases, using Infrared 2 is likely to be useful just for the sake of looking at it because you can do so, rather than applying it to a useful application.  This is because the image from Infrared 2 will be almost the same as Infrared except for a small horizontal offset due to the different physical positions of the left and right infrared sensors on the horizontal plane.

My understanding is that it is the computer's USB controller hardware that determines whether a USB connection is USB 2 or USB 3, and then librealsense uses that status to make decisions about what configurations will be accessible on the camera.  

The USB controller in turn may make the identification based on the hardware that is being connected to it.  For example, if a device is compatible with USB3 but it is connected to a USB2 port or is plugged into a USB3 port but is using a USB2 cable (which lacks internal wires that enable it to perform as USB3) then the device may operate as USB2.

Would it be possible for your project to use a **Raspberry Pi 4** board, which has USB3 ports and is as affordable as the older Pi models that have USB2?  The **Nvidia Jetson Nano** board is similarly affordable, is Arm-based like the Pi and has USB3 too.

As long as changes to unit-tests-live.cpp do not cause errors then in theory it should not cause problems in the Viewer and you should not have to make any special changes in the Viewer settings, though I cannot provide a guarantee that it would work as it has not been done before as far as I am aware.

In regard to the RealSense ROS wrapper, it runs as a compatibility layer on top of librealsense and so is going to be affected primarily by what librealsense is doing in the background rather than a stored configuration on the camera hardware

If you wanted to directly access the camera hardware then librealsense provides a **Low-Level API** to do so.

https://dev.intelrealsense.com/docs/api-architecture#section-low-level-device-api

The C++ example program **rs-data-collect** provides a demonstration of accessing the camera at low-level.

https://github.com/IntelRealSense/librealsense/tree/master/tools/data-collect

Overall though, using a modern USB3-equipped Pi 4 board as your SoC may be the easiest solution for accessing Infrared 2.

**Comment by MartyG-RealSense** [comment]
Hi @matthewoots  Do you require further assistance with this case, please?  Thanks!

**Comment by matthewoots** [comment]
@MartyG-RealSense Hi there, we can close this question! thank you for your support! To sum up for all who see this is USB3 is needed, if you want to use the `Infrared 2` for VIO etc

**Comment by MartyG-RealSense** [comment]
You are very welcome, @matthewoots - thanks very much for the update!
