### ISSUE TITLE
Problems with Point Cloud on Raspberry Pi 4

### ISSUE THREAD

**Issue by sergioar3143** [realsenseai/realsense-ros#2131]
Hello I followed the steps of this link for use D345i in my Raspberry Pi 4 https://ramith.fyi/setting-up-raspberry-pi-4-with-ubuntu-20-04-ros-intel-realsense/?fbclid=IwAR2j2hmCBUYakO6sHXwMt-UcD6ncNKpC-soZJI5rAcrEA1nwVNoNyXBuwlw
When I try to start the node with the command roslaunch realsense2_camera rs_camera.launch filters:=pointcloud, I can't see the Point Cloud. How can I resolve that problem?

**Comment by MartyG-RealSense** [comment]
Hi @sergioar3143  To visually view camera data of the ROS topics published by the RealSense ROS wrapper, you should launch RViz by using the command **rosrun rviz rviz** in the ROS terminal after rs_camera.launch has completed.  Have you run RViz, please?

**Comment by sergioar3143** [comment]
Yes, I used the command rosrun rviz rviz and when I added the pointcloud to Rviz, the terminal printed [ WARN] [1635002350.492095265]: No stream match for pointcloud chosen texture Process - Color
![pointcloud](https://user-images.githubusercontent.com/21043709/138562574-5fa69143-87c6-4016-a2a1-84b95c9909e9.png)

**Comment by MartyG-RealSense** [comment]
Is Fixed Frame set to **camera_link** like in the ROS wrapper documentation's point cloud example for rs_camera.launch please?

https://github.com/IntelRealSense/realsense-ros#point-cloud

**Comment by sergioar3143** [comment]
Yes, I have configured Rviz like the example
![pointcloud](https://user-images.githubusercontent.com/21043709/138563205-981dca64-5d1b-48f4-b0dc-f6dacd0d9fba.png)

**Comment by MartyG-RealSense** [comment]
Are you able to get a color image if you use the **Add** button in the RViz side-panel to add the RealSense camera topic **/camera/color/image_raw**

**Comment by sergioar3143** [comment]
I can't see a color image when I use the command roslaunch realsense2_camera rs_camera.launch filters:=pointcloud, but I can see a color imagen when I use the command roslaunch realsense2_camera rs_camera.launch

**Comment by MartyG-RealSense** [comment]
Raspberry Pi users in https://github.com/IntelRealSense/realsense-ros/issues/1324 experienced the same problem with no pointcloud when using the pointcloud filter but receiving images when not using it.  One of the Pi users in that case was able to receive a pointcloud if they set a custom FPS speed of 6.  Please try the example roslaunch instruction below, which uses the D435i's stream defaults of 848x480 depth and 1280x720 color but sets the FPS to 6 instead of 30.

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud depth_width:=848 depth_height:=480 depth_fps:=6 color_width:=1280 color_height:=720 color_fps:=6**

If that does not work, please also try setting both streams to 640x480 resolution at 6 FPS:

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud depth_width:=640 depth_height:=480 depth_fps:=6 color_width:=640 color_height:=480 color_fps:=6**

**Comment by sergioar3143** [comment]
The second one works well, thank you.

**Comment by MartyG-RealSense** [comment]
@sergioar3143  That's excellent news that you were able to obtain a pointcloud - thanks very much for the update!
