### ISSUE TITLE
no depth information published by d435i 

### ISSUE THREAD

**Issue by Abirami-Segar** [realsenseai/realsense-ros#2136]
hi

i am using intelrealsense d435i and in the rs_camera.launch file, i have enabled the depth information. but when i roslaunch this file, i get to see that the topic /camera/depth/image_rect_raw is subscribed.(i can see the topic when i command 'rostopic list', but when i echo the same rostopic, i see no information
![Screenshot from 2021-10-25 23-41-41](https://user-images.githubusercontent.com/62983491/138775260-93f70ee7-5bef-4018-b5eb-e19761eac79a.png)
.
![Screenshot from 2021-10-25 23-41-48](https://user-images.githubusercontent.com/62983491/138775267-bc61983d-97e0-45f3-92fe-4de666f2fa39.png)
![Screenshot from 2021-10-25 23-41-51](https://user-images.githubusercontent.com/62983491/138775276-3ac4b5a1-4402-4eb3-b426-32e53e13fe7d.png)
![Screenshot from 2021-10-25 23-41-57](https://user-images.githubusercontent.com/62983491/138775289-5a0ba1fe-88f7-47fd-9dca-8a4e61148c18.png)

)

please help.

Thank you.

**Comment by MartyG-RealSense** [comment]
Hi @Abirami-Segar   It looks as though the rs_camera.launch file has been modified from its defaults to set depth and infrared to 640x480 instead of '-1'.  Is this correct, please?  

If the launch file has been modified then the launch would be considered to be invalid and the default stream configuration of the camera would likely be applied instead.  This is because from ROS wrapper version 2.2.22 onwards, three factors have to be provided in a custom stream configuration for each stream type used - width, height and **FPS**.  Although width and height have been custom-configured at 640x480 in the launch file, a custom FPS value for depth - **depth_fps** - has not been defined and remains as '-1'.

![image](https://user-images.githubusercontent.com/41145062/138830740-44a9b978-5af4-4fde-bbaa-f6d6ae1e331a.png)

Please try the custom roslaunch instruction below to see whether depth is published correctly in rostopic echo when using this launch.

**roslaunch realsense2_camera rs_camera.launch depth_width:=640 depth_height:=480 depth_fps:=30**

**Comment by Abirami-Segar** [comment]
Thanks for the reply. Issue solved. Thanks for the support

**Comment by MartyG-RealSense** [comment]
Great news, @Abirami-Segar - thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
