### ISSUE TITLE
How to get the unfilterde pointcloud?

### ISSUE THREAD

**Issue by 18lalala** [realsenseai/realsense-ros#2148]
I am using D455 monocular and depth image to get pointclouds,but I found the msg "/camera/depth/color/points" is filtered pointclouds.So how can I get the initial pointclouds data?

**Comment by MartyG-RealSense** [comment]
Hi @18lalala  I wonder whether using **rs_rgbd.launch** instead of rs_camera.launch would meet your needs.

1.  Ensure that support for rgbd launch mode is installed if you have not done so already.  This can be performed with the instruction below depending on which ROS branch you are using:

**Kinetic**
sudo apt-get install ros-kinetic-rgbd-launch

**Melodic**
sudo apt-get install ros-melodic-rgbd-launch

**Noetic**
sudo apt-get install ros-noetic-rgbd-launch

2.  Launch RealSense ROS in rgbd mode with the rs_rgbd launch file.

**roslaunch realsense2_camera rs_rgbd.launch**

This will result in the generation of an **ordered** point cloud (using rs_camera.launch with the pointcloud filter generates an unordered cloud by default).

3.  Run RViz to visualize the point cloud.

**rosrun rviz rviz**

**Comment by MartyG-RealSense** [comment]
Hi @18lalala  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
