### ISSUE TITLE
Camera node do not publish image to topic /camera/color/image_raw when run rs_from_file.launch

### ISSUE THREAD

**Issue by ndinhtuan** [realsenseai/realsense-ros#2224]
Here is my environment: 
- Ubuntu 20.04
- ROS Noetic
- RealSense ROS v2.2.13
- LibRealSense v2.50.0

I record bag file from Intel RealSense D435, I open Realsense Viewer normally. But when I use realsense2_camera package to publish image through message, **rs_from_file.launch**, I cannot receive any message at **/camera/color/image_raw**. 
After debugging, I realize that the number of subscribers of info_publisher and image_publisher equal 0 (in file base_realsense_node.cpp, function void BaseRealSenseNode::publishFrame). 
![image](https://user-images.githubusercontent.com/15943606/149866336-49591b9f-a633-463d-9927-e8c4f273a2c4.png)
This is debug image: 
![image](https://user-images.githubusercontent.com/15943606/149866435-a6ddddf8-acca-4cc7-8946-c389f53dfbfc.png)

When I run file launch **rs_aligned_depth.launch**, I still receive message from **/camera/color/image_raw** topic.
This is debug image:
![image](https://user-images.githubusercontent.com/15943606/149866617-44b5170c-a839-40b6-8d16-e51038668c61.png)

I'm wondering about what difference between **rs_from_file.launch** and **rs_aligned_depth.launch**. Do anyone see that error ? and why there are no subscriber of info_publisher and image_publisher. Thank you very much.

**Comment by MartyG-RealSense** [comment]
Hi @ndinhtuan  Ideally, the RealSense ROS wrapper version should be matched as closely as possible with the librealsense SDK version listed in the wrapper version's release notes.  The correct ROS wrapper to match with SDK 2.50.0 and ROS Noetic is **2.3.2**.

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.3.2

You do not need to install librealsense again to perform the update, just to build the 2.3.2 wrapper from source code.

In regard to the launch, a bag file can only play back the data that was recorded into it as it is not using a live camera.  When recording is activated in the RealSense Viewer, it will record all of the streams that were currently enabled at the time that the record option was clicked.  Did you have a color stream active when recording the bag in the Viewer, please? 

The **rs_from_file.launch** will access the non-realtime recorded contents of the bag file, whilst **rs_aligned_depth.launch** will use live camera data by default and not the bag and so it would not have a problem with displaying a live stream from the camera's color sensor as long as the ROS wrapper is able to detect the sensor and publish messages from it.

The main problem with reading the bag file though may be that the librealsense SDK uses a bag format that has some differences to the ROS rosbag format that may make the file incompatible for playback in the ROS wrapper, as described by a RealSense team member in https://github.com/IntelRealSense/librealsense/issues/3020#issuecomment-452321766 and so recording the bag within ROS with **rosbag record** instead of in the RealSense Viewer would be preferable if you plan to playback in ROS.

http://wiki.ros.org/rosbag/Commandline#rosbag_record

**Comment by ndinhtuan** [comment]
@MartyG-RealSense  Thank you for replying.
I will try to build wrapper from source code again with version 2.3.2 and give you feedback soon.
For bagfile 

> Did you have a color stream active when recording the bag in the Viewer, please?

Yes, I do have color stream in bag file, and I also open bag file from Realsense Viewer, it run normally. I also use `rosbag play`, it also works.
Actually, I use `roslaunch`, sometimes it works, particularly I run 10 times, only 2 times I receive message from **/camera/color/image_raw**, remain 8 times, I see nothing happens.

**Comment by MartyG-RealSense** [comment]
Thanks very much @ndinhtuan - I look forward to your test results with wrapper 2.3.2.  Good luck!

**Comment by ndinhtuan** [comment]
Hi @MartyG-RealSense , I already installed realsense wrapper version 2.3.2. But I still got the same error.
![image](https://user-images.githubusercontent.com/15943606/150081673-9ec676b3-80de-4109-845c-79ee7e3af057.png)

**Comment by MartyG-RealSense** [comment]
Can you share your full roslaunch log from the terminal for **rs_from_file.launch** in a comment below, please?

**Comment by doronhi** [comment]
I think it is related to a known issue with playing back rosbag files with the wrapper.
It is mentioned in the known issues part in the release description: "Problems running from a bag file (using the "rosbag_filename" option)."
It is on my to-do list but I still didn't get around to it.

**Comment by ndinhtuan** [comment]
@MartyG-RealSense I would like to share you the log of roslaunch from the terminal:
![image](https://user-images.githubusercontent.com/15943606/150247428-e3efc256-a6bb-443a-9970-aaffee6ececc.png)

**Comment by MartyG-RealSense** [comment]
@ndinhtuan  I don't see anything wrong in your kindly provided launch log.  As Doronhi said, your problem may be related to the current known issue with bag playback that he referred to.

**Comment by ndinhtuan** [comment]
@MartyG-RealSense  Thank you very much for your support. I will find more information about the error that Doronhi mentioned.

**Comment by MartyG-RealSense** [comment]
You are very welcome, @ndinhtuan    :)

**Comment by MartyG-RealSense** [comment]
Hi @ndinhtuan  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
