### ISSUE TITLE
launch opensource_traking.launch file in  jetson nano is not work properly 

### ISSUE THREAD

**Issue by shubham300ska** [realsenseai/realsense-ros#2261]
Ubuntu Version -18.04 LTS
I launch rs_camera.launch in jetson nano and other file like  imufilter ,rtabmap,and robot localization  all launch in desktop 
but I didn't success to create map in my desktop
I connect this two system with wifi and I Export Master each system 
can you help me to solve the problem
how I can Do the mapping with jetson nano,Realsence camera D435i a with the help of desktop  
Thank in Advance
![Capture](https://user-images.githubusercontent.com/76483135/155284632-5e657e4d-9d76-46c0-a776-e4c617fd4f01.JPG)

**Comment by MartyG-RealSense** [comment]
Hi @shubham300ska  Have you tried Intel's D435i SLAM guide in the link below that explains how to generate a map, please?

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

The guide at that link was published before the IMU topics were later disabled by default in the RealSense ROS wrapper.  So you should add IMU enabling commands to the roslaunch instruction.

**roslaunch realsense2_camera opensource_tracking.launch enable_gyro:=true enable_accel :=true unite_imu_method:=linear_interpolation**

The 'unite_imu_method' instruction publishes the IMU data as a single **imu** topic instead of two separate gyro and accel topics.

**Comment by MartyG-RealSense** [comment]
Hi @shubham300ska  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
