### ISSUE TITLE
Enable decimation filter even when "align_depth = true "

### ISSUE THREAD

**Issue by mszuyx** [realsenseai/realsense-ros#2269]
Hi intel RS team,

This is a revisit / feature suggestion following the issue: #1834 

Basically, I would like the point cloud / depth image's resolution to be different than the RGB image (as robot navigation usually don't require high point cloud resolution, but a clear RGB image is always welcome). Meanwhile, I need the depth image and RGB image to have similar FOV. (I am using D455, the FOV difference exist but relatively small)

I have been setting the **align_depth = false** and use the **decimation filter** to achieve this. The  **align_depth** option allows me to decouple the resolution setting between RGB image and depth image. And **decimation filter** allows me to further reduce the resolution.

However, as I need to preform mask mapping between RGB image and depth image, I need to set **align_depth = true**. But doing this effectively overwrite the depth image resolution setting and  decimation filter (no matter what you set the resolution to / or resolution the terminal reports, the cloud resolution is ALWAYS the same as the RGB image).

I wonder:

1. Is there a way to let **decimation filter** and **align_depth** compatible with each other?
2. If not, can you provide some insight on how to post-process it in a custom node? (for now I am just cropping the depth image, is it the equivalent of **align_depth**? Or the **align_depth** is more complicated than that?)

Thanks!
Yu

**Comment by MartyG-RealSense** [comment]
Hi @mszuyx  I believe that this question is a follow-up to your align / decimation question at https://github.com/IntelRealSense/realsense-ros/issues/1924 in 2021.  Doronhi suggested a 'bypass' method at https://github.com/IntelRealSense/realsense-ros/issues/1924#issuecomment-864510866 for enabling align_depth and decimation to work together, which I believe you tried implementing but it did not solve your particular problem.  Is that correct, please?

At the end of that case, Doronhi also suggested at https://github.com/IntelRealSense/realsense-ros/issues/1924#issuecomment-904354287 that modifying the **frame_callback()** function may be a solution for what you were requesting.

Instead of using decimation for the purposes of reducing resolution, defining a custom stream configuration with the roslaunch instruction and setting your own choice of stream resolutions may be an easier alternative.  Below is an example of doing this for the depth and color streams.

`roslaunch realsense2_camera rs_camera.launch depth_width:=640 depth_height:=480 depth_fps:=30 color_width:=640 color_height:=480 color_fps:=30`

In a custom stream configuration, three factors must be specified for each stream type defined - width, height and FPS.  If these 3 factors are not provided then the RealSense ROS wrapper deems the configuration invalid and automatically uses the default configuration of the particular RealSense camera model instead.

In answer to your two questions:

1.  I don't have any advice that was not already covered in https://github.com/IntelRealSense/realsense-ros/issues/1924

2.  I could not find any resources regarding accessing librealsense's post-processing functions from a ROS node script instead of using the wrapper's filters.

**Comment by mszuyx** [comment]
@MartyG-RealSense You are absolutely correct! I forgot we have went that route already! (great catch! )
I think because I recently git from the repo again and that undone my previous effort, causing me to think the method didn't work.

So the take away is, since Doronhi's 'bypass' method does allow align_depth and different resolution settings to co-exist, lets use resolution setting (instead of decimation filter) to reduce resolution? 

I will try it today if that solve the problem. And by "post-processing", I was thinking about something like [depth_image_proc/register](http://wiki.ros.org/depth_image_proc?distro=noetic). If I can't resolve the issue with launch file and realsense_node, I will try that and let you know how it goes!

Thanks again!
Yu

**Comment by mszuyx** [comment]
@MartyG-RealSense I just tried Doronhi's 'bypass' method:

- Now setting **align_depth = true** will provide us with two depth images: _/aligned_depth_to_color/image_raw_ and _/depth/image_rect_raw_ . The _/depth/image_rect_raw_ is loyal to the depth resolution setting, while the  _/aligned_depth_to_color/image_raw_ still copying RGB resolution setting. --Which is ok for my application.

- However, I just realize that we need the resolution of depth image / pointcloud to be ~212 x 120 for our application (and that is why decimation filter is prefect). And somehow 256 x 144 is not an available option for the launch file (I guess that is because I am streaming at 30 fps and the node doesn't like it). 

- I also tried using the [depth_image_proc/register](http://wiki.ros.org/depth_image_proc?distro=noetic) method. It turns out it can't really handle the case when the depth image is at a different resolution than the RGB image. -- It gives a very sparse depth image. (Unless I hack the RGB camera_info to trick the node to think otherwise). Also, even when the resolutions are the same, registering using this method will introduce artifacts on depth image. Making the depth image nosier.

-- So, I guess the prefect solution is still somehow make **align_depth** and **decimation filter** to co-exist? (i.e., let the decimation filter effective on only the _/depth/image_rect_raw_  will be sufficient. I can resize the _/aligned_depth_to_color/image_raw_ myself when doing the RGB to depth mapping)

We are trying to deploy some neural network models along side with realsense-ros on a single board computer. So we would like to cut down CPU consumption whenever possible.

**Comment by MartyG-RealSense** [comment]
On D455, 256x144 depth is supported at **90** FPS.  The processing burden of streaming 90 FPS at that minimum resolution should not be very high though.

![image](https://user-images.githubusercontent.com/41145062/156778678-3b2e9a0e-9c43-443b-a0f2-ea302d15dd52.png)

**Comment by mszuyx** [comment]
@MartyG-RealSense Hi, 

I did some tests today to compare the **256x144@90FPS** vs. **424x240@30FPS (with decimation@2)** configs.
At first I was trying to compare the CPU usage in each case. But I found out that the depth image and point cloud creating with 256x144 option seems cut-off:
![Screenshot 2022-03-08 14:52:10](https://user-images.githubusercontent.com/37651144/157323656-caea7057-b074-4e7a-b66f-115047afa315.png)

And here is the same camera pointing at the same position (scene) using the 424x240 option:
![Screenshot 2022-03-08 14:53:31](https://user-images.githubusercontent.com/37651144/157323803-c6648458-ee3a-4ae8-9415-b0d7ef09d9aa.png)

Could you help me understand this? (Similar behavior can be seen on realsense-viewer as well)

Here is my launch file that enables 424x240 setup if you are interested:
[rs_d455_camera_pco.zip](https://github.com/IntelRealSense/realsense-ros/files/8209571/rs_d455_camera_pco.zip)
To enable 256x144 I just change the depth resolution accordingly and FPS to 90 and set decimation to 1 at the end.

I also notice when the align_depth is enabled, ros-realsense will publish a topic that describes the extrinsic matrix between RGB and depth frame. I am thinking maybe I can do the registering/alignment myself with the 424x240 option using reasonable resources. But meanwhile, if realsense can allow me to use decimation with align_depth, that will be very useful!

Thanks

**Comment by mszuyx** [comment]
@MartyG-RealSense Is it possible for you to provide the homography transformation between the rgb and depth frame? Knowing this transformation matrix, I assume the alignment can be done with _cv2.warpPerspective()_.

**Comment by MartyG-RealSense** [comment]
Are you asking why 256x144 without decimation does not look the same as when 424x240 is decimated, please?  If so, I am not certain about the precise mechanics of the process.  A decimated image is different from setting the resolution with the direct selection of a supported RealSense resolution mode though, since the decimation process is taking a higher resolution and 'downsampling' the pixels, scaling the image down proportionally in both dimensions to preserve the aspect ratio.

In regard to comparing the transform between two coordinate systems in ROS, my understanding is that this can be done with **rosrun tf tf_echo**.  For example, if comparing the transform between gyro and depth:

**rosrun tf tf_echo camera_depth_optical_frame camera_gyro_optical_frame**

You can also retrieve the extrinsic transformations between two sensor types on a particular camera using the librealsense tool **rs-enumerate-devices** by launching the tool in calibration information mode:

`rs-enumerate-devices - c`

As you mention **Homography** and OpenCV though, you may be referring to the topic discussed at https://github.com/IntelRealSense/librealsense/issues/2484

**Comment by mszuyx** [comment]
@MartyG-RealSense Yes. Ideally a change in resolution setting shouldn't affect the FOV of the view. And the fact that this resolution setting only work with 90 FPS leads me to think this 256x144 setting is subscribing to a sub-system in the camera. (i.e., the IR projector/receiver. And not even using the stereo features. -- that explains the rigid constraint on FPS and the change in FOV)

For now I am trying to create a homography matrix based on camera models and tf transformation. I will keep you posted.

**Comment by MartyG-RealSense** [comment]
256x144 resolution was introduced when the **On-Chip Calibration** system was released.  More information about it is provided at the link below.

https://dev.intelrealsense.com/docs/self-calibration-for-depth-cameras#section-2-2-example-target-for-calibration-characterization

**Comment by mszuyx** [comment]
@MartyG-RealSense Interesting!

Btw, I got the homography transform to work (actually the affine transform works just fine). I guess for future reference, if people want to create their own alignment solutions. They can check out these two links:
[geometric transformation](https://towardsdatascience.com/image-geometric-transformation-in-numpy-and-opencv-936f5cd1d315)
[register depth image](https://github.com/ros-perception/image_pipeline/blob/noetic/depth_image_proc/src/nodelets/register.cpp)

**Comment by MartyG-RealSense** [comment]
That's excellent news that you achieved a solution!  Thanks very much for the update and for sharing details of your method with the RealSense community  :)
