### ISSUE TITLE
D405 ROS Wrapper

### ISSUE THREAD

**Issue by fiorano10** [realsenseai/realsense-ros#2290]
Currently, only ROS2 supports the new D405 camera, is there a timeline when it will be available for ROS 1? If yes, what is it?

**Comment by MartyG-RealSense** [comment]
Hi @fiorano10   I will make enquiries about your question.  Thanks in advance for your patience.

**Comment by MartyG-RealSense** [comment]
I conducted discussions with Intel about the ROS1 wrapper.  It is planned that the ROS1 wrapper will not receive new features, such as D405 support.  The development focus is now on the 4.x ROS2 wrapper on the **ros2_beta** branch.  So D405 owners should use the 4.x ROS2 wrapper.

**Comment by eric-schleicher** [comment]
I'm a bit unclear on the final disposition of this issue.   Is there an accepted pattern for using ROS2 wrappers to provide compatibility for non-EOL distributions of ROS1 (noetic, melodic)?   Or is this a quixotic recommendation stipulating that customers of with a *new* 405 camera MUST upgrade their ROS platform system to ROS2?  I hope not, because that sounds insane.

![ros-eol](https://user-images.githubusercontent.com/8261783/165649336-b53e5fdb-5150-4c55-8f57-e1cea5f4c5f3.png)

**Comment by MartyG-RealSense** [comment]
The new D405 model is only supported by the 4.x ROS2 wrapper series on the **ros2_beta** branch.  There are no plans to add support for D405 to the 2.x ROS1 wrapper or the previous 3.x ROS2 wrapper as the focus of the RealSense ROS wrapper's developer team is now on the 4.x ROS2 wrapper series.

**Comment by eric-schleicher** [comment]
Without prejudice; it's unfortunate to see this get passed over.  Hopefully this will change in the future.
