### ISSUE TITLE
why is the rs2::error??

### ISSUE THREAD

**Issue by Z-star1** [realsenseai/realsense-ros#2328]

**Comment by Z-star1** [comment]
![2022-04-22 16-22-07 的屏幕截图](https://user-images.githubusercontent.com/62822578/164663324-c4749817-493f-4be0-a22f-a6970e68719f.png)

**Comment by MartyG-RealSense** [comment]
Hi @Z-star1  It looks as though you are using the **ORB-SLAM3** SLAM library at the link below.  Is that correct, please?

https://github.com/UZ-SLAMLab/ORB_SLAM3

The example that you are launching was designed for use with the RealSense D435i camera model and needs to have the .yaml file edited if it is not a D435i.  Are you using a D435i or a different RealSense model?

The **failed to set power state** error usually means that the camera was not able to be accessed, perhaps because it could not be detected or it was already busy when the access attempt was made (for example, the camera was already currently being used for streaming in another program).

**Comment by Z-star1** [comment]
> Hi @Z-star1 It looks as though you are using the **ORB-SLAM3** SLAM library at the link below. Is that correct, please?
> 
> https://github.com/UZ-SLAMLab/ORB_SLAM3
> 
> The example that you are launching was designed for use with the RealSense D435i camera model and needs to have the .yaml file edited if it is not a D435i. Are you using a D435i or a different RealSense model?
> 
> The **failed to set power state** error usually means that the camera was not able to be accessed, perhaps because it could not be detected or it was already busy when the access attempt was made (for example, the camera was already currently being used for streaming in another program).

yes,i am runing ORBSLAM3 with D435i.but  it made a rs2::error.   and I've located the error here.    can you help me?because not only one have this problem.
![2022-04-22 19-30-51 的屏幕截图](https://user-images.githubusercontent.com/62822578/164706440-3fd18f0c-9b2c-4f40-9a95-a022ec645774.png)

**Comment by MartyG-RealSense** [comment]
Does the problem still occur if you use the script below?

```
  rs2::context ctx;// Create librealsense context for managing devices
    // Declare RealSense pipeline, encapsulating the actual device and sensors
    std::vector<rs2::pipeline> pipelines;

    // Start a streaming pipe per each connected device
    for (auto&& dev : ctx.query_devices())
    {
        rs2::pipeline pipe(ctx);
        rs2::config cfg;
        //uncomment this will rise a `failed to set power state`bug
        //cfg.enable_device(dev.get_info(RS2_CAMERA_INFO_SERIAL_NUMBER));
        pipe.start(cfg);
        pipelines.emplace_back(pipe);
    }
```

This script is from an Nvidia Jetson user who was experiencing the **Failed to set power state** error when building a list of camera devices.

https://forums.developer.nvidia.com/t/failed-to-set-power-state-error-for-multiple-realsense/121105

**Comment by MartyG-RealSense** [comment]
Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
