### ISSUE TITLE
NO compressed topic 

### ISSUE THREAD

**Issue by Zhuomin-Zhou** [realsenseai/realsense-ros#2329]
Hi,
When I run ros2-foxy wrapper on raspberry 4, it jumped the errors which show blow. In the topic list, there are no compressed topics. 
The realsense-viewer works well, and I have tried the initial_reset:=true.

Version LibRealSense2: 2.50
system: Ubuntu 20.04
camera: D435i and D435

Error:
[realsense2_camera_node-1]  24/04 10:26:07,463 WARNING [281473013762464] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

The topic list is shown below.

Topic list:
/camera/aligned_depth_to_color/camera_info
/camera/aligned_depth_to_color/image_raw
/camera/color/camera_info
/camera/color/image_raw
/camera/color/metadata
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/depth/metadata
/camera/extrinsics/depth_to_color
/camera/imu
/parameter_events
/rosout
/tf_stati

Thanks in advance!

**Comment by MartyG-RealSense** [comment]
Hi @Zhuomin-Zhou  As you state that you are using the **ros2-foxy** wrapper, may I confirm which wrapper version number you are using please?  The RealSense ROS2 wrapper stopped being called 'ros2-foxy' after version 3.2.0.

https://github.com/IntelRealSense/realsense-ros/releases/tag/3.2.0

The most recent 'ros2-foxy' version (3.2.0) was designed for matching with librealsense SDK version **2.45.0**, whilst you are using librealsense 2.50.0.  RealSense ROS wrapper versions should be matched as closely as possible with a specific librealsense version listed in the ROS wrapper release notes for that version.  

If you are using librealsense 2.50.0 then it should be matched with ROS2 wrapper version **3.2.3** on the ros2 branch or **4.0.4** on the ros2-beta branch.  
  
Can you confirm which RealSense ROS2 wrapper version you are using with librealsense 2.50.0 please?

***********

It is also worth bearing in mind that the RealSense Viewer does not perform depth to color alignment in its **2D** mode, whilst you have configured the RealSense ROS wrapper to align depth and color.  Alignment is a processing-intensive function that is processed on the computer and not on the camera hardware.  

So it is possible that whilst the Pi 4 is able to run the Viewer well because it is not using alignment, the Pi may be struggling to process alignment in the ROS wrapper, resulting in the **resource temporarily unavailable, number 11** type of control_transfer returned warning.  This message can indicate that the computer is unable to keep up with processing the volume of data that is arriving on the USB port.

*********

It is also worth highlighting my message to you in https://github.com/IntelRealSense/realsense-ros/issues/2140#issuecomment-1107532739 regarding how some non-RealSense users of ROS2 Foxy have been reporting having problems with compressed topics recently at the time of writing this.

**Comment by Zhuomin-Zhou** [comment]
Hi,

I am sorry, I was talking about the ROS2 wrapper.
I have tested the latest version of ROS2  wrapper and -beta Wrapper. But either didn't show the compressed topics. The error is the one I mentioned.

Thanks!
Min

**Comment by Zhuomin-Zhou** [comment]
Hi @MartyG-RealSense ,

Would it be caused by the parameters setting? as the CPU of raspberry pi 4 is not enough.
Do you have any recommendations for parameters setting, to get the depth, color-comperssed images, and point cloud?

Thanks in advance!
Min

**Comment by MartyG-RealSense** [comment]
Which method are you using to start the ROS2 wrapper, please - a launch file or ros2 run

There was a recent case where a RealSense ROS2 user had problems when starting with **ros2 launch realsense2_camera rs_launch.py** that did not occur if they started with **ros2 run realsense2_camera realsense2_camera_node** instead.

**Comment by Zhuomin-Zhou** [comment]
Hi @MartyG-RealSense 

I tried to start with **ros2 run realsense2_camera realsense2_camera_node**, but it was not working. 
I also changed the depth_module and rgb_modle to 640×480×15， which was not working.
The compressed topics still disappeared.

Thanks!

**Comment by MartyG-RealSense** [comment]
I have not seen any other reports of compressed topics being missing on ROS2.

Would your project be able to make use of uncompressed **/camera/color/image_raw** if '/camera/color/image_raw/compressed' is not published?

**Comment by Zhuomin-Zhou** [comment]
> I have not seen any other reports of compressed topics being missing on ROS2.
> 
> 
> 
> Would your project be able to make use of uncompressed **/camera/color/image_raw** if '/camera/color/image_raw/compressed' is not published? 

Hi @MartyG-RealSense，

Thanks for your help!
Because the bandwidth of the network for colour and depth images is not enough, the uncompressed images cannot be used.
But, I have found the reason that causes the situation. As the **images_transport_plugins** were not installed, which is why there were not compressed topics.

Regards,
Min

**Comment by MartyG-RealSense** [comment]
It's great to hear that you found the solution, @Zhuomin-Zhou - thanks very much for the update  :)

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.

**Comment by pengzhenghao** [comment]
For those found this issue, install the image transport plugin with:

```
# For this at your robot
sudo apt-get install ros-foxy*-image-transport*

# Install this at your PC
sudo apt-get install ros-humble*-image-transport*
mamba install ros-humble*-image-transport*
mamba install ros-${ROS_DISTRO}-image-transport-plugins
```

**Comment by shtern** [comment]
@pengzhenghao you're a lifesaver, thank you very much! worked for me (ROS Galactic, 4.0.4, 2.50)
