### ISSUE TITLE
How to ensure get_frame_metadata strictly correspond to frame

### ISSUE THREAD

**Issue by Zoltan3057** [realsenseai/realsense-ros#2377]
Hi, 
I wonder how the metadata got by "get_frame_metadata" is strictly correspond to the frame in "frame_callback." There is no lock. Is it based on the assumption that the processing time is quick enough. If there is an exposure change, will the metadata happen to be the changed exposure time value.

**Comment by MartyG-RealSense** [comment]
Hi @Zoltan3057  Metadata attributes are updated and recalculated on a per-frame basis.

The section of the RealSense SDK's **Frame Metadata** documentation linked to below references metadata in relation to frame callbacks.

https://dev.intelrealsense.com/docs/frame-metadata#metadata-query-api

If depth exposure changes whilst depth auto-exposure is enabled then this change will be reflected in the metadata attribute 
**ACTUAL_EXPOSURE** that represents the "real" exposure value, since the exposure value does not update whilst auto-exposure is active.  

The ACTUAL_EXPOSURE for the RGB stream cannot be retrieved whilst RGB auto-exposure is enabled though.

**Comment by MartyG-RealSense** [comment]
Hi @Zoltan3057  Do you require further assistance with this case, please?  Thanks!

**Comment by Zoltan3057** [comment]
Sorry for late reply.
Previously, I recorded images and exposure times while changing camera's exposure time. And there are some mismatches between images and exposure times. Somehow those mismatches don't appear anymore.
Add sleep(0.1) after sensor.set_option may be the reason. 
Thanks for your explanation. It helps a lot.

**Comment by MartyG-RealSense** [comment]
You are very welcome, @Zoltan3057 - thanks very much for the update!
