### ISSUE TITLE
depth and rgb misalignment proportional to vertical position on frame, potentially worsening over time!

### ISSUE THREAD

**Issue by Bart-van-Ingen** [realsenseai/realsense-ros#2379]
Hello! I am not sure if this question belongs more to the realsense-ros or the librealsense repository, correct me if I am wrong!

At my company we are using the realsense d415 to image plants on a 0.5m/s moving ROS2 platform, with the camera pointing down at the plants. We use the realsense-ros ros2 branch to integrate the camera with the rest of our system.   'enable_sync' is set to true in our launch file. Our fps for both rgb and depth is 6 fps.

We have been running into a problem where it seems that there is a misalignment between the rgb and depth map the further down the images you go. It also seems that this problem has been getting progressively worse over the year on a realsense that is used in a prototype at a client. This can be seen in the images below.

The grey mask shows the depth map with the ground level removed. This should therefore indicate the plants in the depth map. The rgb image is below this mask. In the image from September 2021, we see that there is almost perfect overlap between the depth map mask and the plants in the rgb image, since no plants peak out under the mask. In the following image from October 2021 we can see that this overlap is not as good. The crazy part is that it seems to be fine for the first quarter of the image and getting worse the lower you go on the image. This is also highlighted by the last image of June 2022.

Note: we think that the direction of the shift (up or down) is dependent on the direction in which our device is moving (up or down).

**September 2021**  
![layered_Depth_and_sd](https://user-images.githubusercontent.com/36703540/173867356-9b6ba09e-bd5f-44e1-8b60-2658ce01ac8b.jpg)

**October 2021**  
![layered_depth_and_sd](https://user-images.githubusercontent.com/36703540/173867314-5760a1b0-9cb0-4034-a224-fdb1d85b3b99.jpg)

**June 2022**
![layered_depth_and_sd](https://user-images.githubusercontent.com/36703540/173867240-ea87bbc0-bf41-4152-a1f9-c4f8740ab318.jpg)

There are similar issues that can be found here :
[Color and depth maps are not aligned when moving fast · Issue #4771 · IntelRealSense/librealsense · GitHub](https://github.com/IntelRealSense/librealsense/issues/4771)
 [Color and Depth Maps Not Aligned as Speeds Increase · Issue #5867 · IntelRealSense/librealsense · GitHub](https://github.com/IntelRealSense/librealsense/issues/5867)

An interesting quote @MartyG-RealSense in [issue 5867](https://github.com/IntelRealSense/librealsense/issues/5867):

> When D400 RGB and Depth sensors are set to the same FPS and the actual exposure does not exceed the frame period, then RGB sensor internally acts as Master and at the beginning of each frame it sends HW pulse to the Depth (Slave) sensor to start Depth generation as well. This results in Depth and RGB frames being captured simultaneously (timestamp offset < 1msec)

We observe the  exposure of the rgb to be around 25 microseconds. We also think that the exposure of the infrared cameras. This is far below 1/6, so this not seem likely to be the issue.
Although only qualitative, we do get the impression that the higher we set the fps the lesser this problem becomes.

Has anyone experienced something similar or has a useful tip on how to get closer to the origin of this bizarre problem?

**Comment by MartyG-RealSense** [comment]
Hi @Bart-van-Ingen  I would recommend using 15 FPS instead of 6 FPS, as at 6 FPS there may be errors that disappear at 15.  Using 6 FPS introduces the possibility that there may be time-outs in the camera stream because new frames are not arriving quickly enough.

If you need to use 6 FPS then disabling RGB auto-exposure if you have it enabled and setting manual RGB exposure to around '70' can provide a smooth stream with minimal RGB blur.  I note though that you had almost perfect alignment in September 2021, suggesting that your configuration may essentially be fine.

During the year, have you performed **recalibration** of the camera at any time?  If the camera has been operating continuously for 12 months without recalibration then the depth and RGB could become progressively more out of alignment as time passes.

**Comment by Bart-van-Ingen** [comment]
Hi @MartyG-RealSense thanks for the quick response! We will be switching to 15 fps and I will relay back if it has fixed our problem!

We have been running our camera with rgb auto-exposure set to false and with a rgb exposure no higher than 30. The camera has not been running continuously for 12 months, but has been in a demanding environment with occasionally high temperatures and humidity. 

For the recalibration is there any manual interaction needed? It will be difficult to go to every realsense we have in the field to calibrate it every so often ...

**Comment by MartyG-RealSense** [comment]
Recalibration requires manual interaction, yes.  If your project is able to switch to the **D455** model then it has a thermal compensation mechanism that can automatically adjust for changes in environmental temperature to maintain depth measurement accuracy.  This mechanism is discussed at https://github.com/IntelRealSense/librealsense/issues/8434

Alternatively, you could set up a calibration target board or boards on the moving platform's route in the environment that the cameras operate in and have the platform be able to stop at these boards and undergo calibration instead of having to visit the camera in person.

**Comment by Bart-van-Ingen** [comment]
We are actually reverting back from the D455 due to the bad color performance in the high sun light situation (https://github.com/IntelRealSense/librealsense/issues/7155). We will think about the implementation of the boards, thanks for the suggestion!

So far the simple solution of changing the fps to 15 seems to be working well, we are back to the original overlap!

If 6 fps is not a well function fps, should it then be a setting in the realsense? I can imagine that more people may fall over this issue ...

**Comment by MartyG-RealSense** [comment]
6 FPS (or 5 FPS on the D455 model) can work but there are a range of factors that can affect performance on a particular computing configuration.  15 FPS tends to be a good setting that can run well on most systems.

The link below discusses retro-fitting cameras with the CLAREX light filters that are built into Intel's new D435 variant the **D435f**.

https://support.intelrealsense.com/hc/en-us/community/posts/7030571809299

**Comment by MartyG-RealSense** [comment]
Hi @Bart-van-Ingen  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by Bart-van-Ingen** [comment]
Hi Marty! 

For now this has resolved the issue, thanks for the help!

**Comment by MartyG-RealSense** [comment]
That's great to hear, @Bart-van-Ingen - thanks very much for the update!
