### ISSUE TITLE
Cannot get latest official version ros--kinetic-realsense-ros-2.3.2 in Ubuntu16.04?

### ISSUE THREAD

**Issue by byhang** [realsenseai/realsense-ros#2393]
Hi Intel,
I wanna get official version 2.3.2, what can I do?

I set my env according to [librealsense](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md), I got 2.3.0 when I run `sudo apt-get install ros-$ROS_DISTRO-realsense2-camera`.
> Get:1 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-librealsense2 amd64 2.45.0-1xenial-20210506-081043-0800 [12.8 MB]
> Get:2 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-realsense2-camera amd64 2.3.0-1xenial-20210506-084151-0800 [308 kB]  

###  sudo apt-get install ros-$ROS_DISTRO-realsense2-camera=2.3.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '2.3.2' for 'ros-kinetic-realsense2-camera' was not found

**Comment by MartyG-RealSense** [comment]
Hi @byhang  I note that you are using ROS Kinetic and the output provides the message **E: Version '2.3.2' for 'ros-kinetic-realsense2-camera' was not found**.  Instead of librealsense 2.50.0 and wrapper 2.3.2, it provides librealsense 2.45.0 and wrapper 2.3.0.

Wrapper 2.3.0's release coincided with the time around May 2021 when Kinetic was made End of Life (EOL) by ROS and no longer updated with syncs.

https://discourse.ros.org/t/preparing-for-final-kinetic-sync/19805

The most recent RealSense ROS1 wrappers such as 2.3.2 still list compatibility with Kinetic.  Would it be possible to build librealsense and the wrapper seperately instead of building them both at the same time from packages with the `apt-get install` command, please?  You could build librealsense from either packages or source code, but the ROS wrapper would have to be built from source code after the librealsense install has been completed successfully.

**Comment by byhang** [comment]
Thx very much, I try try

**Comment by byhang** [comment]
Thank you @MartyG-RealSense very much for your careful assistance.
In Ubuntu-16.04, I build ddynamic-reconfigure-0.3.2、 realsense-ros-2.3.2 and librealsense2-2.50.0 from source code, than I solved this problem.

**Comment by MartyG-RealSense** [comment]
It's great to hear that you achieved a solution!  Thanks very much for the update  :)
