### ISSUE TITLE
Problem with topic TF

### ISSUE THREAD

**Issue by alvaropascuaI** [realsenseai/realsense-ros#2471]
Hi, i try to use RTABMAP - Ros2, but i have the next error, i try to launch topic tf since module realsense2 but i can't
What i need to do for publishing data from topic /tf
![image](https://user-images.githubusercontent.com/97975075/188623416-1252b3f7-5c42-4a70-9947-c01bf145dda8.png)

**Comment by MartyG-RealSense** [comment]
Hi @alvaropascuaI  There is a case of this error with a RealSense D435i and rtabmap_ros on the Nvidia Jetson support forum.

https://forums.developer.nvidia.com/t/jetson-xavier-nx-intel-realsense-d435i-camera-stop-transmit-data-after-a-time/216318

The RealSense user in that case found that the error was resolved if they reduced depth and color FPS to 15, though they still had other warnings being generated.

**Comment by alvaropascuaI** [comment]
I try, but i have the same problem
![image](https://user-images.githubusercontent.com/97975075/188626150-08f0ba71-e0c4-40b2-951b-1b21bd1305e2.png)

**Comment by MartyG-RealSense** [comment]
Which launch file of the RealSense ROS2 wrapper are you using, please?  And have you set the IMU gyro and accel topics to True, as they are disabled by default.

**Comment by alvaropascuaI** [comment]
I launch with next command **ros2 run realsense2_camera realsense2_camera_node --ros-args -p initial_reset:=true -p enable_infra1:=true -p depth_width:=640 -p depth_height:=480 -p depth_fps:=15.0 -p infra1_width:=640 -p infra1_height:=480 -p infra1_fps:=30.0 -p color_width:=640 -p color_height:=480 -p color_fps:=15.0 -p enable_accel:=true -p enable_gyro:=true -p gyro_fps:=200.0 -p accel_fps:=63.0 -p enable_pointcloud:=true -p unite_imu_method:="linear_interpolation"**

**Comment by MartyG-RealSense** [comment]
I note that your earlier log image showing the streams that are being published does not include the gyro and accel streams.  Can you confirm please whether the IMU topics are being published?

![image](https://user-images.githubusercontent.com/41145062/188685781-3764efa8-481f-4bf3-85a9-9bdf4acbd76d.png)

**Comment by alvaropascuaI** [comment]
I have next topics, if i launch with command that i told u before
![image](https://user-images.githubusercontent.com/97975075/188687372-f37b23de-9be4-478e-ab44-d7fb052ab1b4.png)

**Comment by MartyG-RealSense** [comment]
What happens if you launch with rs_launch.py instead of ros2 run?

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=640x480x30 initial_reset:=true  pointcloud.enable:=true enable_accel:=true enable_gyro:=true gyro_fps:=200.0 accel_fps:=63.0 unite_imu_method:="linear_interpolation"`

**********

If you are using the **ros2_beta** wrapper then it is worth highlighting that in that wrapper, enable_pointcloud:=true was changed to **pointcloud.enable:=true**

You also do not need to define a long list of width, height and FPS values in the ros2_beta wrapper as you instead use a **profile** instruction such as depth_module.profile:=640x480x30 which is the same as depth_width:=640 depth_height:=480 depth_fps:=30.0 infra1_width:=640 infra1_height:=480 infra1_fps:=30.0

The full list of changes is here:

https://github.com/IntelRealSense/realsense-ros/tree/ros2-beta#please-notice-if-you-are-moving-from-realsense-ros2-branch-to-ros2-beta

**Comment by alvaropascuaI** [comment]
I launch with your command and i have the next topics, and about ros2_beta i don't use 
![Captura desde 2022-09-07 08-20-53](https://user-images.githubusercontent.com/97975075/188804198-36efa1b6-40be-4593-8aac-06ed976d69dd.png)

**Comment by MartyG-RealSense** [comment]
Thanks for your confirmation that you are using **ros2** instead of **ros2_beta**.

So you have tried launching with both ros2 run and ros2 launch and both methods resulted in the same error?

The Nvidia forum case that I quoted earlier is the only other occurrence of this exact error message that I could find.  In a case at https://github.com/introlab/rtabmap_ros/issues/653#issuecomment-939555927 with a similar but not exact error, it was suggested that the error might result from timestamps not being synchronized.

Does the error disappear if you add **global_time_enabled:=true** to your launch instruction, please?

You could also try **enable_sync::=true**

**Comment by alvaropascuaI** [comment]
Thank you, very much, I added that global_time_enabled:=true and i pass the error, i want to ask u all question in me life

**Comment by MartyG-RealSense** [comment]
You are very welcome.  It's great to hear that you were successful  :)
