### ISSUE TITLE
Wrong encoding when trying to extract image from bag

### ISSUE THREAD

**Issue by jcremona** [realsenseai/realsense-ros#2473]
Hi! I'm trying to extract some images from a bagfile. I opened the bagfile using rqt_bag and I could see that image msgs were saved with encoding 'rgb8'. Using this simple script, I've saved images to my hard drive:
```
    for topic, msg, t in bag.read_messages(topics=[args.image_topic]):
        cv_img = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")
        cv2.imwrite(os.path.join(args.output_dir, "frame%06i.png" % count), cv_img)
```
Note that `desire_encoding="passthrough"` implies that image are saved with the same encoding as ROS image msg. The resulting images looks like this one:
![passthrough](https://user-images.githubusercontent.com/3181393/188956922-b2ea4284-1a35-4b0e-b1f8-5b5cdbe970fc.png)
However, if I use `desire_encoding="bgr8"`, images looks fine. So, images stored in the rosbag are indeed rgb8? Could this be a bug in realsense-ros? 

Thanks.

**Comment by MartyG-RealSense** [comment]
Hi @jcremona  Yes, RGB in the RealSense ROS wrapper uses the RGB8 format.

As images are blue tinted with RGB8 but look normal with BGR8, this may be an OpenCV **color space** issue, as this can cause such a color reversal due to OpenCV's default color space being BGR and not RGB.  https://github.com/IntelRealSense/librealsense/issues/9304 and https://github.com/IntelRealSense/librealsense/issues/9541 are examples of this phenomenon.

**Comment by MartyG-RealSense** [comment]
Hi @jcremona  Do you require further assistance with this case, please?  Thanks!
