### ISSUE TITLE
Missing frames in the aligned_depth_to_color/image_raw topic

### ISSUE THREAD

**Issue by ricber** [realsenseai/realsense-ros#2474]
Hi, I report a problem we are facing with a D435i camera. As you can see from the following screenshot of rqt_bag, we regularly miss frames for some seconds when we record the depth data with the d435i camera.
![Screenshot from 2022-08-25 18-27-21](https://user-images.githubusercontent.com/18362950/189320727-2c9eb692-7fe5-4cc6-9f10-8b9c38bdca30.png)

What can be the cause of the problem? 

The D435i camera is connected directly to a USB 3.0 port with the official Intel cable. The Ubuntu version is 18.04, and the ROS distro is melodic. RealSense ROS version is v2.3.2 and LibRealSense is v2.50.0. The device FW version is 05.12.14.50. Everything is running on a Shuttle PC with an Intel Core i7-4790S CPU.

When the camera is started, we also get some WARNINGS on the terminal. Look at the screenshot below. 
![Screenshot from 2022-08-25 18-28-01](https://user-images.githubusercontent.com/18362950/189321520-b6b08c8e-ecd1-43f0-8e2e-9d1a2bb99bba.png)

**Comment by MartyG-RealSense** [comment]
Hi @ricber  Does the number of warnings reduce if you add **global_time_enabled:=true** to your roslaunch instruction, please?

**Comment by ricber** [comment]
No, the parameter **global_time_enabled** did not reduce the number of warnings nor the missing frames. Moreover, I am not sure the warnings are related to the missing frames problem.

**Comment by MartyG-RealSense** [comment]
The warning **Resource temporarily unavailable**, when generating continuously like in your provided image, can indicate that there is a serious communication problem between the camera and computer, 

Do the warnings reduce if you add **initial_reset:=true** to the roslaunch instruction to reset the camera at launch if you are not using this instruction already?

**Comment by ricber** [comment]
No, the parameter **initial_reset** did not reduce the number of warnings nor the missing frames. I emphasize that most of the warnings appear at the starting of the camera. Then I get a warning once in a while, like every some minutes.

**Comment by MartyG-RealSense** [comment]
If **control_transfer returned** warnings only occur occasionally after launch (such as once every one or two minutes) then they can safely be ignored.

 I note that you are using a computer with an **i7-4790S** processor.  Although it is an i7 processor, the first number after the 'i' number can be more important as it indicates the age of the processor technology in terms of its architecture **generation**.  The '4' in 4790S shows that it is 4th Generation (codename Haswell), which dates to around 2014-2015.  

https://www.intel.com/content/www/us/en/products/sku/80808/intel-core-i74790s-processor-8m-cache-up-to-4-00-ghz/specifications.html

Although RealSense 400 Series cameras can work with any Intel processor, the processor in this particular computer may be having difficulty processing the volume of camera data being generated by the launch due to the age of the processor's technology.

**Comment by MartyG-RealSense** [comment]
Hi @ricber  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
