### ISSUE TITLE
modify the resolution but there is no change in rqt_image_viewer

### ISSUE THREAD

**Issue by NKdryer** [realsenseai/realsense-ros#2490]
Hello, I published the topics of realsense by running `roslaunch realsense2_camera rs_camera.launch color_width:=462 color_height:=260`, then I open rqt_image_viewer but the image has no difference between `roslaunch realsense2_camera rs_camera.launch`, Do I miss some operations? Or how can I know whether the resolution has been modified? Thank you in advance.

**Comment by MartyG-RealSense** [comment]
Hi @NKdryer  From RealSense ROS wrapper version 2.2.22 onwards, three factors - stream width, height and **FPS** - should be provided in a custom stream configuration.  Otherwise, the launch will deem the custom configuration invalid and apply the default stream profile of the particular RealSense camera model being used.

The resolution should also be one that is supported by RealSense cameras.  Please try launching with 640x480 color resolution and 30 FPS using the roslaunch instruction below.

**roslaunch realsense2_camera rs_camera.launch color_width:=640 color_height:=480 color_fps:=30**

The resolution and FPS that is being applied by the launch can be found near the bottom of the roslaunch log in the ROS terminal, just above the line **RealSense Node is Up!**

**Comment by NKdryer** [comment]
Thanks for the explanation. So whether 346 * 260 is a resolution supported by RealSense camera? If not, how can I display the images or adjust the collected images to this resolution.

**Comment by MartyG-RealSense** [comment]
The data sheet document for the RealSense 400 Series cameras provides the following information.

https://dev.intelrealsense.com/docs/intel-realsense-d400-series-product-family-datasheet

An RGB color resolution supported by all 400 Series camera models is 424x240.

The D415, D435, D445i and D435f models support 320x240 and 320x180 RGB color resolutions.

The post-processing **decimation filter** provides the ability to reduce a selected resolution but it is not possible to define a precise custom resolution such as 346x260, unfortunately.

https://dev.intelrealsense.com/docs/post-processing-filters#decimation-filter

In ROS, the function **image_proc/resize** described in Section 4.4 of the link below may help you to adjust the image size.

http://wiki.ros.org/image_proc

**Comment by MartyG-RealSense** [comment]
Hi @NKdryer  Do you require further assistance with this case, please?  Thanks!

**Comment by NKdryer** [comment]
Thanks for your explanation about this problem! But I still had another problem when using this camera in Linux.

For those **.yaml** files that contain calibration results for the RealSense camera and another camera, is there exists an interface in the **.launch** file that lead the camera to read the **.yaml** file at the specified location in my computer?

**Comment by MartyG-RealSense** [comment]
Hi @NKdryer  Thanks very much for the update!

The link below may be a helpful reference for loading a .yaml file from the launch file.

https://roboticsbackend.com/ros-param-yaml-format/#In_a_launch_file

**Comment by NKdryer** [comment]
So if I load the **.yaml** file containing calibration results in the **.launch** file correctly, would the **calibrated** images be displayed when selecting RealSense image_raw in the visualization gui?

**Comment by MartyG-RealSense** [comment]
My understanding is that loading a .yaml file into the launch file should have the same effect on the image that it would if you had defined the parameters in the launch file directly.

**Comment by MartyG-RealSense** [comment]
Hi @NKdryer  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
