### ISSUE TITLE
Library / Wrapper version warning (Ubuntu 20.04 Ros2)

### ISSUE THREAD

**Issue by geoeo** [realsenseai/realsense-ros#2506]
I just cloned the ros2-beta branch and compiled the ros2 wrapper. However at startup I am getting the a warning: `running with a different librealsense version`

Built is v.2.50.0
Running is v.2.51.1

I checked the installed sdk version to be v.2.51.1 via `apt-cache policy librealsense2-dev`

I am wondering where this 2.50.0 version is comming from?

**Comment by MartyG-RealSense** [comment]
Hi @geoeo  This message would typically appear if the wrapper was compiled under one librealsense version and then the librealsense version was changed to another.  Each time that the librealsense version is changed, the ROS wrapper should be built again in order to avoid this warning.

An example of how the quoted warning could be produced is if 2.50.0 had been installed on an earlier occasion, and then the ROS wrapper was built.  If librealsense 2.51.1 was built after that without subsequently rebuilding the ROS wrapper then this warning could occur.

**Comment by geoeo** [comment]
So I know that a previous version of the wrapper has been built on that machine. But if I check out a the git repo again and build that repo for the first time how can that warning occur? 

Also just to be clear by wrapper I mean the realsense-ros repo

**Comment by MartyG-RealSense** [comment]
If you installed librealsense from packages then you can uninstall all librealsense-related packages on your computer with the instruction below to be sure that you do not have a previous version of librealsense already on the computer when performing a new install of it.

`dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge`

Once librealsense 2.51.1 has been built successfully from packages then the ros2_beta wrapper should be built secondly after that.

**Comment by geoeo** [comment]
I didnt install the sdk from packages. I always installed it via apt. This is what I dont understand. My current SDK version is 2.51. So why does the ROS2 wrapper complain that at some point a 2.50 was present, even if it currently isnt.

**Comment by geoeo** [comment]
The issue is that `ros-galactic-librealsense2` is still at version 2.50.0
