### ISSUE TITLE
Using realsense with long wire

### ISSUE THREAD

**Issue by Akumar201** [realsenseai/realsense-ros#2511]
Hi , I wanted to use the real-sense d435 with a long range wire or wireless without loosing any data. I tried using it with a longer wire and transfer error was coming continuously showing that there is loss of data, any suggestion how can I use this ?

**Comment by MartyG-RealSense** [comment]
Hi @Akumar201  When using a USB cable longer than 2 meters with RealSense cameras, performance can degrade or disconnections occur unless a high quality cable is used, due to the high volume of data bandwidth that the cameras can transmit through the cable.

Due to the high data bandwidth, using wireless wi-fi may result in less stability than a wired connection.

Using a cable containing **active repeater** components can help to stably extend cable length up to 20 meters.  Fiber optic cable or ethernet cable can also be used to extend up to 100 meters (though ethernet cables are slower than USB 3).

The company **Newnex** supply high quality active repeater cables and fiber optic cable that are validated for use with RealSense.

https://www.newnex.com/realsense-3d-camera-connectivity.php

https://www.youtube.com/watch?v=GLQgR1jT04M

Information about using ethernet networking with RealSense cameras can be found in Intel's white-paper guide on the subject at the link below.

https://dev.intelrealsense.com/docs/open-source-ethernet-networking-for-intel-realsense-depth-cameras

**Comment by Akumar201** [comment]
Thank you for your response. This issue has been resolved ,  I am closing this issue as it has been solved. If the problem persists, please comment and the issue will be reopened if appropriate.

**Comment by MartyG-RealSense** [comment]
Thanks very much @Akumar201 for the update!
