### ISSUE TITLE
camera intrinsics calibration of D455i in ros

### ISSUE THREAD

**Issue by bigfacecat553** [realsenseai/realsense-ros#2556]
enviroment:
      ubuntu 16.04
      ros kinetic
      camera D455i

Hi, guys. I have the problem about camera intrinsics calibration of D455i in ros.
I find the similar problem:
https://github.com/IntelRealSense/librealsense/issues/2666
https://github.com/IntelRealSense/realsense-ros/issues/508

It seems that the realsense in ros `roslaunch realsense2_camera rs_camera.launch filters:=pointcloud` does not need to have a yaml file in ros to improve the image quality.
https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy

I used to calibrate the intrinsics of Kinect V2 in ros, and I thought the process of realsense  may be similar in ros.
https://github.com/code-iai/iai_kinect2/tree/master/kinect2_calibration

I also find several tutorials of realsense, but all the work seems to be done through SDK or realsense software.
https://dev.intelrealsense.com/docs/calibration

So if I want to achieve the intrinsics calibration of realsense in ros and improve the image or depth quality, is that possible?
I want to use the realsense in my ros workspace.

I also heard that the calibration process has been completed when leaving the factory, is that true? So I needn't to do so?

**Comment by MartyG-RealSense** [comment]
Hi @bigfacecat553  Yes, RealSense cameras are calibrated in the factory but can become mis-calibrated and require re-calibrating with software tools.  This does not need to be performed in ROS, as the RealSense SDK provides two different methods for doing so - a depth-only calibration with **On-Chip Calibration** accessible from within the RealSense Viewer tool, or depth and RGB calibration with **Dynamic Calibration**.  With both tools you can save the calibration to the camera hardware.

**On-Chip Calibration**
https://dev.intelrealsense.com/docs/self-calibration-for-depth-cameras

**Dynamic Calibration**
https://www.intel.com/content/www/us/en/support/articles/000026723/emerging-technologies/intel-realsense-technology.html

See page 14 onwards of the user guide at the link above for Ubuntu 16.04 installation instructions.

*********

Events that could cause a mis-calibration include a physical shock (a hard knock, drop on the ground or severe vibration) or very high temperature.

On-Chip Calibration can calibrate both intrinsics and extrinsics, though as separate calibration operations and not both at the same time.

Dynamic Calibration only calibrates extrinsics, as it is extrinsics calibration that will have the most impact on depth quality.  There is an OEM version of the tool that calibrates both intrinsics and extrinsics and is supplied with Intel's $1500 USD 'OEM Calibration Target' product at the link below.  This product is targeted at engineering departments and manufacturing facilities, and most RealSense users will not require its intrinsic calibration feature.

https://store.intelrealsense.com/buy-intel-realsense-d400-cameras-calibration-target.html

********

If a camera has become mis-calibrated then instead of re-calibrating, you can instead try resetting the camera to its factory-new default calibration in the RealSense Viewer using the instructions at https://github.com/IntelRealSense/librealsense/issues/10182#issuecomment-1019854487

**Comment by bigfacecat553** [comment]
> Hi @bigfacecat553 Yes, RealSense cameras are calibrated in the factory but can become mis-calibrated and require re-calibrating with software tools. This does not need to be performed in ROS, as the RealSense SDK provides two different methods for doing so - a depth-only calibration with **On-Chip Calibration** accessible from within the RealSense Viewer tool, or depth and RGB calibration with **Dynamic Calibration**. With both tools you can save the calibration to the camera hardware.
> 
> **On-Chip Calibration** https://dev.intelrealsense.com/docs/self-calibration-for-depth-cameras
> 
> **Dynamic Calibration** https://www.intel.com/content/www/us/en/support/articles/000026723/emerging-technologies/intel-realsense-technology.html
> 
> See page 14 onwards of the user guide at the link above for Ubuntu 16.04 installation instructions.
> 
> Events that could cause a mis-calibration include a physical shock (a hard knock, drop on the ground or severe vibration) or very high temperature.
> 
> On-Chip Calibration can calibrate both intrinsics and extrinsics, though as separate calibration operations and not both at the same time.
> 
> Dynamic Calibration only calibrates extrinsics, as it is extrinsics calibration that will have the most impact on depth quality. There is an OEM version of the tool that calibrates both intrinsics and extrinsics and is supplied with Intel's $1500 USD 'OEM Calibration Target' product at the link below. This product is targeted at engineering departments and manufacturing facilities, and most RealSense users will not require its intrinsic calibration feature.
> 
> https://store.intelrealsense.com/buy-intel-realsense-d400-cameras-calibration-target.html
> 
> If a camera has become mis-calibrated then instead of re-calibrating, you can instead try resetting the camera to its factory-new default calibration in the RealSense Viewer using the instructions at [IntelRealSense/librealsense#10182 (comment)](https://github.com/IntelRealSense/librealsense/issues/10182#issuecomment-1019854487)

Thanks, I will have a try.
