### ISSUE TITLE
ROS Humble: binary instalation for arm64

### ISSUE THREAD

**Issue by renzobazan96** [realsenseai/realsense-ros#2559]
Hello,

I want to install the package over sudo apt install ros-humble-realsense2-camera. Currently there exist a package for amd64 but no for arm64: http://packages.ros.org/ros2/ubuntu/pool/main/r/ros-humble-realsense2-camera/
For now I can build it from source

Is there any plan when the binaries will be released?

**Comment by MartyG-RealSense** [comment]
Thanks very much @renzobazan96 for your question.  I will refer it to the RealSense ROS development team.

@Nir-Az  Could you advise @renzobazan96 about their Humble binary question above, please?  Thanks very much!

**Comment by Nir-Az** [comment]
Hi @renzobazan96,
The RS wrapper ROS2 package is dependent on the `librealsense2` SDK ROS2 package.
On latest wrapper release we had an issue with building the `librealsense2` package on ARM so I guess that's why the wrapper ARM package was not built.
Since then the `librealsense2` package had been fixed (see [here](https://repo.ros2.org/status_page/ros_humble_default.html?q=realsense)) and is waiting for ROS2 sync (the sync should be done any day now see [here](https://discourse.ros.org/t/preparing-for-humble-sync-and-patch-release-2022-11-21/28234) )

Hopefully the `realsense_camera` ARM build will be triggered automatically.
If not our next release is in a couple of weeks and we will make sure the ARM package will be there.
It's a matter of timing with the ROS2 sync, we missed the train by a day :)

Hope it helps..
Nir

**Comment by Nir-Az** [comment]
@renzobazan96 things happened faster than I imagined.
Please refresh your first link 😎

**Comment by renzobazan96** [comment]
I could install the packages today :). Thanks for the support

**Comment by MartyG-RealSense** [comment]
Thanks again @Nir-Az  :)

It's great to hear that you were successful, @renzobazan96 - thanks very much for the update!

**Comment by AndreV84** [comment]
so ros2 node supports humble release ? Right? @MartyG-RealSense

**Comment by AndreV84** [comment]
what is the solution for arm64 focal ros humble implementation for d400? if any?

**Comment by MartyG-RealSense** [comment]
Hi @AndreV84  The RealSense ROS2 wrapper supports Humble but for **Ubuntu 22.04 Jammy** rather than 20.04 Focal.

![image](https://user-images.githubusercontent.com/41145062/207457155-19797eb4-e4be-407c-b48e-ca92eb0a239c.png)

Building the wrapper for Humble on arm64 has had some problems though with the buildfarm, as described at https://github.com/IntelRealSense/librealsense/issues/10439#issuecomment-1280318586 and the link below.

https://discourse.ros.org/t/humble-build-farm-job-on-arm-fails-on-first-release/27413
