### ISSUE TITLE
ROS2 Dynamic Reconfigure Image Transport

### ISSUE THREAD

**Issue by xkaraman** [realsenseai/realsense-ros#2565]
Currently only `base` topic parameters can be configured.

Image transport plugins like `compressed`, `compressedDepth` are not available for reconfigure from `ros2 run rqt_reconfigure rqt_reconfigure`
![image](https://user-images.githubusercontent.com/22965395/204330699-e93699e2-a54f-4ac3-8d52-1145c290545c.png)

Trying to configure them manually with
`ros2 param set /camera/camera .aligned_depth_to_color.image_raw.compressed.format png` results to an error of

`Setting parameter failed: parameter '.aligned_depth_to_color.image_raw.compressed.format' cannot be set because it was not declared`

**Comment by MartyG-RealSense** [comment]
Hi @xkaraman  Your **ros2 param set** instruction looks unusual to me in regard to how it has full-stop marks instead of / symbols.  

`ros2 param set /camera/camera .aligned_depth_to_color.image_raw.compressed.format png`

My expectation would be that the instruction would look more like this:

`ros2 param set /camera/aligned_depth_to_color/image_raw/compressed`

As `aligned` topics would only be published if **align_depth** was enabled and they are listed in the rqt_reconfigure window, it seems that you have enabled align_depth in your launch but are indeed missing the compressed topics.

Are the compressed topics listed outside of the rqt_reconfigure interface if you use the command `ros2 topic list` to list all currently available topics?

**Comment by xkaraman** [comment]
Yeah `.param` it's seems unusual to me coming from ros1 but apparently that's how it's done in ros2. Also `ros2 param set node_name param_name value` is the way to go for setting them in ROS2.

Yes `aligned_depth` was set to true and topics where visible and able to visualize through rviz

**Comment by MartyG-RealSense** [comment]
@xkaraman  I will highlight your issue to one of my Intel RealSense colleagues.  Thanks very much for your patience!

@Nir-Az  In this issue, @xkaraman has compressed topics listed in ROS2 when using **ros2 topic list** but cannot interact with those compressed topics in the rqt_reconfigure window during runtime after launch or configure them with `ros2 param set` instructions.  Is that normal for ROS2 please?  Thanks!

![image](https://user-images.githubusercontent.com/41145062/205126100-a593e6aa-8365-46ea-81a8-92b01e2251aa.png)

**Comment by Nir-Az** [comment]
Hi,
I am not familiar with image transport parameters, but are you sure you see the new compressed topic in the topic list?

**Comment by xkaraman** [comment]
Yes @Nir-Az, i have also confirmed through `ros2 topic echo /camera/color/image_raw/compressed --once --no-arr` that yields:
```
header:
  stamp:
    sec: 1670235648
    nanosec: 56710912
  frame_id: camera_color_optical_frame
format: rgb8; jpeg compressed bgr8
data: '<sequence type: uint8, length: 285846>'
---
```

I would like to also report that when i open `ros2 run rqt_reconfigure rqt_reconfigure` and navigate to `camera/camera` paremters, when i scroll down to see the pameters, `colorizer.stream_format_filter` is the last one i can see before `rqt` crashing with an expception of `[ros2run]: Floating point exception`.

**Comment by Nir-Az** [comment]
OK, we will need to investigate those 2 issues on our side
Thanks

**Comment by xkaraman** [comment]
I noticed that if i remove `namespace` argument when launching the node from ROS2 launch file `rs_launch.py` params do NOT have the `.` in from of the param that has been odd to me as well as @MartyG-RealSense. Maybe i should open a new issue for it?
Still no compressed parameters are shown though.

**Comment by MartyG-RealSense** [comment]
Hi @xkaraman  Let's await the outcome of the investigation by @Nir-Az before creating another issue.  Thanks!

**Comment by xkaraman** [comment]
Any news on this @MartyG-RealSense ?

**Comment by MartyG-RealSense** [comment]
Hi @xkaraman  I will follow up with @Nir-Az about this issue.  Thanks very much for your patience.

**Comment by MartyG-RealSense** [comment]
Hi @xkaraman  I checked with the RealSense ROS team about this issue.  They advised that it's in their pipeline but not a main focus at the moment and they will investigate it once they are able to get to it.  Thanks very much for your patience.

**Comment by MartyG-RealSense** [comment]
Hi @xkaraman  Bearing in mind the information in the comment above, do you require further assistance with this case please?  Thanks!

**Comment by xkaraman** [comment]
Ok thanks for the update @MartyG-RealSense. Personally i don't need further assistance but maybe the issue must remain open until a fix is proposed?

**Comment by MartyG-RealSense** [comment]
I put an **Enhancement** label on the case to signify to keep it open whilst the feature request remains active.

**Comment by SamerKhshiboun** [comment]
Hi @xkaraman 

My name is Samer and I'm a developer in the RealSense SW Team.

Regarding the scroll down issue in the rqt_reconfigure and that the last parameter you see is colorizer.stream_format_filter:
The problem is that the next paramter that rqt_reconfigure trying to pull and view, is "colorizer.stream_index_filter" which defined as an INT value in a range of [-1, INT_MAX].
LibRealSense is returning this range, but somehow it overflows to be INT_MAX + 1, which rqt_reconfigure is not accepting as it limited to INT_MAX(32bit) and overflows this number to be negative number.

This is the message I get from rqt_reconfigure:
`[WARN] [1679264563.906326759] [rqt_reconfigure]: Failed to retrieve parameters from node: argument 2 overflowed: value must be in the range -2147483648 to 2147483647
`
I see there are two problems:

1- in the rqt_reconfigure application which doesn't support big number (bigger than 32 bits) and also doesn't know to skip these errors. (Reference: https://github.com/ros-visualization/rqt_reconfigure/issues/107)

2- in our ros wrapper, which we should prevent these cases in general (need to figure out why the value is increased by 1 while converting from float to double)
![image](https://user-images.githubusercontent.com/99127997/226213648-4cd510fa-c918-48df-bf16-39f510d8f578.png)

This answer can provide useful information: https://stackoverflow.com/questions/23420783/convert-int-max-to-float-and-then-back-to-integer

I will continue investigating this issue and will look for a proper way to define the parameter range.
Regarding the other issue, I need to look more deeper in order to understand it.

Will update asap.

**Comment by xkaraman** [comment]
Thanks @SamerKhshiboun for the update! If you have any other updates or want me to help somehow, you are more than welcome to ask! :)

**Comment by johannesWen** [comment]
Hi, @SamerKhshiboun 
Do you have an update concerning the integer overflow?

**Comment by MartyG-RealSense** [comment]
Hi @SamerKhshiboun  Could you kindly assist with the question of @johannesWen above, please?  Thanks!

**Comment by SamerKhshiboun** [comment]
Hi @MartyG-RealSense , @johannesWen 
We opened a PR on librealsense repo
https://github.com/IntelRealSense/librealsense/pull/11858

When this PR will be merged, you can use the latest code of librealsense (development branch) and recompile your librealsense library, and then when using rqt_reconfigure the problem will disappear.

Also, this fix will be included in the future releases of Librealsense

Thanks,
Samer

**Comment by MartyG-RealSense** [comment]
Hi @xkaraman and @johannesWen  As PR https://github.com/IntelRealSense/librealsense/pull/11858 got merged into the librealsense SDK on May 31 2023, do you require further assistance with this case please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to merging of a fix into the librealsense SDK.
