### ISSUE TITLE
Could you add a ros parameter for odom_frame in base_realsense_node.cpp?

### ISSUE THREAD

**Issue by Yuchen966** [realsenseai/realsense-ros#2566]
In base_realsense_node.cpp, there are two lines:

```
msg.header.frame_id = DEFAULT_ODOM_FRAME_ID;
...
odom_msg.header.frame_id = DEFAULT_ODOM_FRAME_ID;
```

`DEFAULT_ODOM_FRAME_ID` is defined in constant.h and could not be modified (if I don't want to modify this package and only tend to modify parameter files in my custom package). Is there a reason why it is not defined as a ros parameter?

**Comment by MartyG-RealSense** [comment]
Hi @Yuchen966  The documentation of the RealSense ROS wrapper states "odom_frame_id defines the origin coordinate system in ROS convention (X-Forward, Y-Left, Z-Up)".  

This is presumably something that should not be modified in order to maintain the RealSense ROS wrapper's compatibility with ROS convention.  Because RealSense uses a different axis system where Z is forward and Y is up, the wrapper needs to be able to convert to the default ROS axes.

**Comment by MartyG-RealSense** [comment]
Hi @Yuchen966  Do you require further assistance with this case, please?  Thanks!
