### ISSUE TITLE
get RGB Image and depth array from bag file

### ISSUE THREAD

**Issue by Xue21** [realsenseai/realsense-ros#2624]
How to use the tools in ros1 to get RGB images and depth arrays from bag files

**Comment by MartyG-RealSense** [comment]
Hi @Xue21  You could possibly extract stereo images from a bag file with the ROS bag tool **extract_stereo_images**.

http://wiki.ros.org/bag_tools#extract_stereo_images

If you need to convert the bag to a file that stores data as an array such as an **.npy** instead of an image file then googling for the search term **ros convert bag to npy** returns search results such as the rosbag to npy conversion script at the link below.

https://github.com/RobustFieldAutonomyLab/lidar_super_resolution/blob/master/scripts/rosbag2npy.py

There is a ROS tutorial at the link below for extracting images from a bag as jpeg files with the **extract_images** command.

http://wiki.ros.org/rosbag/Tutorials/Exporting%20image%20and%20video%20data

**Comment by MartyG-RealSense** [comment]
Hi @Xue21  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
