### ISSUE TITLE
[D435i] No RealSense devices found!

### ISSUE THREAD

**Issue by jesusramondovale** [realsenseai/realsense-ros#2694]
Hello! I'm experiencing some troubles while working on a SBC DEBIX Model A (2GB RAM) with Ubuntu Server 20.04 and ROS2-Foxy installed.   

#### I've installed the RealSense SDK (*sudo apt install ros-foxy-librealsense2*) and the ROS Wrapper (*sudo apt install ros-foxy-realsense2*)

Everything is fine until I run the camera node (*ros2 run realsense2_camera realsense2_camera_node*) and says there is no Realsense device connected:

`debix@DEBIX25:~$ ros2 run realsense2_camera realsense2_camera_node
[INFO] [1681394309.305800446] [camera]: RealSense ROS v4.51.1
[INFO] [1681394309.306101828] [camera]: Built with LibRealSense v2.51.1
[INFO] [1681394309.306168079] [camera]: Running with LibRealSense v2.51.1
[WARN] [1681394309.322417799] [camera]: No RealSense devices were found!
 13/04 13:58:29,322 WARNING [281473125865888] (ds5-factory.cpp:1152) DS5 group_devices is empty.`

Camera is correctly connected via USB as I tried doing 'lsusb' and it appears. But doing *'rs-enumerate-devices'* shows there are no cameras connected. 

EDIT: tried doing exactly the same on an Raspi 4 with Ubuntu 22.04 & ROS2-Humble and everything worked fine

**Comment by MartyG-RealSense** [comment]
Hi @jesusramondovale  Please first remove all RealSense related packages from your SBC DEBIX Model A with the command below in the Ubuntu terminal.

`dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge`

Then try the installation command below to install librealsense 2.51.1 and ROS2 wrapper 4.51.1 together from packages.

`sudo apt install ros-foxy-realsense2-camera`

Afterwards, do not input any of the apt-get installation instructions that you have listed above.  Using only **sudo apt install ros-foxy-realsense2-camera** should be sufficient.

**Comment by jesusramondovale** [comment]
Thank you for your response! 
I tried doing what you said, I did the two commands without any problem but then when I run the node nothing changed :(

I tried unplugging and plugging the camera while node running and showed me this: 

`[WARN] [1681450892.858532845] [camera]: No RealSense devices were found! 14/04 05:41:32,858 WARNING [281472717822368] (ds5-factory.cpp:1152) DS5 group_devices is empty.
[WARN] [1681450899.012981871] [camera]: No RealSense devices were found!
 14/04 05:41:39,012 WARNING [281472717822368] (ds5-factory.cpp:1152) DS5 group_devices is empty.
 14/04 05:41:45,154 ERROR [281472717822368] (librealsense-exception.h:52) get_dev_capabilities: Cannot open '/dev/video6 Last Error: Device or resource busy
 14/04 05:41:45,156 ERROR [281472717822368] (librealsense-exception.h:52) Cannot identify '/dev/video4 Last Error: No such file or directory
 14/04 05:41:45,156 ERROR [281472717822368] (librealsense-exception.h:52) Cannot identify '/dev/video2 Last Error: No such file or directory
 14/04 05:41:45,157 ERROR [281472717822368] (backend-v4l2.cpp:639) uvc meta-node with no video streaming node encountered: id- /dev/video3
vid- 8086
pid- b3a
mi- 0
unique_id- 2-1.3-4
path- /sys/devices/platform/soc@0/32f10108.usb/38200000.dwc3/xhci-hcd.0.auto/usb2/2-1/2-1.3/2-1.3:1.0/video4linux/video3
susb specification- 320
 14/04 05:41:45,157 ERROR [281472717822368] (backend-v4l2.cpp:639) uvc meta-node with no video streaming node encountered: id- /dev/video5
vid- 8086
pid- b3a
mi- 0
unique_id- 2-1.3-4
path- /sys/devices/platform/soc@0/32f10108.usb/38200000.dwc3/xhci-hcd.0.auto/usb2/2-1/2-1.3/2-1.3:1.0/video4linux/video5
susb specification- 320
 14/04 05:41:45,157 ERROR [281472717822368] (backend-v4l2.cpp:639) uvc meta-node with no video streaming node encountered: id- /dev/video7
vid- 8086
pid- b3a
mi- 3
unique_id- 2-1.3-4
path- /sys/devices/platform/soc@0/32f10108.usb/38200000.dwc3/xhci-hcd.0.auto/usb2/2-1/2-1.3/2-1.3:1.3/video4linux/video7
susb specification- 320
[WARN] [1681450905.910977780] [camera]: No RealSense devices were found!`


*lsusb* shows the camera connected: 

*`debix@DEBIX25:/$ lsusb
Bus 002 Device 007: ID 8086:0b3a Intel Corp. 
Bus 002 Device 002: ID 0bda:0411 Realtek Semiconductor Corp. USB3.2 Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0bda:5411 Realtek Semiconductor Corp. USB2.1 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`* 

*rs-enumerate-devices* shows no devices: 
`No device detected. Is it plugged in?`

PD: my DEBIX is running with Linux Kernel 5.10.72

Do you know what can I try? Thank you!

**Comment by MartyG-RealSense** [comment]
The RealSense SDK does not have support for kernel 5.10, unfortunately.  It supports 5.11, 5.13 and 5.15.  The SDK can work with unsupported kernels but there may be unpredictable consequences in regards to stability.

We know that there is not a problem with the camera or its firmware driver because it works correctly on your Raspberry Pi.

Your board's CPU is an i.MX 8M Plus quad-core ARM Cortex-A53.   That configuration is exotic enough to merit trying to install librealsense from source code with CMake instead of packages with the **-DFORCE_RSUSB_BACKEND=true** installation method.  RSUSB bypasses the kernel and so is not dependent on Linux versions or kernel versions and the kernel does not need to be patched.

I would recommend using the RealSense package uninstall instruction again to clear out the previous SDK and ROS wrapper installation, and then trying to install librealsense on its own from source code with the RSUSB method to see if the camera can be detected.  Then we can move on to attempting to install the ROS wrapper afterwards if the camera is detected by librealsense.

As an RSUSB build is more complex than a package installation, it may be worth trying the simplest installation approach first, described at the link below.

https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md

**Comment by MartyG-RealSense** [comment]
Hi @jesusramondovale   Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
