### ISSUE TITLE
realsense2_camera not building because it cannot find librealsense2

### ISSUE THREAD

**Issue by Brac24** [realsenseai/realsense-ros#2696]
I built librealsense2 on Ubuntu 18 for Jetson Nano from source because I want to use the native backend. I also have to build realsense2_camera for ROS 2 Foxy. But I get the following error when it tries to build realsense2_camera
![image](https://user-images.githubusercontent.com/4980091/232278835-2fd23bb7-0bfc-4aae-886e-9d58297d50eb.png)
There is a similar issue here unrelated to realsense https://github.com/colcon/colcon-core/issues/76

Is there a special way I need to build librealsense2 to be used with ROS 2? I can colcon build librealsense2 and then realsense2_camera will also build but I don't think that will build librealsense2 with native backend which I would like. Do I have to colcon build librealsense2 to be able to build realsense2_camera?

**Comment by MartyG-RealSense** [comment]
Hi @Brac24  If you want to use the native backend then you will need to build librealsense from source code or Jetson packages.  

https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md#4-install-with-debian-packages

That will mean building the ROS2 wrapper from source code afterwards.

The wrapper documentation recommends that Foxy is used with Ubuntu 20.04 rather than 18.04.  

![image](https://user-images.githubusercontent.com/41145062/232306880-4c2fc558-7ad5-4f5d-8028-5b10a0e3bbbf.png)

For 18.04, ROS2 Dashing or Eloquent will be an appropriate choice to use with the **ros2-development** wrapper.

![image](https://user-images.githubusercontent.com/41145062/232307210-dc717d67-2f7b-4464-bbb0-7477d4cc2eb6.png)

**Comment by Brac24** [comment]
Yes I do understand but I am trying to use ROS 2 Foxy. I believe I would get the same error even if I choose a different ROS distribution. 
My question is why does the ROS 2 wrapper search for librealsense2 within the ROS2 workspace instead of the linux library paths such as /usr/local/lib or something?

**Comment by MartyG-RealSense** [comment]
I see that your colcon build command is **colcon build --packages-select** and then a list of packages.  There is no need to specify packages when building the ROS wrapper from source code.  The build command is simply **colcon build**

https://github.com/IntelRealSense/realsense-ros#option-2-install-from-source

It looks as though the installation is looking for packages in the catkin workspace because of your --packages-select command, which is not required.

**Comment by MartyG-RealSense** [comment]
Hi @Brac24  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
