### ISSUE TITLE
Can D435i filter out 850nm infrared light?

### ISSUE THREAD

**Issue by kao-yang** [realsenseai/realsense-ros#2703]
I am using two camera:Realsense D435i which closed emitter and Orbbec Gemini2 which emitting infrared structured light.
When I turn on two cameras,D435i's image effected by Gemini2's infrared structured light.
![effict](https://user-images.githubusercontent.com/57090523/233526739-77fb820f-a088-45b5-9928-de3c9ceeb11d.png)
But after a few seconds, the infrared structured light in D435i's image disappear.
![no_effect](https://user-images.githubusercontent.com/57090523/233526662-4023dec6-7b17-4428-8b35-88e9535b5d9e.png)
It seems that D435i can filter infrared structured light from Gemini2.Is that right?How should I set parameters to filter infrared structured light from Gemini2 at 850nm?

**Comment by MartyG-RealSense** [comment]
Hi @kao-yang  If a RealSense camera's IR emitter is disabled and its projected dot pattern is removed, the camera can still see infrared patterns projected by other cameras or by external projectors.  The IR emitter of RealSense cameras also operates in the 850 nm range.  

The D435i camera model is not equipped with an infrared-blocking filter on its sensors.  It can see all light frequencies in the visible to near-infrared range.

I note that in your RealSense Viewer you have auto-exposure disabled.  Does the structured light from the Gemini2 still appear for a few seconds if auto-exposure is enabled, please?

If you are sensing at close range (between 7 cm and 50 cm) then the **D405** close-range camera model would not be able to see an external infrared pattern as its sensors are equipped with an IR-blocking **IR Cut** filter so that it cannot see frequencies in the 850 nm range, and so cannot see a projected IR pattern.

Purchasing and fitting an external **short pass** filter over the lenses on the outside of the D435i camera could help to block IR frequencies from other cameras, as described in Intel's guide to using optical filters with 400 Series cameras.

https://dev.intelrealsense.com/docs/optical-filters-for-intel-realsense-depth-cameras-d400

**Comment by kao-yang** [comment]
> 
if auto-exposure is enabled, the structured light from the Gemini2 still appear for a few seconds。What puzzles me is that since D435i can't filter out 850nm infrared light, why does the structural light disappear from the image after a few seconds?

**Comment by MartyG-RealSense** [comment]
Is the Gemini2 camera's projection disabling itself?

**Comment by kao-yang** [comment]
> Is the Gemini2 camera's projection disabling itself?

No,Gemini2 camera's projection is always enable.Will D435f slove this problem?Can D435f filter the ir light at 850nm?

**Comment by MartyG-RealSense** [comment]
D435f does not block infrared light.  Its filter blocks **visible** light frequencies (the ones below 850 nm) and allows infrared frequencies, so the Gemini2's projection would still be visible.  D405 can block infrared, but it is a short-range camera with an ideal depth sensing range of 7 cm to 50 cm (half a meter).

**Comment by kao-yang** [comment]
> 


https://user-images.githubusercontent.com/57090523/233601962-7965d98a-aba9-4a5e-9209-362f2a0e2718.mp4

This video shows that the the structured light from the Gemini2 disappeared in the begin.But in the end of the video,with the rotation of cameras,the structured light appear again,and disappear again in a few seconds.

**Comment by MartyG-RealSense** [comment]
I examined your case carefully but without using filter products on the RealSense lenses to block infrared frequencies from being seen, the best option may be to compensate for the loss of depth detail when the structured light pattern is active.  Two ways of doing this are:

1.  Set the **Laser Power** option in Steeo Module > Controls to its maximum value of '360'.

2.  Expand open the **Spatial Filter** post-processing filter and set its **Holes filling mode** drop-down menu to 'Unlimited' so that it attempts to automatically fill in the gaps in the depth image caused by the structured light.

![image](https://user-images.githubusercontent.com/41145062/233622200-084031fa-c784-4463-8d6f-a48d810c4d4a.png)

I cannot comment on why the Gemini2 camera may be behaving in this manner as I can only advise on RealSense camera technology.

**Comment by kao-yang** [comment]
> I examined your case carefully but without using filter products on the RealSense lenses to block infrared frequencies from being seen, the best option may be to compensate for the loss of depth detail when the structured light pattern is active. Two ways of doing this are:
> 
> 1. Set the **Laser Power** option in Steeo Module > Controls to its maximum value of '360'.
> 2. Expand open the **Spatial Filter** post-processing filter and set its **Holes filling mode** drop-down menu to 'Unlimited' so that it attempts to automatically fill in the gaps in the depth image caused by the structured light.
> 
> ![image](https://user-images.githubusercontent.com/41145062/233622200-084031fa-c784-4463-8d6f-a48d810c4d4a.png)
> 
> I cannot comment on why the Gemini2 camera may be behaving in this manner as I can only advise on RealSense camera technology.

Thank you very much for your answer. I will try this setting.

**Comment by MartyG-RealSense** [comment]
Hi @kao-yang  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
