### ISSUE TITLE
Pointcloud scattered within a close distance

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2718]
How this video pointcloud didn't scattered in such a close distance? : [https://www.youtube.com/watch?v=iJWHRW7sZW8](url)
What realsense D455 function can I use to solve this problem?

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  Do you mean that your D455 pointcloud is breaking up when the camera is close to a surface, please?  If so then if the camera being used in the video is a D435 or D435i, it would be able to be placed closer to a surface without the cloud scattering because the D455 has a larger minimum distance (around 0.4 m / 40 cm, compared to 0.1 m / 10 cm on D435 / D435i.  A D455 therefore has to be placed further away from a surface when depth-sensing.

It is possible to reduce the minimum distance of a RealSense camera using an option called **Disparity Shift**.  I recommend setting it to a value of '100'.  This is because as the Disparity Shift value is increased, minimum distance reduces but the maximum observable depth range also reduces, removing some of the background.  '100' provides a good balance between placing the camera nearer to a surface and not losing too much of the background detail.

The RealSense ROS wrapper does not have a command to directly set Disparity Shift, but you can do so by setting the value in a **json** camera configuration file and loading that file into the wrapper during launch, as described at https://github.com/IntelRealSense/realsense-ros/issues/981#issuecomment-552177118

An alternative, cruder way to reduce minimum distance is to use a lower resolution.

**Comment by TapleFlib** [comment]
Got it ! thankyou !
