### ISSUE TITLE
Colour mismatching while extracting images from .bag file

### ISSUE THREAD

**Issue by SingCheng** [realsenseai/realsense-ros#2740]
Hi,

I am new to handling the bag file and record by D435i, I did use the [bag_to_images.py](https://gist.github.com/wngreene/835cda68ddd9c5416defce876a4d7dd9) to extract images from bag file.

However, when I review the images, I did find that the colour is mismatched

Original:
![image](https://github.com/IntelRealSense/realsense-ros/assets/50645313/43cf6b25-7227-47d6-bc45-994246a9ffa3)

After extracted:
![frame000000](https://github.com/IntelRealSense/realsense-ros/assets/50645313/99d9f63c-a81e-41c7-b15e-34897a404f97)

**For the code that I have used, `cv2_to_imgmsg` provided a few options for colour or pixel depth conversions, is any option suitable for us below?**

- mono8: CV_8UC1, grayscale image
- mono16: CV_16UC1, 16-bit grayscale image
- bgr8: CV_8UC3, color image with blue-green-red color order
- rgb8: CV_8UC3, color image with red-green-blue color order
- bgra8: CV_8UC4, BGR colour image with an alpha channel
- rgba8: CV_8UC4, RGB colour image with an alpha channel

Cheers

**Comment by MartyG-RealSense** [comment]
Hi @SingCheng  When using a RealSense RGB image with OpenCV, the **BGR8** format should be used for the RealSense RGB stream instead of RGB8 or the color will be reversed, producing effects like the one that you experienced.  This is because BGR8 is the default color space for OpenCV.

You can select the BGR8 format when recording RGB to a bag file with the RealSense Viewer tool.  

If you are recording in the RealSense ROS wrapper using **rosbag record** then the RGB stream of the wrapper will use RGB8 and the format cannot be changed in the wrapper.

**Comment by MartyG-RealSense** [comment]
Hi @SingCheng  Do you require further assistance with this case, please?  Thanks!

**Comment by SingCheng** [comment]
Hi @MartyG-RealSense, the problems have been solved, thank you.

**Comment by MartyG-RealSense** [comment]
You are very welcome, @SingCheng - thanks very much for the update!
