### ISSUE TITLE
 control_transfer returned error,error: Resource temporarily unavailable【D435i】

### ISSUE THREAD

**Issue by 10179013** [realsenseai/realsense-ros#2751]
D435i、ubutnu18.04
When I run：
roslaunch realsense2_camera rs_camera.launch \ unite_imu_method:="linear_interpolation" \ enable_gyro:=true \ enable_accel:=true
There is a warning:
`[ WARN] [1684978146.915808289]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 25/05 09:30:02,841 WARNING [139959447103232] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 25/05 09:30:02,892 ERROR [139958664611584] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 132
[ WARN] [1684978295.716470682]: Hardware Notification:Depth stream start failure,1.68498e+12,Error,Hardware Error`
How can I solve it?

**Comment by MartyG-RealSense** [comment]
If this **control_transfer returned** warning is generated in the log continuously then it indicates that there is a serious communication problem between the camera and computer.  

If it generates a small number of times during launch and stops, or only appears once or twice per minute after launch, then the warning can be safely ignored.

Please try adding **initial_reset:=true** to your roslaunch instruction to reset the camera at launch in order to see whether this reduces the warnings.

**Comment by MartyG-RealSense** [comment]
Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
