### ISSUE TITLE
SLAM with d435i

### ISSUE THREAD

**Issue by apotdar2023** [realsenseai/realsense-ros#2779]
Hi, I have followed the wiki to perform SLAM using the realsense d435i camera. However, I am unable to export a point cloud of the entire map. Publishing the/rtabmap/cloud_map yields several point clouds of the map. Is there a way to extract the whole thing as one point cloud. Also the points seem to be quite sparse. Is there a way to generate a dense point cloud similar to the one seen on th rviz tool.

**Comment by MartyG-RealSense** [comment]
Hi @apotdar2023  In the SLAM guide, a 2D map is built up using the instruction `rosrun map_server map_saver map:=/rtabmap/proj_map –f my_map_1` and then the pointcloud is saved with `rosrun pcl_ros pointcloud_to_pcd input:=/rtabmap/cloud_map` and it keeps saving pointclouds until Ctrl-C is used.

This suggests to me that the best way to get the whole pointcloud will be to wait until it has built up until a level of completion that you are satisifed with and then input the pointcloud saving command and use the first file saved.

In regard to altering pointcloud density, does it make a difference if you add **ordered_pc:=true** to your roslaunch instruction to publish an 'ordered' pointcloud instead of the default 'unordered' cloud?

**Comment by apotdar2023** [comment]
Thank you for your response. I'll try out your suggestion and update on the same.
Also, I would like to understand how the d435i camera conducts SLAM. Apart from the wiki, is there a script or some base code available? Would like to see how the IMU data is unpacked and used for SLAM.

**Comment by MartyG-RealSense** [comment]
The RealSense SDK (librealsense) does not have built-in SLAM support for the 400 Series stereo depth camera and the D435i SLAM guide is the only official guide available, so there is not a script or source code to examine, unfortunately.  

Using SLAM with RealSense typically involves interfacing the camera with a third-party SLAM solution such as ORB-SLAM, RTABMAP, OpenVSLAM or Kimera. 

At the link below, a RealSense user created an adaptation of Intel's D435i SLAM guide that added localization with RTABMAP and obtaining the relative position from a recorded pointcloud map.

https://shinkansan.github.io/2019-UGRP-DPoom/SLAM

**Comment by MartyG-RealSense** [comment]
Hi @apotdar2023  Do you require further assistance with this case, please?  Thanks!

**Comment by apotdar2023** [comment]
The above worked fine. Thank you for the support

**Comment by MartyG-RealSense** [comment]
You are very welcome.  Thanks very much for the update!
