### ISSUE TITLE
Depth Frame cap at 15fps when running with ros 2 (auto exposure error)

### ISSUE THREAD

**Issue by chijie1998** [realsenseai/realsense-ros#2780]
Hi, i am running D455 camera with Ros 2 Foxy in ubuntu 20.04 and I am having a strange frame drop for depth topic despite setting the depth module profile at 30 fps, i only can get 15 fps. There are a few error when launching the camera with rs_launch.py. I could get a 30 fps depth image stream when run with realsense-viewer without any problem or error.

![image](https://github.com/IntelRealSense/realsense-ros/assets/86032619/a0ad9364-eb92-4643-95eb-9dad24e27f1d)

Things that i have tried :
1. Gold factory reset
2. Downgrade firmware to the latest production firmware
3. Launch with 'depth_module.enable_auto_exposure':'true'
4. Comment out the {'name': 'depth_module.exposure.1',  and {'name': 'depth_module.exposure.2', line in rs_launch.py

Appreciate if you could help in resolving this issue. Thank you.

**Comment by MartyG-RealSense** [comment]
Hi @chijie1998  The red errors **auto_exposure_limit** and **auto_gain_limit** in your provided image are occurring because firmware version 5.14.0.0 is being used with librealsense SDK version 2.54.1.  Firmware 5.14.0.0 is incompatible with 2.54.1 due to changes made to its internal structure which mean that it must be used with the later SDK version 2.53.1.

The red errors should disappear if you downgrade your firmware version to the previous one, **5.13.0.50**.  The procedure for doing so in the RealSense Viewer tool is:

1.  Download the Viewer bin file for 5.13.0.50 to your computer from the link below.

https://dev.intelrealsense.com/docs/firmware-releases#d400-series-firmware-downloads

2.  Go to the **More** option near the top of the Viewer's options side-panel and select **Update Firmware** from its drop-down menu.

3.  A file navigation box will pop up.  Navigate to the location on your computer where you downloaded the .bin file to and select the file.  The firmware downgrade should now automatically begin.

If you are unable to use the RealSense Viewer tool then the 5.13.0.50 bin file can also be used to perform the downgrade with the RealSense SDK tool **rs-fw-update**

**Comment by chijie1998** [comment]
@MartyG-RealSense Thank you for your quick response! I tried to update the firmware following your instruction but realsense-veiwer just crached halfway.
![image](https://github.com/IntelRealSense/realsense-ros/assets/86032619/0090e3f0-625f-4ff7-b1ac-a92c2c78063a)
![image](https://github.com/IntelRealSense/realsense-ros/assets/86032619/f55dda20-f338-4f83-970b-3b829f945ae7)

Is this the GUI issue? I tried multiple times and the program crashed when the progress bar is around 30% as shown on the figure on top.

**Comment by MartyG-RealSense** [comment]
At the 30% point in the process the camera performs a reset and disconnects in preparation for the second half of the firmware update process.  Sometimes though the camera is not re-detected after the reset and the update fails.

Are you performing the update using the official 1 meter RealSense USB cable or a longer USB cable of your own choice, please?

**Comment by chijie1998** [comment]
I see. Actually this is a D457 camera and it doesn't comes with any official realsense USB cable. I am using Newnex 1meter cable. Is this the problem? I still have the old official cable that comes with D435 that I bought few years back, will there be any issue if i use this cable instead?

**Comment by MartyG-RealSense** [comment]
Newnex produce high quality USB equipment and so a 1m Newnex USB cable should be fine for performing firmware update with.

Testing with an official cable from a D435 would also be fine as the official cable supplied with the camera can be swapped between any 400 Series camera model.

**Comment by chijie1998** [comment]
Hi, i have tried to update the firmware using the official able but realsense viewer still crashed at 30%. Do you have any idea how to solve this? or is there any workaround to update the firmware?

**Comment by chijie1998** [comment]
Hi, this seems to be an issue in ubuntu, i tried to use the window OS version of realsense viewer and it could update without any issue. The red errors for **auto_exposure_limit** and **auto_gain_limit** are gone now as shown below :
![image](https://github.com/IntelRealSense/realsense-ros/assets/86032619/68e0a0b8-627a-40ea-968f-6616e5a5db4b)

However, the depth frame rate is still cap on 15fps despite of the settings. Do you have any idea why it occurs? Personally I think it is related to the auto exposure settings because if I open the camera using realsense viewer and disable the auto exposure, the frame rate drops to 15fps. I am launching the ros2 node with the argument 'depth_module.enable_auto_exposure':'true' and i check the ros param it is set to true as well.

**Comment by MartyG-RealSense** [comment]
I recall that there was an issue on the D455 and D405 camera models with enable_auto_exposure earlier in 2023 in ROS2 where, if it was set to **off** then FPS dropped to 15.  The problem is described at https://github.com/IntelRealSense/realsense-ros/pull/2612

enable_auto_exposure is already set to true by default in the rs_launch.py launch file and so you should not need to use a launch instruction to set it to true.  So it is not clear why the FPS would be acting as though it was off (false).

https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/launch/rs_launch.py#L72

What is the FPS if you launch with ros2 run instead of ros2 launch, like this:

`ros2 run realsense2_camera realsense2_camera_node`

**Comment by chijie1998** [comment]
Thank you for your useful infromation. The issue is resolved. It seems like the problem is that I was using the realsense ros2 package from apt install. After removing it and manually build from the ros-development branch, I am able to get 30 fps for my depth frame. Thank you for you help.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  I'm pleased to hear that you achieved a solution.  Thanks very much for the update!
