### ISSUE TITLE
0 pointcloud depth on an object 

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2789]
Is it normal for depth to be 0 on an object that is not supposed to has 0 depth value? I use yolo to detect object and sometimes the center point of the object has 0 value.

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  A value of '0' on a surface could indicate that this particular area of the object's surface was not readable by the camera.  An example of such a surface could be one that is colored black, is reflective or has a strong light source shining on it.

**Comment by TapleFlib** [comment]
got it , thanks so much , do you know if there's realsense scientific research on why black colored object, reflective or has a strong light source shining on it isn't readable by the camera?

**Comment by MartyG-RealSense** [comment]
The problem with reading black surfaces is due to a general physics principle (not specific to RealSense) that dark grey or black absorbs light and so makes it more difficult for depth cameras to read depth information from such surfaces.  The darker the color shade, the more light that is absorbed and so the less depth detail that the camera can obtain.

Reflections create glare that can block out details of a surface.  The picture below demonstrates how fitting a **linear polarization filter** product over the lenses on the front of the camera can negate glare to provide a clear image.

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/0d6b48d7-47a1-435e-8a2f-0e1d5610e04c)

If a strong light source is cast on a surface then the area where the light is focused may just be a blob of plain bright white on an RGB image that can provide no useful information.  If the area is not readable then on the depth image it may appear as a plain black area that has no depth values in it.

**Comment by TapleFlib** [comment]
I got it, thanks so much !
