### ISSUE TITLE
Low quality image in RGB 

### ISSUE THREAD

**Issue by Camilochiang** [realsenseai/realsense-ros#2844]
I have notice that in general  when using a realsense camera (D415) in ROS1 , the colors of the RBG stream outside in full sun tend to be quite non saturated / low contrast. 
To solve this problem some options came to my mind:
- managing RGB exposure:
**question**: Is there any way to set the RGB exposure to auto in ROS1 / ROS2? or this is the default setting?
- managing RGB gain
**question**: Is there any way to set the RGB gain to auto in ROS1 / ROS2?  or this is the default setting
- Using HDR if available
 I have been looking for any HDR reference and only found [this](https://community.intel.com/t5/Items-with-no-label/RealSense-D435-color-image-capture-quality/m-p/609953?)
where is suggested that HDR was not implemented due the size/quality of the OV2740
I have also read the [HDR deep](https://dev.intelrealsense.com/docs/high-dynamic-range-with-stereoscopic-depth-cameras) guide and on it, it clearly says:
```
Note that HDR imaging for the visible light RGB sensor is outside the scope of this white-paper.
```
**question**: Is there any implementation of HDR for the color streams already available? If yes, was this one available in the ROS 1 wrapper?
- Activating histogram_equalization
This could be done in ROS1 with 'histogram_equalization_enabled` set to True
**question**: Is this the default value or need to be activated?

Thanks!

Edit:
regarding RGB exposure: it look that [it needed to be activated after launching](https://github.com/IntelRealSense/realsense-ros/issues/2598). Already documented and fixed in ROS2. I doubt that works by default in ROS1

**Comment by MartyG-RealSense** [comment]
Hi @Camilochiang  HDR for color has been previously asked about recently at https://github.com/IntelRealSense/librealsense/issues/11748 and advice is provided in response by my Intel RealSense colleagues.


***********

In the ROS2 launch file` rs_launch.py`, RGB auto-exposure is set to True by default.

https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/launch/rs_launch.py#L42

Depth auto-exposure is disabled by default because `depth_module.exposure.1` is auto-disabling the enable_auto_exposure feature of the depth stream.  There is not a similar manual exposure setting in the launch file for the RGB stream though, so its auto-exposure should remain True.

The ROS1 launch file **rs_camera.launch** has a similar manual exposure setting for depth which likely disables depth auto-exposure.

https://github.com/IntelRealSense/realsense-ros/blob/ros1-legacy/realsense2_camera/launch/rs_camera.launch#L140

There is not a parameter in the ROS1 launch file for RGB auto-exposure, though my assumption would be that it is True by default.  You can make sure though by using the rosparam launch file code below.

```
<rosparam>
 /camera/rgb_camera/enable_auto_exposure: true
</rosparam>
```

*********

Regarding your mention in your edit of RGB auto-exposure apparently being disabled in ROS2 at https://github.com/IntelRealSense/realsense-ros/issues/2598 - that was because the D405 camera model was being used in that case.  D405 does not have a separate RGB sensor and obtains RGB from the depth sensor.  It also uses the depth exposure for RGB as its RGB does not have its own separate exposure settings.  So when depth auto-exposure is disabled for depth, it is disabled for RGB too.  But this will not apply to other RealSense camera models such as D415. 

*********

Like with auto-exposure, auto-gain should be enabled by default until the gain value is manually changed and auto-gain is automatically disabled.
