### ISSUE TITLE
Rock-5b with jammy 22.04 Humble not working with realsenseWrapper v4.54.1

### ISSUE THREAD

**Issue by hemsinghb** [realsenseai/realsense-ros#2862]
Hello , 

I have Installed D455 camera on rock5b (librealsense v2.54.1 ) and it is working good. However, after installing Ros2 wrapper version v4.54.1, the node is not up, whereas while launching bringup.launch , the device is resetting and showing nothing on rviz.  Older vesion of librealsense are not compatible with jammy 22.04.3.  I need help to make the camera d455  work on ros2 navigation.  (My kernel version is 5.10.160).   

 thanks in advance.

**Comment by MartyG-RealSense** [comment]
Hi @hemsinghb  If you are using ROS2 and navigation, are you using the **bringup_launch.py** launch file at the link below, please?

https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/launch/bringup_launch.py

If so then that launch file on its own will not publish RealSense topics in ROS.  The RealSense ROS wrapper should be launched first in order to publish the topics and access them in RViz.  

`ros2 launch realsense2_camera rs_launch.py`

Typically, once the ROS wrapper has been launched first then the launch file of a second tool (such as bringup_launch.py) is run secondly afterwards. 

Have you launched rs_launch.py, and if so has its launch been able to complete successfully?

**Comment by hemsinghb** [comment]
Hi, MartyG,  Thanks for the response,

My bringup.launch includes realsense2_camera and  wrapper launch,

The output terminal message shows D455 found and ... Device resetting. ultimately "camera node is not UP". That is the problem. Any further advice please.

**Comment by MartyG-RealSense** [comment]
What method did you use to install the 4.54.1 ROS2 wrapper, please?

**Comment by hemsinghb** [comment]
Hi, 

I have used the following method to install wrapper v4.54.1 on rock5b:

mkdir -p ~/ros2_ws/src
cd ~/ros2_ws/src/

git clone https://github.com/IntelRealSense/realsense-ros.git -b ros2-development
cd ~/ros2_ws

sudo apt-get install python3-rosdep -y
sudo rosdep init # "sudo rosdep init --include-eol-distros" for Eloquent and earlier
rosdep update # "sudo rosdep update --include-eol-distros" for Eloquent and earlier
rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y


 befor above wrapper installation , I have installed librealsense v2.54.1 using cmake .

Thanks, with regards, hem.

**Comment by MartyG-RealSense** [comment]
The instruction list exactly matches the documentation, so that looks fine.  Can you confirm that you performed the final instructions in the procedure?

**Build**
`colcon build`

**Source environment**
```
ROS_DISTRO=<YOUR_SYSTEM_ROS_DISTRO>  # set your ROS_DISTRO: iron, humble
source /opt/ros/$ROS_DISTRO/setup.bash
cd ~/ros2_ws
. install/local_setup.bash
```

**Comment by hemsinghb** [comment]
Yes please did colcon build and the following source also

$ source /opt/ros/humble/setup.bash
$ cd ~/ros2_ws
$ . install/local_setup.bash

**Comment by MartyG-RealSense** [comment]
We could try a package build of the ROS2 wrapper instead of a source code build to see whether it makes a difference.

1.  Remove the source code build of the wrapper by completely deleting the **/ros2_ws/src** catkin workspace folder.

2.  Configure the Ubuntu repositories using the instructions at the link below.

http://wiki.ros.org/Installation/Ubuntu/Sources

3.  Install the ROS wrapper for Humble from packages with the instruction below.

`sudo apt install ros-humble-realsense2-*`

**Comment by MartyG-RealSense** [comment]
Hi @hemsinghb  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
