### ISSUE TITLE
I want to replace the depth at the edge with 0.0m

### ISSUE THREAD

**Issue by fig-shimooka** [realsenseai/realsense-ros#2881]
This image is my D435 depth frame.
Objects are always present in the D435's field of view.
The lower right corner of this image is that area.
I do not want to see this area.
What should I do?

![Screenshot from 2023-09-26 16-38-59](https://github.com/IntelRealSense/realsense-ros/assets/72783232/25f74201-eb7a-4408-a2f8-bea121f90353)

**Comment by MartyG-RealSense** [comment]
Hi @fig-shimooka  If the black area in the lower right corner is caused by an object obstructing the camera's field of view then you cannot see what is behind that obstructing object.   

You may be able to fill in the hole though using the neighboring depth information by applying the **Hole Filling** post-processing filter.  This filter can be found in the Viewer's options side panel under **Stereo Module > Post Processing**.  The filter can be enabled by left-clicking on the red icon beside it to turn it from red (Off) to blue (On).

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/ccc86ecd-7bd6-411e-9660-0c5cb037bea4)

If there is a close-range obstructing object in the camera's view then another approach would be to reduce the camera's minimum depth sensing distance so that it can generate depth for surfaces that are less than 10 cm from the camera lenses.  This could be done by changing the **Disparity Shift** option from its default of '0' to a value of '100'.  This option is under **Stereo Module > Advanced Controls > Depth Table**.

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/6c25b544-05da-4d83-bd23-a41565bc668d)

**Comment by MartyG-RealSense** [comment]
Hi @fig-shimooka  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
