### ISSUE TITLE
Pointcloud2 color texture Issue with D405 Camera and Ros2 driver

### ISSUE THREAD

**Issue by ndaley7** [realsenseai/realsense-ros#2886]
Good Afternoon,

I'm currently trying to utilize a D405 camera with the Ros2 version of the node and I'm experiencing an odd issue.

I am Starting up the camera using the exact commands from the documentation [here](https://github.com/IntelRealSense/realsense-ros/tree/ros2-development#start-camera-node):

```
ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 pointcloud.enable:=true
```
After booting up Rviz2, I add an image module to confirm the color image is working, and a pointcloud2 module to subscribe to the /points message.

As soon as I enable the Poincloud2 module, the Warning below writes out on the terminal:

```
[realsense2_camera_node-1] [WARN] [1696179054.430680446] [camera.camera]: No stream match for pointcloud chosen texture Process - Color
```
Has anyone experienced anything like this before?

I am attempting this on a Jetson Nano Orin 8Gb within a docker containing all of the relevant Ros Modules.

Please see screenshots below with terminal output/version info along with another screenshot showing the firmware on the camera:

![D405 Poincloud Issue](https://github.com/IntelRealSense/realsense-ros/assets/17780361/3020a219-e97b-4575-9e11-0b9fb78a00cb)

![D405 Information 128422272788](https://github.com/IntelRealSense/realsense-ros/assets/17780361/28186118-bbf9-4b97-824c-14e590792ea7)

**Comment by MartyG-RealSense** [comment]
Hi @ndaley7  ROS2 wrapper 4.54.1 is designed to be used with librealsense **2.54.1** rather than the 2.53.1 version you are using.  A ROS2 wrapper for 2.53.1 was not created.  It is important to match a particular ROS wrapper version as closely as possible with a specific librealsense version listed in that particular wrapper's release notes.

The camera firmware driver version that should be used with 2.53.1 is **5.14.0.0** rather than 5.15.1.0 (which is designed for use with the current latest 2.54.2 version of librealsense).  The appropriate firmware match for librealsense 2.54.1 is **5.15.0.2**.

The **No stream match for pointcloud chosen texture Process - Color** warning is generated if the wrapper detects missing color image frames.

Does the message still occur if you reduce resolution to 848x480, please?

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=848x480x30 pointcloud.enable:=true`

**Comment by ndaley7** [comment]
> Hi @ndaley7 ROS2 wrapper 4.54.1 is designed to be used with librealsense **2.54.1** rather than the 2.53.1 version you are using. A ROS2 wrapper for 2.53.1 was not created. It is important to match a particular ROS wrapper version as closely as possible with a specific librealsense version listed in that particular wrapper's release notes.
> 
> The camera firmware driver version that should be used with 2.53.1 is **5.14.0.0** rather than 5.15.1.0 (which is designed for use with the current latest 2.54.2 version of librealsense). The appropriate firmware match for librealsense 2.54.1 is **5.15.0.2**.
> 
> The **No stream match for pointcloud chosen texture Process - Color** warning is generated if the wrapper detects missing color image frames.
> 
> Does the message still occur if you reduce resolution to 848x480, please?
> 
> `ros2 launch realsense2_camera rs_launch.py depth_module.profile:=848x480x30 pointcloud.enable:=true`

Oh I had no idea about the version mismatch.  As these were the versions set up on the provided docker, I went with it.  I'll give the new resolution a try!

**Comment by ndaley7** [comment]
> Hi @ndaley7 ROS2 wrapper 4.54.1 is designed to be used with librealsense **2.54.1** rather than the 2.53.1 version you are using. A ROS2 wrapper for 2.53.1 was not created. It is important to match a particular ROS wrapper version as closely as possible with a specific librealsense version listed in that particular wrapper's release notes.
> 
> The camera firmware driver version that should be used with 2.53.1 is **5.14.0.0** rather than 5.15.1.0 (which is designed for use with the current latest 2.54.2 version of librealsense). The appropriate firmware match for librealsense 2.54.1 is **5.15.0.2**.
> 
> The **No stream match for pointcloud chosen texture Process - Color** warning is generated if the wrapper detects missing color image frames.
> 
> Does the message still occur if you reduce resolution to 848x480, please?
> 
> `ros2 launch realsense2_camera rs_launch.py depth_module.profile:=848x480x30 pointcloud.enable:=true`

Upon running the camera, color and depth are good:

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/9364cc7a-97cb-4148-9d69-d5fb21aed8d7)

Unfortunately the same error comes back up upon activating the pointcloud:

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/f975b45d-2c6f-4a2e-a116-12365098ae64)

**Comment by MartyG-RealSense** [comment]
Given that the session is having difficulty obtaining color frames, is the pointcloud generated if you texture the pointcloud with the **infrared** image instead of the color image by adding **pointcloud.stream_filter:=1** to the end of your launch instruction?

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 pointcloud.enable:=true pointcloud.stream_filter:=1`

**Comment by ndaley7** [comment]
> ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 pointcloud.enable:=true pointcloud.stream_filter:=1

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/5a0e5983-c86d-43e8-9f6c-697f91184dee)
Unfortunately a similar result.

I think I'll also try the previous commands with a d435 that we have onhand to see if there is a difference when the camera model is changed.

**Comment by ndaley7** [comment]
A little more info to add around this issue.  I tried to run the same script with the d435 camera and received the same stream error as a result:

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/da5f51a9-4dd2-457b-a39a-22a09f6920f9)

**Comment by MartyG-RealSense** [comment]
What happens if Fixed Frame is set to **camera_link**

**Comment by ndaley7** [comment]
Unfortunately the same results, and same warning.

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/c603175c-b228-4175-ba3e-d02f4541ca08)

**Comment by MartyG-RealSense** [comment]
There used to be problems with using pointcloud or depth-color alignment on Jetson boards specifically.  When pointcloud or alignment was not enabled, performance was fine.  That problem has become very rare now but it is still possible for the occasional case to be reported.

Instead of enabling the pointcloud, could you try enabling alignment please?  If alignment does not work correctly then it could indicate that you are experiencing this now-rare problem.

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 align_depth.enable:=true`

**********

It appears that we also have not tested whether the pointcloud publishing problem occurs when launching with **ros2 run** instead of ros2 launch.

`ros2 run realsense2_camera realsense2_camera_node --ros-args -p pointcloud.enable:=true`

**Comment by MartyG-RealSense** [comment]
Hi @ndaley7  Do you require further assistance with this case, please?  Thanks!

**Comment by ndaley7** [comment]
> There used to be problems with using pointcloud or depth-color alignment on Jetson boards specifically. When pointcloud or alignment was not enabled, performance was fine. That problem has become very rare now but it is still possible for the occasional case to be reported.
> 
> Instead of enabling the pointcloud, could you try enabling alignment please? If alignment does not work correctly then it could indicate that you are experiencing this now-rare problem.
> 
> `ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 align_depth.enable:=true`
> 
> It appears that we also have not tested whether the pointcloud publishing problem occurs when launching with **ros2 run** instead of ros2 launch.
> 
> `ros2 run realsense2_camera realsense2_camera_node --ros-args -p pointcloud.enable:=true`

Sorry for the delay, I'll give these a try

**Comment by ndaley7** [comment]
> There used to be problems with using pointcloud or depth-color alignment on Jetson boards specifically. When pointcloud or alignment was not enabled, performance was fine. That problem has become very rare now but it is still possible for the occasional case to be reported.
> 
> Instead of enabling the pointcloud, could you try enabling alignment please? If alignment does not work correctly then it could indicate that you are experiencing this now-rare problem.
> 
> `ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 align_depth.enable:=true`
> 
> It appears that we also have not tested whether the pointcloud publishing problem occurs when launching with **ros2 run** instead of ros2 launch.
> 
> `ros2 run realsense2_camera realsense2_camera_node --ros-args -p pointcloud.enable:=true`

Regarding this, thankfully the alignment seems to be working:
`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 align_depth.enable:=true`
![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/c981847d-9cd8-44ef-84ba-b5a8719bc9ef)

Regarding the 2nd test:
`ros2 run realsense2_camera realsense2_camera_node --ros-args -p pointcloud.enable:=true`
The pointcloud is actually displaying now!  Unfortunately there is no color decode option to get the color mapped to the cloud (like RGB8):

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/54171abb-d434-4a4d-aeb6-c01c7ebf54a6)

**Comment by MartyG-RealSense** [comment]
Now that the pointcloud is publishing, does the **pointcloud.stream_filter** parameter (which can use the infrared stream as the pointcloud texture instead of the RGB stream) work if tried again?

`ros2 run realsense2_camera realsense2_camera_node --ros-args -p pointcloud.enable:=true -p pointcloud.stream_filter:=1`

**Comment by MartyG-RealSense** [comment]
Hi @ndaley7  Do you require further assistance with this case, please?  Thanks!

**Comment by ndaley7** [comment]
> Hi @ndaley7 Do you require further assistance with this case, please? Thanks!

I've been out for travel the last week, will give this a try.

**Comment by ndaley7** [comment]
> Now that the pointcloud is publishing, does the **pointcloud.stream_filter** parameter (which can use the infrared stream as the pointcloud texture instead of the RGB stream) work if tried again?
> 
> `ros2 run realsense2_camera realsense2_camera_node --ros-args -p pointcloud.enable:=true -p pointcloud.stream_filter:=1`

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/dde60aa1-ed2b-4c36-83fc-cf3a14f6be8b)
Similar error but this time for the depth stream.

**Comment by MartyG-RealSense** [comment]
If you are still using librealsense 2.53.1 then the firmware driver currently installed in your camera (5.15.1.0) is incorrect for that SDK.  The recommended firmware for 2.53.1 is **5.14.0.0**.  Using a firmware other than the recommended one for that particular librealsense version can result in errors.

**Comment by ndaley7** [comment]
> If you are still using librealsense 2.53.1 then the firmware driver currently installed in your camera (5.15.1.0) is incorrect for that SDK. The recommended firmware for 2.53.1 is **5.14.0.0**. Using a firmware other than the recommended one for that particular librealsense version can result in errors.

Hmm Okay that is good to know.... is there a procedure for downgrading the firmware?

**Comment by MartyG-RealSense** [comment]
The easiest method is to use the RealSense Viewer tool.

1.  Visit the link below and download the firmware file for 5.14.0.0 from it.

https://dev.intelrealsense.com/docs/firmware-releases#d400-series-firmware-downloads

2.  Open the RealSense Viewer, click on the **More** option near the top of the Viewer's options side-panel and select **Update Firmware** from its drop-down menu.

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/e27faf74-d302-4a3c-800e-bc6efac11ec4)

3.  Doing so causes a file selector to pop up.  Navigate to the location on your computer that you downloaded the firmware file to and select it.  The firmware downgrade should begin automatically.

**Comment by ndaley7** [comment]
> The easiest method is to use the RealSense Viewer tool.
> 
> 1. Visit the link below and download the firmware file for 5.14.0.0 from it.
> 
> https://dev.intelrealsense.com/docs/firmware-releases#d400-series-firmware-downloads
> 
> 2. Open the RealSense Viewer, click on the **More** option near the top of the Viewer's options side-panel and select **Update Firmware** from its drop-down menu.
> 
> ![image](https://user-images.githubusercontent.com/41145062/276964266-e27faf74-d302-4a3c-800e-bc6efac11ec4.png)
> 
> 3. Doing so causes a file selector to pop up.  Navigate to the location on your computer that you downloaded the firmware file to and select it.  The firmware downgrade should begin automatically.

I had no idea that the tool could be used to downgrade as well!  I'll give it a try and re-run some of the commands to see if the result is different

**Comment by ndaley7** [comment]
Sadly even with the matching firmware the same issue persists:

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/8afee471-fd7a-4b09-bee0-6e62b2063ab6)

**[WARN] [1697988608.741091483] [camera]: No stream match for pointcloud chosen texture Process - Depth**

**Comment by MartyG-RealSense** [comment]
What happens if you set Fixed Frames to `camera_link` again and this time also set the **Image** topic to `/camera/color/image_raw` instead of /depth/image_rect_raw so RViz resembles the picture below with the color image shown at the bottom of the RViz side-panel?

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/c10ff9ad-63a1-40c8-93b6-e662dd240c48)

**Comment by ndaley7** [comment]
Appears to be the same issue, I ran the prior command:

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=848x480x30 pointcloud.enable:=true`

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/7c7571b9-4ea4-4f30-8944-1cf4c3c38381)

**Comment by MartyG-RealSense** [comment]
The problem is likely to be that there are frames being dropped when the pointcloud is enabled (perhaps because of a dropped FPS rate), causing the **No stream match for pointcloud chosen process - Color** message.

I note that we have not yet raised the subject of **CUDA** in this discussion.  The librealsense SDK can be built with CUDA graphics acceleration support on Nvidia Jetson boards.  Because librealsense supports CUDA, so does the ROS wrapper.  This greatly reduces the CPU effort required to process pointclouds or alignment.  This is because the processing work is offloaded from the CPU onto the graphics GPU on the Jetson board.

Which installation method did you use to build librealsense, please?  If it was built using the Jetson packages then CUDA support is automatically included.

https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md#4-install-with-debian-packages

If librealsense was built from source code with CMake though then it is necessary to include the build flag **-DBUILD_WITH_CUDA=TRUE** in the CMake build instruction to add CUDA support.  For example:

`cmake .. -DBUILD_EXAMPLES=true -DCMAKE_BUILD_TYPE=release -DFORCE_RSUSB_BACKEND=true -DBUILD_WITH_CUDA=true && make -j$(($(nproc)-1)) && sudo make install`

**Comment by ndaley7** [comment]
> The problem is likely to be that there are frames being dropped when the pointcloud is enabled (perhaps because of a dropped FPS rate), causing the **No stream match for pointcloud chosen process - Color** message.
> 
> I note that we have not yet raised the subject of **CUDA** in this discussion. The librealsense SDK can be built with CUDA graphics acceleration support on Nvidia Jetson boards. Because librealsense supports CUDA, so does the ROS wrapper. This greatly reduces the CPU effort required to process pointclouds or alignment. This is because the processing work is offloaded from the CPU onto the graphics GPU on the Jetson board.
> 
> Which installation method did you use to build librealsense, please? If it was built using the Jetson packages then CUDA support is automatically included.
> 
> [IntelRealSense/librealsense@`master`/doc/installation_jetson.md#4-install-with-debian-packages](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md?rgh-link-date=2023-10-25T11%3A58%3A23Z#4-install-with-debian-packages)
> 
> If librealsense was built from source code with CMake though then it is necessary to include the build flag **-DBUILD_WITH_CUDA=TRUE** in the CMake build instruction to add CUDA support. For example:
> 
> `cmake .. -DBUILD_EXAMPLES=true -DCMAKE_BUILD_TYPE=release -DFORCE_RSUSB_BACKEND=false -DBUILD_WITH_CUDA=true && make -j$(($(nproc)-1)) && sudo make install`

The commands are being run on a docker container that came on a premade Jetson image by Nvidia..... I would have assumed that it was CUDA enabled given the hardware, but is there a way I can check that was the case?

**Comment by MartyG-RealSense** [comment]
Whilst a Jetson image created by Nvidia may have CUDA installed on it, it would not contain the librealsense CUDA component that adds support for RealSense pointcloud and depth-color alignment acceleration.  That can only be provided by installing librealsense from Jetson packages or building it from source code with the mentioned build flag.

The only way that you would likely know whether librealsense's CUDA support was enabled would be to launch the camera and then look at its CPU percentage usage in an Ubuntu system monitoring tool such as **htop** whilst the ROS session is active.  

With CUDA support enabled the CPU usage when generating a pointcloud might be no higher than 30%, whilst the absence of CUDA support could result in CPU usage of 70% or higher.

**Comment by ndaley7** [comment]
> Whilst a Jetson image created by Nvidia may have CUDA installed on it, it would not contain the librealsense CUDA component that adds support for RealSense pointcloud and depth-color alignment acceleration. That can only be provided by installing librealsense from Jetson packages or building it from source code with the mentioned build flag.
> 
> The only way that you would likely know whether librealsense's CUDA support was enabled would be to launch the camera and then look at its CPU percentage usage in an Ubuntu system monitoring tool such as **htop** whilst the ROS session is active.
> 
> With CUDA support enabled the CPU usage when generating a pointcloud might be no higher than 30%, whilst the absence of CUDA support could result in CPU usage of 70% or higher.

I'll give this a look when home and verify whether cuda is being used or not.

**Comment by ndaley7** [comment]
> Whilst a Jetson image created by Nvidia may have CUDA installed on it, it would not contain the librealsense CUDA component that adds support for RealSense pointcloud and depth-color alignment acceleration. That can only be provided by installing librealsense from Jetson packages or building it from source code with the mentioned build flag.
> 
> The only way that you would likely know whether librealsense's CUDA support was enabled would be to launch the camera and then look at its CPU percentage usage in an Ubuntu system monitoring tool such as **htop** whilst the ROS session is active.
> 
> With CUDA support enabled the CPU usage when generating a pointcloud might be no higher than 30%, whilst the absence of CUDA support could result in CPU usage of 70% or higher.

Good Afternoon,

After digging through the docker build files, it seems that the image does use a librealsense build with CUDA enabled:

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/361d91a9-04e0-4b10-b3da-5dd4019ac9c6)

**Comment by MartyG-RealSense** [comment]
Thank you for the information and the clarification that you installed librealsense using the JetsonHacks **installLibrealsense** build script.

Which Ubuntu and JetPack versions are you using?  The ideal combinations for using librealsense on Jetson would be JetPack 4.6 for Ubuntu 18.04 and JetPack 5.0.2 for Ubuntu 20.04.

**Comment by ndaley7** [comment]
> Thank you for the information and the clarification that you installed librealsense using the JetsonHacks **installLibrealsense** build script.
> 
> Which Ubuntu and JetPack versions are you using? The ideal combinations for using librealsense on Jetson would be JetPack 4.6 for Ubuntu 18.04 and JetPack 5.0.2 for Ubuntu 20.04.

Good Morning, here is the system info:

![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/ea5c93cd-6f9e-4a34-9589-193ec4c7b30b)


![image](https://github.com/IntelRealSense/realsense-ros/assets/17780361/035a480e-dffa-471f-ae59-7cab264f8842)


It seems to be using Jetson 5.11.

**Comment by MartyG-RealSense** [comment]
JetPack 5.1.1 is fine for use with Ubuntu 20.04.  However, if librealsense has not been built from source code in RSUSB = true mode then 5.1.1 could be a problem, since librealsense supports the slightly earlier **5.0.2** JetPack version in SDK 2.54.1.  However, 5.0.2 support was not introduced until SDK 2.54.1 (you are using SDK 2.53.1) so in 2.53.1 the most recent supported JetPack version was **4.6**    

As there is no official support in the SDK for any JetPack 5 version until 2.54.1, using an RSUSB = true build of librealsense 2.53.1 from source code (which should bypass JetPack compatibility problems) is definitely worth considering to see whether it resolves your pointcloud enabling issue.  

Using SDK 2.54.1 and ROS2 wrapper 4.54.1 would be even better if possible for you to do so.

**Comment by MartyG-RealSense** [comment]
Hi @ndaley7  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by ndaley7** [comment]
> Hi @ndaley7 Do you require further assistance with this case, please? Thanks!



> JetPack 5.1.1 is fine for use with Ubuntu 20.04. However, if librealsense has not been built from source code in RSUSB = true mode then 5.1.1 could be a problem, since librealsense supports the slightly earlier **5.0.2** JetPack version in SDK 2.54.1. However, 5.0.2 support was not introduced until SDK 2.54.1 (you are using SDK 2.53.1) so in 2.53.1 the most recent supported JetPack version was **4.6**
> 
> As there is no official support in the SDK for any JetPack 5 version until 2.54.1, using an RSUSB = true build of librealsense 2.53.1 from source code (which should bypass JetPack compatibility problems) is definitely worth considering to see whether it resolves your pointcloud enabling issue.
> 
> Using SDK 2.54.1 and ROS2 wrapper 4.54.1 would be even better if possible for you to do so.

I have not had time to try these fixes, but will report back once I have.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update.  I look forward to your next report.  Good luck!
