### ISSUE TITLE
Adding realsense D435 camera to Turtlebot3 in gazebo

### ISSUE THREAD

**Issue by johnsonlin2001** [realsenseai/realsense-ros#2945]
Hi, I'm new to ROS and gazebo and have been trying to add a D435 camera to turtlebot3 in order to do tracking. I installed [turtlebot3 simulation package from ROBOTIS](https://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/). I also installed the intel ROS realsense gazebo plugin. So far I've been trying to modify the model.sdf file in "~/catkin_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_burger" to include the d435 camera model but this hasn't been working. I'm running ROS 1 kinetic on ubuntu 16.04. Does anyone know how I would go about doing this? 
Thank you.

**Comment by MartyG-RealSense** [comment]
Hi @johnsonlin2001  If you are using ROS1 Kinetic and 16.04 then Intel's old **ros_object_analytics** tool may be especially suited for you instead of using Gazebo, as it is compatible with RealSense 400 Series cameras and the ROS1 wrapper and provides tracking functionality.

https://github.com/intel/ros_object_analytics

In regard to your original question, the link below features a Turtlebot burger user aiming to modify it for use with a RealSense D435i camera.  They were provided with instructions for adding the camera to `catkin_ws/src/turtlebot3/turtlebot3_description/urdf/turtlebot3_burger.urdf.xacro `

https://robotics.stackexchange.com/questions/22365/modifying-turtlebot3-to-include-different-camera

**Comment by MartyG-RealSense** [comment]
Hi @johnsonlin2001  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
