### ISSUE TITLE
Where does the timestamp of the published camera topic data come from?

### ISSUE THREAD

**Issue by tuzbtla** [realsenseai/realsense-ros#2963]
Where does the timestamp of published camera topic data (including depth images and rgb images) come from?
1. Inside the camera
2. The moment the data is received, like ros::Time::now()

Which one is right, or is it from somewhere else?

**Comment by MartyG-RealSense** [comment]
Hi @tuzbtla  There are a range of different timestamps that have different characteristics.  At https://github.com/IntelRealSense/librealsense/issues/2188#issuecomment-409985803 an Intel RealSense team member provides a list of timestamp types and descriptions for them.

If the librealsense SDK has support for **hardware metadata** enabled then **hardware timestamps** will be provided.  Otherwise, **software timestamps** based on the computer's clock will be used.

Hardware metadata support is enabled if: (1) the librealsense SDK is installed from DKMS packages; or (2) if librealsense is built from source code and a **kernel patch** has been applied to the Linux kernel; or (3) librealsense has been built from source code with the CMake flag **-DFORCE_RSUSB_BACKEND=TRUE** included in the CMake build instruction.

**Comment by tuzbtla** [comment]
Thanks, because I want to synchronize Time with other sensors, how do I turn off support for hardware metadata and use the time returned by ros::Time::now() instead?

**Comment by tuzbtla** [comment]
> 嗨，有一系列不同的时间戳具有不同的特征。在英特尔[实感/librealsense#2188（注释）](https://github.com/IntelRealSense/librealsense/issues/2188#issuecomment-409985803)中，英特尔实感团队成员提供了时间戳类型列表及其描述。
> 
> 如果 librealsense SDK 启用了对硬件**元数据**的支持，则将提供**硬件时间戳**。否则，将使用基于计算机时钟**的软件时间戳**。
> 
> 在以下情况下，将启用硬件元数据支持：（1） 从 DKMS 软件包安装 librealsense SDK;或 （2） 如果 librealsense 是从源代码构建的，并且**内核补丁**已应用于 Linux 内核;或 （3） librealsense 是从源代码构建的，CMake 构建指令中包含 CMake 标志 **-DFORCE_RSUSB_BACKEND=TRUE**。

Thanks, because I want to synchronize Time with other sensors, how do I turn off support for hardware metadata and use the time returned by ros::Time::now() instead?

**Comment by MartyG-RealSense** [comment]
If you disable a setting called **Global Time** which is enabled by default on RealSense 400 Series cameras then ROS will use its own timing sync system.  More information about this can be found at https://github.com/IntelRealSense/realsense-ros/issues/1906#issuecomment-851794554

**Comment by tuzbtla** [comment]
Thanks.
