### ISSUE TITLE
How to reduce the effect of the sunlight and object color? [Depth Camera, L515)

### ISSUE THREAD

**Issue by kevinDrawn** [realsenseai/realsense-ros#2970]
Hello @MartyG-RealSense,

I am encountering two problems with the depth camera (model: L515) that I'm using for a mobile manipulator. It is utilized both in the morning and at night, (indoor of the hospital). The depth values of the same relative place differ depending on the sunlight passing through the window, which changes with the time of day.

The second issue involves a black-colored sofa and refrigerator. When I view these objects through the depth map, they are not well recognized, especially in the black areas. 

How can I improve the precision quality? Could you recommend a filter, or should I consider changing the camera model?

Thank you.

**Comment by MartyG-RealSense** [comment]
Hi @kevinDrawn  The L515 camera model is sensitive to infrared light sources such as sunlight as it can interfere with the camera.  The RealSense 400 Series camera models are better suited to dealing with sunlight and a range of different day / night lighting conditions.  The **D435f** and **D455f** models are equipped with a light-blocking filter that can enhance depth quality.

As your L515 needs to be used in variable light conditions, setting it to use the **Short Range** camera configuration preset instead of the default 'Max Range' preset may provide better results.

In regard to difficulty in reading black objects, it is a general physics principle (not specific to RealSense) that dark gray and black colors absorb light, making it difficult for depth cameras to obtain detail from them.  Projecting a strong light onto such surfaces can help to bring out depth detail from them if it is required, like in the L515 case at https://github.com/IntelRealSense/librealsense/issues/6757 where a light-source is cast onto a black leather office chair.

**Comment by kevinDrawn** [comment]
Thank you for your rapid response.

I have another question.

If I shine a strong light on the black surface, could this light affect the quality of the depth measurement, similar to the issue I mentioned with sunlight?

Hmm... It may not be affected because the power light is not infrared light, right?

**Comment by MartyG-RealSense** [comment]
A strong light source on a black surface should be less likely to result in a reflective glare that blinds the camera than a lighter surface color such as white.

**Comment by kevinDrawn** [comment]
I totally understand.

Lastly, where can i change the configuration of the variable light conditions?

Thank you a lot!

**Comment by MartyG-RealSense** [comment]
In the RealSense Viewer tool, you can select Short Range from the drop-down menu beside the **Preset** option near the top of the Viewer's options side-panel.

If you have a program script then https://github.com/IntelRealSense/librealsense/issues/11053#issuecomment-1297174433 has Python code for setting the Short Range preset.

https://github.com/IntelRealSense/librealsense/issues/9071#issuecomment-878552273 has C++ code for setting it.

**Comment by kevinDrawn** [comment]
Thank you so much!

In https://github.com/IntelRealSense/librealsense/issues/6757, it is recommended to use the D435 camera, which has IR recognition. So, can the D435 model provide more stable precision on black or gray surfaces than L515?

**Comment by MartyG-RealSense** [comment]
Difficulty in reading gray / black surfaces is a general physics problem rather than a RealSense-specific one. However, using a 400 Series camera such as D435 may provide an advantage in regard to its built-in infrared projector component, which can project a pattern of IR dots onto a surface (which are invisible to the human eye) to aid the camera's depth analysis.

<img width="790" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/41145062/61eda086-d74b-44aa-9f63-9eda7a820733">

Most RealSense 400 Series camera models except D405 are equipped with a projector.  This includes D415, D435, D435i, D435f, D435if, D455, D455f, D456 and D457.

**Comment by kevinDrawn** [comment]
Thank you!! I'll try it later.

**Comment by MartyG-RealSense** [comment]
Hi @kevinDrawn  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @kevinDrawn  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
