### ISSUE TITLE
Building ROS2 wrapper - locating RealSense SDK 2.0

### ISSUE THREAD

**Issue by Genozen** [realsenseai/realsense-ros#2979]
###Setup
RB5 SOM board
Ubuntu 18.04 LTS
Kernel 4.19
Camera D455

### Issue Description
Hello, I've built my realsense SDK 2.0 from source on the SOM board and the example works properly. (https://developer.qualcomm.com/forum/qdn-forums/hardware/qualcomm-robotics-rb5-development-kit/68234)

Ubuntu 18.04 LTS - Kernel 4.19

I'm now trying to build the ROS 2 Wrapper, where can I tell colcon build to look for the SDK folder? because just doing colcon build couldn't not find the RealSense SDK 2.0...

Also ran into some issues when executing `rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y`
where it cannot find [tf2_ros_py], despite I already sudo apt installed on it... (originally it works untill I install other packages then it broke...)

**Comment by MartyG-RealSense** [comment]
Hi @Genozen  The simple procedure at the link below for installing librealsense may work better for you.

https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md

In regard to installing the ROS2 wrapper: the procedure that you are using will install the latest ROS2 wrapper version, but that version is designed to be used only with ROS2 Humble and Iron, which should be used with Ubuntu 22.04 rather than 18.04.  It is therefore going to be difficult to install a ROS2 wrapper version that will work with 18.04, since the ROS2 version used with 18.04 would have to be Eloquent.

The easiest route to a solution may be to use ROS1 Noetic instead of ROS2 if it is possible for you to do so, and then first remove your current installation of librealsense and then use the command below to build correctly matching versions of librealsense and the ROS1 wrapper together at the same time.  The command should install librealsense 2.50.0 and ROS1 wrapper 2.3.2.

`sudo apt-get install ros-$ROS_DISTRO-realsense2-camera`

https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy?tab=readme-ov-file#method-1-the-ros-distribution

**Comment by MartyG-RealSense** [comment]
Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
