### ISSUE TITLE
"Segmentation fault (core dumped)" installing sdk and wrapper from ros server

### ISSUE THREAD

**Issue by MFHuniovi** [realsenseai/realsense-ros#2997]
* Before opening a new issue, we wanted to provide you with some useful suggestions (Click "Preview" above for a better view):

    * Consider checking our ROS RealSense Wrapper documentation [README](https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/README.md).
    * Have you looked in our [Discussions](https://github.com/IntelRealSense/realsense-ros/discussions)?
    * Try [searching our GitHub Issues](https://github.com/IntelRealSense/realsense-ros/issues) (open and closed) for a similar issue.

* All users are welcomed to report bugs, ask questions, suggest or request enhancements and generally feel free to open new issue, even if they haven't followed any of the suggestions above :)

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | {D435i }                          | 
| Firmware Version                   | (5.15.1)                          | 
| Operating System & Version |   { Linux (Ubuntu  22.04.3 LTS) } | 
| Kernel Version (Linux Only)    |  ( 5.15.71)                                                                       | 
| Platform                                 | DEBIX Model A Industrial Single Board Computer 8gb                          |
| Librealsense SDK Version       |  { 2.54.1-1jammy.20240125.204242 }                                                    | 
| Language                               |  {}         | 
| Segment			         |  {Robot}                             | 
| ROS Distro			         |  {Humble }                                           | 
| RealSense ROS Wrapper Version   |  { 4.54.1-1jammy.20240126}                                                  | 

### Issue Description
I have installed from ros servers the sdk and the wrapper in principle correctly since no error came out but then any command I do always gives the same result "segmention fault (core dumped)".
"segmention fault
"error"
![image](https://github.com/IntelRealSense/realsense-ros/assets/71136753/8b1845ea-9651-492f-a733-b83f4746b92c)

installation
![image](https://github.com/IntelRealSense/realsense-ros/assets/71136753/e70213bc-35ea-4248-8cbe-2ce03f8e8d52)

Update
I have installed compiling the sdk in release mode and the wrapper in release mode but now I have a high cpu usage 120-150% and if I want to get the information of a topic I get the following error 
![image](https://github.com/IntelRealSense/realsense-ros/assets/71136753/a1720832-f691-419c-adce-65a0d1746fd1)

**Comment by MartyG-RealSense** [comment]
Hi @MFHuniovi  Thanks very much for the update.  Have you enabled the gyro and accel topics (which are disabled by default) and combined them together into a single `/imu` topic using the `unite_imu_method` parameter, please?

`ros2 run realsense2_camera realsense2_camera_node --ros-args -p enable_gyro:=true -p enable_accel:=true -p unite_imu_method:=2`

**Comment by MFHuniovi** [comment]
Sorry I didn't put the command I use, it is the following: 
ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true enable_accel:=true enable_gyro:=true unite_imu_method:=2 diagnostics_period:=3.141596
 I have enabled these two calculations because to calculate an odom I am using the robot_pose_ekf and I am passing it a single imu
 
 From the camera I would only need the imuand a lens to see in black and white for now, can you help me with the parameters? Is there any documentation that explains more in detail the parameters and if they affect more or less the performance of the cpu and memory?

**Comment by MartyG-RealSense** [comment]
Among the parameters that you are using, pointcloud is likely to be the most processing intensive.  Depth-color alignment - align_depth.enable - and post-processing filters can also consume processing resources.

Scrolling down the front page of the ROS2 wrapper, you can find documentation for some of the features of the wrapper.

https://github.com/IntelRealSense/realsense-ros

 The link below is also a helpful official reference.

https://www.intelrealsense.com/ros/

If a particular parameter that you are interested in is not listed in the official documentation then you can search this support GitHub for past issues that reference it by googling for **librealsense ros** and adding the function that you want to research onto the end of the search term, such as `librealsense ros "pointcloud.enable:=true"`

Putting quotation marks around a search term increases the relevancy of search results by searching for that exact phrase instead of similar sounding words.

In past issues involving DEBIX Model A, building librealsense from source code using an installation method that bypasses the kernel and then building the ROS wrapper separately from source code too has been recommended.  With 'exotic' computing hardware such as industrial computing boards, bypassing the kernel can result in a more stable librealsense installation.  The link below has a librealsense build script for doing so that can be tried.

https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md

**Comment by MartyG-RealSense** [comment]
Hi @MFHuniovi  Do you require further assistance with this case, please?  Thanks!

**Comment by MFHuniovi** [comment]
Hello, no thanks :D

**Comment by MartyG-RealSense** [comment]
Thanks very much @MFHuniovi for the update!
