### ISSUE TITLE
Framerate changes to 15 fps when I disable auto exposure

### ISSUE THREAD

**Issue by Guochh01** [realsenseai/realsense-ros#3087]
| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       |  D435i                    | 
| Firmware Version                   | 5.15.1                 | 
| Operating System & Version |   Ubuntu 20.04 | 
| Kernel Version (Linux Only)    |  5.15.0-105-generic                                                                      | 
| Platform                                 | PC                          |
| Librealsense SDK Version       |  2.54.2                                                     | 
| Language                               |  C++         | 
| Segment			         |  Robot                           | 
| ROS Distro			         |              noetic                             | 
| RealSense ROS Wrapper Version   | 2.3.2                                              | 

### Issue Description
When I turn off Auto Exposure of the rgb camera, the fps parameter will be invalid and the fps drops to 15. Whether I set the Auto Exposure parameter in realsense-viewer or in ros launch file, it looks like this:

- Disable Auto Exposure

![image](https://github.com/IntelRealSense/realsense-ros/assets/72130032/4939da4a-d1ff-4dd6-bd62-f83e7704295e)

- Enable Auto Exposure
 
![image](https://github.com/IntelRealSense/realsense-ros/assets/72130032/6dafac4e-a3eb-41b6-843a-380fb2f052b7)

Is it true that if I turn off Auto Exposure I can't set the frame rate, it only stays at 15 fps?

**Comment by MartyG-RealSense** [comment]
Hi @Chenhui-Guo  I was not able to replicate your FPS drop when disabling auto-exposure.  I found though that if FPS was set to 60 like in the above image and I artifically forced an FPS drop by increasing the manual RGB exposure value then it returned to 60 if RGB exposure was set to a value of 78.

**Comment by Guochh01** [comment]
Thanks for the reply! @MartyG-RealSense I tried it the way you said, after disabling auto-exposure, setting the RGB exposure value affects the frame rate. When the exposure value was set above 160, the frame rate started dropping from 60. 

- Exposure value is 160, frame rate is 59.53

![image](https://github.com/IntelRealSense/realsense-ros/assets/72130032/cde1a401-296d-4d12-bd62-49fab3c2bfa3)

- Exposure value is 700, frame rate is 14.25

![image](https://github.com/IntelRealSense/realsense-ros/assets/72130032/98574412-444e-48b0-9741-6eb87e07a95f)


I need to set a high exposure value for dark scenes, e.g. 600. Does that mean the RGB frame rate won't reach the 60 fps I set? Is low frame rate due to high exposure a hardware bottleneck for the D435i?

I still want to ask if there is any other way to get the frame rate up? Looking forward to your reply!

**Comment by MartyG-RealSense** [comment]
The mathematics of how exposure affects FPS is described at https://github.com/IntelRealSense/librealsense/issues/1957#issuecomment-400715579

There is not a way to avoid the FPS drop when using an RGB exposure value of 600, unfortunately.

You can though increase the RGB **Brightness** setting to brighten the RGB image without affecting FPS.

If you needed the RGB image to be able to 'see in the dark' then the alternative would be to place an external lamp near your D435i camera, or instead use a RealSense camera model that supports streaming RGB from the left infrared sensor so that the camera's IR emitter enables the camera to provide a clear image in the dark.  This feature is available on D405, D415 and the D455 type models (D455, D455f, D456, D457).  The dots on the image below, taken by a D455, are from the camera's infrared pattern projector that enables dark-environment use of the camera.

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/0c92a004-c9f9-4881-b36a-ee14b5709e75)

**Comment by Guochh01** [comment]
Thanks for the advice, you've solved my doubts. I will try to increase RGB Brightness.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  I'm pleased that I could help.  :)
