### ISSUE TITLE
How to calibrate D435 using checkerboard underwater?

### ISSUE THREAD

**Issue by WencaiShan** [realsenseai/realsense-ros#3117]
Hello! I would like to use my D435 underwater, but the depth performance is not good underwater, so I need to calibrate it. 
I plan to use a checkerboard for calibration. Should I use dynamic calibration or on-chip calibration? Are there any operational guidelines or steps I can  to? 
Or is there any other way to solve this problem?

Thank you!
![compare](https://github.com/IntelRealSense/realsense-ros/assets/69716030/2c97e0b1-a033-40f3-81cf-a7fc4d8d5521)

**Comment by MartyG-RealSense** [comment]
Hi @WencaiShan  There is an extensive technical discussion about calibrating underwater at https://github.com/IntelRealSense/realsense-ros/issues/1723

The discussion is so long that a lot of it is hidden under a cut at https://github.com/IntelRealSense/realsense-ros/issues/1723#issuecomment-802741234 so I recommend going there first and clicking 'Load More' to uncover the full discussion and then returning to the start.

If you are calibrating underwater instead of the air then the Dynamic Calibration tool is typically used.  For large water environments such as a swimming pool or the ocean, a large calibration board target is recommended instead of an A4 / US Letter paper size one.  Intel offer a large calibration target board product in the official RealSense Store for $1500 USD.

https://store.intelrealsense.com/buy-intel-realsense-d400-cameras-calibration-target.html

**Comment by MartyG-RealSense** [comment]
Hi @WencaiShan  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
