### ISSUE TITLE
ROS parameter: usb_port_id is not used

### ISSUE THREAD

**Issue by shaun-edwards** [realsenseai/realsense-ros#312]
branch: development

The [realsense_camera](http://wiki.ros.org/realsense_camera) documentation (possibly out of date) specifies the `usb_port_id` can be used in place of the serial number to be used to connect to a specific camera on a specific usb bus/port.  I would like to use this same functionality to connect to two different cameras (independent of serial number).  Is this supported?  Note: I would like to specify the bus, since I believe USB ports are assigned dynamically, based on the order in which things are connected.

I am happy to provide a PR for such functionality if it doesn't exist.

As near as I can tell the [BaseRealSenseNode::getParameters()](https://github.com/intel-ros/realsense/blob/development/realsense_ros_camera/src/base_realsense_node.cpp#L99-L167) does not load this parameter.  The [RealSenseNodeFactory::onInit()](https://github.com/intel-ros/realsense/blob/development/realsense_ros_camera/src/realsense_node_factory.cpp#L48-L65) method checks the serial number using `get_info(RS2_CAMERA_INFO_SERIAL_NUMBER);` before connecting, but does not mention the USB port.  I'm not certain which `get_info` method should be used to query the USB bus/port though.

**Comment by icarpis** [comment]
Hello @shaun-edwards, the [realsense_camera](http://wiki.ros.org/realsense_camera) wiki page is relates to [ROS wrapper 1.0](https://github.com/intel-ros/realsense/releases/tag/1.8.1) (branch: indigo-devel) which is not supports the Intel D400 cameras. Currently there isn't ROS wiki page for the [ROS wrapper 2.0](https://github.com/intel-ros/realsense/tree/development).

A functionality of connecting to a specific camera using the `usb_port_id` is not implemented yet.
In order to implement this feature you can use `RS2_CAMERA_INFO_PHYSICAL_PORT` to get the full device path as following:
`auto dev_path = _dev.get_info(RS2_CAMERA_INFO_PHYSICAL_PORT)`
`dev_path => "/sys/devices/pci0000:00/0000:00:14.0/usb4/4-4/4-4:1.0/video4linux/video1"`

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
