### ISSUE TITLE
Last release documentation is not clear about the version of librealsense/firmware to use

### ISSUE THREAD

**Issue by edgarcamilocamacho** [realsenseai/realsense-ros#3205]
In the release changes you see these two items:

![image](https://github.com/user-attachments/assets/3396994b-ea67-465c-b443-a6d7b40bf8ec)

But when you check the code changes on them, they are not coherent:

![image](https://github.com/user-attachments/assets/0a21edc1-7127-46a6-9931-737c8048273e)

![image](https://github.com/user-attachments/assets/a3de404b-df74-4dbd-bdef-3105e76907e9)

**Comment by MartyG-RealSense** [comment]
@edgarcamilocamacho  The second and third images that you kindly provided are from the **ros2-development** branch of the ROS2 wrapper.

However, the naming of the wrapper has recently changed.  **ros2-development** used to be the default Master branch of the wrapper.  However, the Master branch is now **ros2-master**

After this change, the ros2-development branch is now the development branch for the next upcoming wrapper version, which only has source code available for it and not packages.

ros2-development will be in flux because it has changes being continuously added to it, whilst ros2-master is the branch that most RealSense ROS2 users will be using.  Therefore, the notes that can be relied upon for accuracy are the ones in the wrapper release notes (the first image that you posted above).

**Comment by edgarcamilocamacho** [comment]
Yes, you right, the tag itself is correctly set:

https://github.com/IntelRealSense/realsense-ros/blob/4.56.1/realsense2_camera/CMakeLists.txt#L121
https://github.com/IntelRealSense/realsense-ros/blob/4.56.1/README.md?plain=1#L122

What generated the confussion were the links from the release documentation.

Thanks!

**Comment by MartyG-RealSense** [comment]
You are very welcome.  I'm pleased I could help!
