### ISSUE TITLE
Synchronize the color lens of D435I with an external sensor

### ISSUE THREAD

**Issue by RtJinxuWang** [realsenseai/realsense-ros#3257]
| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { **D435i** }                          | 
| Firmware Version                   | (Open RealSense Viewer --> Click info)                          | 
| Operating System & Version |   { Linux (Ubuntu 18/20/22) } | 
| Kernel Version (Linux Only)    |  (e.g. 5.4)                                                                       | 
| Platform                                 | NVIDIA Jetson                           |
| Librealsense SDK Version       |  { 2.<?>.<?> }                                                    | 
| Language                               |  {C/C#/labview/opencv/pcl/python/unity }         | 
| Segment			         |  {Robot/Smartphone/VR/AR/others }                             | 
| ROS Distro			         |  {Iron/Humble/Rolling/etc.. }                                           | 
| RealSense ROS Wrapper Version   |  {4.51.1, 4.54.1, etc..}                                                  | 

Hello. When the Intel RealSense D435I is in slave mode and using external triggering, does the trigger voltage have to be 1.8V? Can it be replaced with 3.3V instead?

**Comment by MartyG-RealSense** [comment]
Hi @JasonWang9805  Yes, the external trigger pulse's voltage has to be 1.8V in order to work with Pin 5 (the sync pin) on the slave camera.

If generating a 1.8V trigger is a problem for your external trigger equipment then you could generate a 3.3V pulse and then use an electronics component called a voltage shifter, or level shifter, to reduce the 3.3V to 1.8V so it works with the camera.  An example of a level shifter that should work is the SparkFun one referenced at https://github.com/IntelRealSense/librealsense/issues/12064#issuecomment-1661991065

**Comment by MartyG-RealSense** [comment]
Hi @JasonWang9805  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
