### ISSUE TITLE
This issue was actually caused by interference from OptiTrack motion capture sensors in the same space as the L515. Turning them off and the L515 data is fixed. This does not vary with CPU architecture.

### ISSUE THREAD

**Issue by Ju6276** [realsenseai/realsense-ros#3258]
This issue was actually caused by interference from OptiTrack motion capture sensors in the same space as the L515. Turning them off and the L515 data is fixed. This does not vary with CPU architecture.

_Originally posted by @calvertdw in https://github.com/IntelRealSense/realsense-ros/issues/1762#issuecomment-802225432_
          hi! i am now using l515 to get rgb-d images and point clouds, the wavelength of Optitrack is 860nm, so i get the bad images. So can i use a IR cut filter(but l515 has also 860nm laser
? Could someone can help me? Thanks in advance.

![rgbd](https://github.com/user-attachments/assets/bfbcc09a-3c7f-4d5c-a351-8f61c2770150)
![pointcloud](https://github.com/user-attachments/assets/27137186-aef4-4cdf-ba10-a9245ee37c6a)
)

**Comment by MartyG-RealSense** [comment]
Hi @Ju6276  The L515 lidar depth camera uses different camera technology to the 400 Series depth cameras.  To quote from the L515 data sheet document: "L515 uses an IR laser, a MEMS, an IR photodiode, an RGB imager, a MEMS controller, and a vison ASIC.  The MEMS is used to scan the IR laser beam over the entire field-of-view (FOV).  The L515 vision ASIC will process the data from the reflected beam captured by the photodiode and will output a depth point representing the accurate distance of a specific point in the scene from the camera".

So in short, as the IR laser light has to return to the camera from a surface in order for depth for that surface to be calculated, putting an IR-blocking filter over the laser's aperture would likely severely impair the camera's images.

If you are writing your own program then you could try instead improving the image with a **visual preset** camera configuration, which can be applied with script code.  

A user guide document for the L515 model can be downloaded as a PDF from the link below.  Page 10 discusses the range of presets available (which are different from the 400 Series cameras' presets) and the effects that they have.

https://support.intelrealsense.com/hc/en-us/articles/360051646094-Intel-RealSense-LiDAR-Camera-L515-User-Guide

In many situations, using the 'Short Range' preset instead of the default 'Max Range' preset in order to reduce the camera's Laser Power and Receiver Gain values has a positive effect on the image.

**Comment by Ju6276** [comment]
Thank you for your fast reply. I will read the douc. Do you have any examples to preset the visual moduls?

**Comment by MartyG-RealSense** [comment]
https://github.com/IntelRealSense/librealsense/issues/9071#issuecomment-878552273 has a C++ example for setting the preset and https://github.com/IntelRealSense/librealsense/issues/10496#issuecomment-1124667121 has code for Python.

**Comment by MartyG-RealSense** [comment]
Hi @Ju6276  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
