### ISSUE TITLE
What's the serial_no for d435 camera should I input in the launch file? 

### ISSUE THREAD

**Issue by 1075976432** [realsenseai/realsense-ros#469]
It seems that the TF frames were not same with the real d435 camera model after launched the file "rs_camera.launch". 
I guess the reason was miss of the serial_no in the launch file, so the default model was not d435 but other type.
Dose anyone know the serial_no for d435?
Thanks!

**Comment by neomanic** [comment]
Run `rs-enumerate-devices | grep Serial` to get the serial number.

**Comment by 1075976432** [comment]
@neomanic 
Thanks at first!
But the the result was same after input the serial_no gained by your method. 
The TF between **camera_link** and **camera_color_optical_link** was still not correct with the urdf model loaded by the view_d435.launch file which I think has the true frames parameters.
Maybe there is no option to change the TF frames in this Ros package when launching rs_camera.launch.

**Comment by neomanic** [comment]
Ah, okay. You're saying the tfs provided by the URDF doesn't match reality? I can't help much then, I've been happy with them, but admittedly I haven't looked too closely at them.

**Comment by fiorano10** [comment]
@1075976432 I think the urdf has been updated in the new release, which should make more sense.

**Comment by doronhi** [comment]
@1075976432, Did the update fix it?

**Comment by 1075976432** [comment]
@doronhi 
The urdf has the correct parameters of frames. However, when launched the **rs_camera.launch** file, the problem still exist.
I solve the problem by broadcasting a right frame....

**Comment by doronhi** [comment]
I am not sure what you mean by “broadcasting a right frame “. I am not sure what is the exact problem you describe.
Is your issue related to #497?

**Comment by atyshka** [comment]
@doronhi  Here is a detailed video of the issue. I started the model which had the correct transforms but then everything is offset when the driver is started.
![peek 2018-11-13 10-36](https://user-images.githubusercontent.com/19317207/48424265-4a8cfb80-e730-11e8-9520-5be64412a72c.gif)
When the driver is started the frames no longer line up with the geometry.
Also @1075976432 I believe you should change the title of your post, this issue is about incorrect transforms and that has nothing to do with the serial no.
