### ISSUE TITLE
Roslaunch realsense2_camera rs_camera.launch error

### ISSUE THREAD

**Issue by BobLim93** [realsenseai/realsense-ros#479]
I encounter this when I run roslaunch realsense2_camera rs_camera.launch 

[realsense2_cameras_camera.launch] is not  a launch file name The traceback for the exception was written to the log file

**Comment by fiorano10** [comment]
@BobLim93 Can you auto-complete the path using 'tabs' to launch it? If you can't then you probably need to build your workspace before using it.

**Comment by freemanlo** [comment]
Did you run "$ source devel/setup.bash" to have your build setup? Then, you can run the launch file.

**Comment by doronhi** [comment]
Based on your error message, it possible that instead of writing:
`roslaunch realsense2_camera rs_camera.launch`
you typed:
`roslaunch realsense2_cameras_rs_camera.launch`

That's how I managed to reproduce the error:
`
doronhi@ubuntu:~/catkin_ws$ roslaunch realsense2_cameras_rs_camera.launch
[realsense2_cameras_rs_camera.launch] is not a launch file name
The traceback for the exception was written to the log file
`
Is that the case?
