### ISSUE TITLE
An error has occurred during frame callback: null pointer passed for argument "frame_ref"

### ISSUE THREAD

**Issue by rdaems** [realsenseai/realsense-ros#489]
When I set enably_sync = true, align_depth = true and enable_pointcloud = true, I get an error upon trying to view the aligned images:
An error has occurred during frame callback: null pointer passed for argument "frame_ref"

This does not happen when I disable the pointcloud.

D415 
ROS wrapper 2.1.0

**Comment by vossie11** [comment]
Same problem here. 

Realsense D435
ROS wrapper v2.1.0
librealsense v2.16.1

**Comment by atyshka** [comment]
Same problem
D435
ROS Wrapper 2.1.0
librealsense 2.16.1
ROS Melodic, Ubuntu 18.04

**Comment by atyshka** [comment]
I only get the issue when attempting to subscribe to the camera/aligned_depth_to_color/image_raw topic

**Comment by arb93** [comment]
Same problem here as well.
Realsense D415
ROS Kinetic
librealsense v2.16.1

**Comment by atyshka** [comment]
Haven’t had a lot of time to go through the latest commits, but this stands out to me from commit 043be569e1334ba447fe85bca1a024db37085ed6 from base_realsense_node.cpp:
    // if(0 != info_publisher.getNumSubscribers() ||
    //    0 != image_publisher.first.getNumSubscribers())
    {
        auto width = 0;
        auto height = 0;
The if wasn’t commented out before, maybe this has something to do with it. @doronhi can you please explain this code? Also, with all the filters stuff you’ve been implementing I think we’d all appreciate if the heavy development was done on a different branch as a lot of people depend on this package and breaking changes on master isn’t good 😕

**Comment by doronhi** [comment]
The commented out lines are a mistake that shouldn't have happened. It is already corrected in the next commits and will be tagged in a new version, hopefully early next week with the release of librealsense 2.16.2

As for the error:
`
An error has occurred during frame callback: null pointer passed for argument "frame_ref"
`

It is a bug. Fixed in the last commit, especially in the public development branch, for those with need to take before the new release.
I also Added a unit test for that case, to avoid future mistakes like that.

The filters were added in the main branch because they were needed for many users. The bugs that appeared are truly regrettable and we'll try to avoid them.

**Comment by atyshka** [comment]
@doronhi Thanks for the fix and clarification, I’m sorry if I seemed critical. Should the latest commit also fix #491 ?
