### ISSUE TITLE
/usr/include/librealsense2/hpp/rs_sensor.hpp:109:13: error: no match for call to ‘(rs2::asynchronous_syncer) (rs2::frame)’              on_frame_function(frame{ fref });

### ISSUE THREAD

**Issue by lucasjinreal** [realsenseai/realsense-ros#525]
All version are build error, is that master ros package not compatible with realsense2????

**Comment by doronhi** [comment]
Without further information as to what OS you use, what versions did you try or, preferably, the build log, it a little hard to see the problem.
Since the latest version appears to work, my only guess right now is that you somehow ended up with a mixture of librealsense and realsense2_camera versions. Maybe an old librealsense.so file lurking around.
Could you try over on a new machine?
