### ISSUE TITLE
Benefits of using realsense rosbag instead of the regular rosbags

### ISSUE THREAD

**Issue by pedropgusmao** [realsenseai/realsense-ros#618]
Hello,

In my current application, I am using multiple sensors (including a thermal camera on one computer and a D435 on another PC) that need to be synchronized according to their timestamps. I have noticed, however,  that rosbags recorded with the regular realsense software will produce rosbags with initial time as January 1st 1970, which hinders my ability to perform any kind of timestamp matching across different (synchronized) machines.  My questions are: 

Do I lose any capability by using regular **rosbag record -a** instead of realsenses recording application?

Can I actually get all the information from the produced rosbag as I would from the realsense software without loss of frames, and would I still be able to perform post-processing operations on the recorded data? 

Thanks for your support.

**Comment by doronhi** [comment]
The bagfile saved by realsense-viewer contains several topics.
The 'metadata' topic contains system time.
In python you could see it like that:
```
>>> import rosbag
>>> bag = rosbag.Bag(filename)
>>> mmsgs = [msg for topic, msg, t in bag.read_messages(topics=['/device_0/sensor_1/Color_0/image/metadata'])]
>>> systime = [msg for msg in mmsgs if 'system_time'==msg.key]
 
>>> import datetime
>>> datetime.datetime.fromtimestamp(float(systime[0].value)/1000)
datetime.datetime(2019, 2, 18, 0, 55, 19, 132249)
```
The timestamp you saw is most likely the device hardware time. i.e., the time since you plugged it in.

The benefit of using the realsense bag file is that you can run the realsense2_wrapper with it using the option `rosbag_filename`. The wrapper will publish the images, giving them the current ROS time and you could enable or disable different filters every run to try out the post-processing benefits.
If you use the bag file saved using **rosbag record -a** you are confined to the output of the wrapper, not to the output of the camera.

Regarding loss of frames, that really depends on the kind of machine you use. I would use a very powerful machine for the recordings, regardless of the machine you will use later on.

**Comment by pedropgusmao** [comment]
Thanks, for this! 
So the hardware time will be when I plugged the camera in but not the the time when the first frame was recorded, right? Is there any way to recover this information? 
Again, 

Thanks!

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by pedropgusmao** [comment]
Sorry, I found the metadata you mentioned. Thanks!

**Comment by anug7** [comment]
@pedropgusmao , Did you find the meta-information needed to do the post processing like alignment?
